### ISSUE TITLE
rtl8188eu driver missing in 0.6.19

### ISSUE THREAD

**Issue by evilbunny2008** [ayufan-rock64/linux-build#100]
This is the driver for the [802.11n dongle](https://www.pine64.org/?product=usb-wifi-802-11bgn-rtl8188eu-for-rock64) from the pine64 store, but doesn't seem to exist in 0.6.19, but works fine in 0.6.15

**Comment by xalius** [comment]
The config options have been added, should be in the next release/pre-release.
