### ISSUE TITLE
"soft" reboot doesn't work

### ISSUE THREAD

**Issue by jebivetar** [ayufan-rock64/linux-build#101]
rebooting via cli ('reboot') or using the reset button on the board doesn't result in an actual reboot - i'm not sure what is happening as i don't have a serial adapter in my hands yet but i can't connect to the machine or ping it (no route).

have to unplug power manually which isn't exactly ideal.

debian stretch minimal 6.15 on 4.4 kernel

**Comment by itdaniher** [comment]
I'd be moderately surprised - I recall the R64 having unidirectional power switches on the USB ports. Do these not actually block 5V on V+?

**Comment by jebivetar** [comment]
no idea about any of that but,

 i wasn't able to reboot with my additions to fstab (for drives connected to said usb hub) commented out and the usb hub plugged in; and, 

i was able to reboot when the usb hub is not connected.

not exhaustive testing but figure i'd throw out an update in case anyone out there can replicate.

**Comment by rsmith16384** [comment]
I am using 4.4.114-rockchip-ayufan-193 and even with no USB devices connected I cannot reboot

**Comment by rsmith16384** [comment]
Same problem here with stretch, and no usb devices connected

**Comment by jebivetar** [comment]
i no longer have a powered usb hub connected, but one with bus power, and several drives attached (powered independently) and cannot reboot on either 188 or 195 with whatever the linux-rockchip package was for 188 or 6.26

**Comment by ayufan** [comment]
Thanks. I noticed that too. I'm trying figure out whys.

**Comment by ayufan** [comment]
This is fixed as of 0.6.30. The problem was DRAM issue. This requires upgrade of bootloader.

**Comment by nathanalderson** [comment]
I know it's a year later, but I'm seeing the same issue. Can anyone point me to directions for checking the bootloader version and upgrading?
