### ISSUE TITLE
Kernel halt after Kubernetes install - 0.6.18 Xenial

### ISSUE THREAD

**Issue by carlosedp** [ayufan-rock64/linux-build#106]
I've installed Kubernetes 1.9.3 on Rock64 using the _xenial-containers-rock64-0.6.18-180-arm64.img.xz_ image.
After the master node being up for some minutes, it started generating kernel dumps.

The complete boot dump with the halt that happened on line 845 is in: https://gist.github.com/carlosedp/6ea80434782604a80242b06f358329b4

**Comment by carlosedp** [comment]
To add some more information, same error occured on 0.6.15. The module I'm installing to Kubernetes is a load balancer (https://metallb.universe.tf/installation/). Source here https://github.com/google/metallb. I talked to the author and it's a Go app with netfilter rules for load balancing.

**Comment by carlosedp** [comment]
To add on this issue, with build 0.5.15 and Kernel 4.4.77 the problem does not show up.

**Comment by xalius** [comment]
Latest pre-release should be stable now.

**Comment by carlosedp** [comment]
Any idea on what was causing the kernel errors?

**Comment by ayufan** [comment]
Probably `CONFIG_SCHED_WALT`.
