### ISSUE TITLE
open-iSCSI driver tcp is not loaded. Load the module then retry command

### ISSUE THREAD

**Issue by LFAB3** [ayufan-rock64/linux-build#107]
Hello ayufan-rock64,
I have a problem with iSCSI, I tried with latest release and with pre-release kernel. You can reproduce this with following instructions as root:
1.- apt-get update
2.- apt-get upgrade
3.- apt-get dist-upgrade
4.- apt-get install open-iscsi
5.- systemctl start open-iscsi
6.- iscsiadm -m discovery -t sendtargets -p 192.168.1.3

iscsiadm: can not connect to iSCSI daemon (111)!
iscsiadm: Could not scan /sys/class/iscsi_transport.
iscsiadm: Could not scan /sys/class/iscsi_transport.
iscsiadm: Could not scan /sys/class/iscsi_transport.
iscsiadm: iSCSI driver tcp is not loaded. Load the module then retry the command.

iscsiadm: Could not perform SendTargets discovery: iSCSI driver not found. Please make sure it is loaded, and retry the opera
root@rock64

root@rock64:~# uname -a
Linux rock64 4.4.77-rockchip-ayufan-136 #1 SMP Thu Oct 12 09:14:48 UTC 2017 aarch64 GNU/Linux

Thx for your support

**Comment by xalius** [comment]
The config options have been added, should be in the next release/pre-release.

**Comment by LFAB3** [comment]
Ok, THX for your help solving this issue. :-)
