### ISSUE TITLE
AES not enabled on openmediavault build

### ISSUE THREAD

**Issue by woiza** [ayufan-rock64/linux-build#108]
I flashed "jessie-openmediavault-rock64-0.6.15-175-arm64.img.xz" on my sd card and noticed that AES is not enabled. I did a test with openssl ("openssl speed -elapsed -evp aes-256-cbc") and the numbers are at least 10 times lower compared to your containers build or DietPi.
Is it possible to enable hardware encryption and decryption on this build?

**Comment by ayufan** [comment]
It is possible that jessie is too old to support AES on openssl. Kernel definitely has crypto extensions compiled in.

**Comment by woiza** [comment]
Hmm bummer, Thanks for your quick response. I will try stretch then.
