### ISSUE TITLE
Software starts crash after update

### ISSUE THREAD

**Issue by fl-chris** [ayufan-rock64/linux-build#109]
HW: Rock64 with 4GB RAM and 32GB eMMC
OS: bionic-minimal-rock64-0.6.15-175-arm64

Some days ago, I did an update of the system and now programs like Geany and Lxterminal, often crash ?

I've tried to reinstall the OS, but the same thing happens.

A few slices of syslog:
*
*
Feb 22 22:52:01 rock64 rsyslogd-2007: action 'action 9' suspended, next retry is Thu Feb 22 22:53:01 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Feb 22 22:52:01 rock64 CRON[2996]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Feb 22 22:53:01 rock64 rsyslogd-2007: action 'action 9' suspended, next retry is Thu Feb 22 22:54:01 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Feb 22 22:53:01 rock64 CRON[3785]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Feb 22 22:53:05 rock64 Tor[2988]: Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 22 22:53:16 rock64 Tor[2988]: message repeated 2 times: [ Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.]
Feb 22 22:53:46 rock64 systemd[1]: Starting Cleanup of Temporary Directories...
Feb 22 22:53:46 rock64 systemd-tmpfiles[3847]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
Feb 22 22:53:46 rock64 systemd[1]: Started Cleanup of Temporary Directories.
Feb 22 22:54:01 rock64 rsyslogd-2007: action 'action 9' suspended, next retry is Thu Feb 22 22:55:01 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Feb 22 22:54:01 rock64 CRON[3868]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Feb 22 22:55:01 rock64 rsyslogd-2007: action 'action 9' suspended, next retry is Thu Feb 22 22:56:01 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Feb 22 22:55:01 rock64 CRON[3917]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Feb 22 22:55:01 rock64 CRON[3918]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Feb 22 22:55:26 rock64 kernel: [ 1028.985980] geany[1228]: unhandled level 1 translation fault (11) at 0x00000000, esr 0x92000005
Feb 22 22:55:26 rock64 kernel: [ 1028.985996] pgd = ffffffc0e2d71000
Feb 22 22:55:26 rock64 kernel: [ 1028.986299] [00000000] *pgd=0000000000000000, *pud=0000000000000000
Feb 22 22:55:26 rock64 kernel: [ 1028.986975] 
Feb 22 22:55:26 rock64 kernel: [ 1028.986989] CPU: 0 PID: 1228 Comm: geany Not tainted 4.4.103-rockchip-ayufan-175 #1
Feb 22 22:55:26 rock64 kernel: [ 1028.986994] Hardware name: Rockchip RK3328 Rock64 (DT)
Feb 22 22:55:26 rock64 kernel: [ 1028.987000] task: ffffffc0e2e4b700 task.stack: ffffffc0e2cc4000
Feb 22 22:55:26 rock64 kernel: [ 1028.987009] PC is at 0x7fa97f0260
Feb 22 22:55:26 rock64 kernel: [ 1028.987013] LR is at 0x7fa97f0308
Feb 22 22:55:26 rock64 kernel: [ 1028.987018] pc : [<0000007fa97f0260>] lr : [<0000007fa97f0308>] pstate: 80000000
Feb 22 22:55:26 rock64 kernel: [ 1028.987022] sp : 0000007fd2b1f430
Feb 22 22:55:26 rock64 kernel: [ 1028.987027] x29: 0000007fd2b1f430 x28: 0000007fd2b1f728 
Feb 22 22:55:26 rock64 kernel: [ 1028.987033] x27: 00000055b0e317a0 x26: 0000007fa9baaea0 
Feb 22 22:55:26 rock64 kernel: [ 1028.987040] x25: 0000007fa9daa000 x24: 0000007fa9daa000 
Feb 22 22:55:26 rock64 kernel: [ 1028.987047] x23: 0000000000000028 x22: 000000007fffffff 
Feb 22 22:55:26 rock64 kernel: [ 1028.987053] x21: 0000007fd2b1f538 x20: 0000000000000000 
Feb 22 22:55:26 rock64 kernel: [ 1028.987060] x19: 0000007fa77b8448 x18: 0000000000000000 
Feb 22 22:55:26 rock64 kernel: [ 1028.987066] x17: 0000007fa9e2f680 x16: 0000007fa929acb0 
Feb 22 22:55:26 rock64 kernel: [ 1028.987073] x15: 0000000000000000 x14: 0000000000000002 
Feb 22 22:55:26 rock64 kernel: [ 1028.987079] x13: 28207465675f7265 x12: 746e696f705f6369 
Feb 22 22:55:26 rock64 kernel: [ 1028.987086] x11: 000a64656c696166 x10: 20274c4c554e203d 
Feb 22 22:55:26 rock64 kernel: [ 1028.987092] x9 : 3d20296e6f697461 x8 : 636f6c5f65756c61 
Feb 22 22:55:26 rock64 kernel: [ 1028.987099] x7 : 7628207465675f72 x6 : 65746e696f705f63 
Feb 22 22:55:26 rock64 kernel: [ 1028.987105] x5 : 00000055b14a2f90 x4 : 00000055b1b634b0 
Feb 22 22:55:26 rock64 kernel: [ 1028.987112] x3 : 00000055b0dcb038 x2 : 0000007fa98ebbb4 
Feb 22 22:55:26 rock64 kernel: [ 1028.987119] x1 : 14ad2dc21cc54800 x0 : 00000028ffffffd8 
Feb 22 22:55:26 rock64 kernel: [ 1028.987124] 
Feb 22 22:55:54 rock64 kernel: [ 1056.398874] lxterminal[1122]: unhandled level 1 translation fault (11) at 0x00000001, esr 0x92000005
Feb 22 22:55:54 rock64 kernel: [ 1056.398888] pgd = ffffffc0e2c94000
Feb 22 22:55:54 rock64 kernel: [ 1056.399190] [00000001] *pgd=0000000000000000, *pud=0000000000000000
Feb 22 22:55:54 rock64 kernel: [ 1056.399842] 
Feb 22 22:55:54 rock64 kernel: [ 1056.399856] CPU: 2 PID: 1122 Comm: lxterminal Not tainted 4.4.103-rockchip-ayufan-175 #1
Feb 22 22:55:54 rock64 kernel: [ 1056.399867] Hardware name: Rockchip RK3328 Rock64 (DT)
Feb 22 22:55:54 rock64 kernel: [ 1056.399873] task: ffffffc0f4fc5280 task.stack: ffffffc0e2c60000
Feb 22 22:55:54 rock64 kernel: [ 1056.399881] PC is at 0x7f976a8260
Feb 22 22:55:54 rock64 kernel: [ 1056.399885] LR is at 0x7f976a8308
Feb 22 22:55:54 rock64 kernel: [ 1056.399890] pc : [<0000007f976a8260>] lr : [<0000007f976a8308>] pstate: 80000000
Feb 22 22:55:54 rock64 kernel: [ 1056.399895] sp : 0000007fc0235f60
Feb 22 22:55:54 rock64 kernel: [ 1056.399899] x29: 0000007fc0235f60 x28: 0000007fc0236230 
Feb 22 22:55:54 rock64 kernel: [ 1056.399906] x27: 0000007f97a6ada8 x26: 0000007f97a6adc8 
Feb 22 22:55:54 rock64 kernel: [ 1056.399912] x25: 0000007f97c62000 x24: 0000007f97c62000 
Feb 22 22:55:54 rock64 kernel: [ 1056.399919] x23: 0000000000000028 x22: 000000007fffffff 
Feb 22 22:55:54 rock64 kernel: [ 1056.399925] x21: 0000007fc0236028 x20: 0000000000000001 
Feb 22 22:55:54 rock64 kernel: [ 1056.399932] x19: 0000007f9598d568 x18: 0000000000001c00 
Feb 22 22:55:54 rock64 kernel: [ 1056.399939] x17: 0000007f972c1680 x16: 0000007f97d78cb0 
Feb 22 22:55:54 rock64 kernel: [ 1056.399945] x15: 0000000000000000 x14: 0000000000000008 
Feb 22 22:55:54 rock64 kernel: [ 1056.399952] x13: 74615f6727206e6f x12: 6974726573736120 
Feb 22 22:55:54 rock64 kernel: [ 1056.399958] x11: 64656c6961662027 x10: 4c4c554e203d3d20 
Feb 22 22:55:54 rock64 kernel: [ 1056.399979] x9 : 0000000000000000 x8 : 0000000000000000 
Feb 22 22:55:54 rock64 kernel: [ 1056.400003] x7 : 0000000000000000 x6 : 0000007f97da6948 
Feb 22 22:55:54 rock64 kernel: [ 1056.400025] x5 : 000000557116ed70 x4 : 000000557107ba50 
Feb 22 22:55:54 rock64 kernel: [ 1056.400032] x3 : 0000005570edf038 x2 : 0000007f977a7020 
Feb 22 22:55:54 rock64 kernel: [ 1056.400039] x1 : 0ef29f17b1d65600 x0 : 000000287fffffff 
Feb 22 22:55:54 rock64 kernel: [ 1056.400044] 
Feb 22 22:56:01 rock64 rsyslogd-2007: action 'action 9' suspended, next retry is Thu Feb 22 22:57:01 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Feb 22 22:56:01 rock64 CRON[3979]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Feb 22 22:57:01 rock64 rsyslogd-2007: action 'action 9' suspended, next retry is Thu Feb 22 22:58:31 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
*
*
*
Feb 22 23:18:24 rock64 systemd[1]: Started Hostname Service.
Feb 22 23:19:01 rock64 rsyslogd-2007: action 'action 9' suspended, next retry is Thu Feb 22 23:20:31 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Feb 22 23:19:01 rock64 CRON[5702]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Feb 22 23:20:01 rock64 CRON[5720]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Feb 22 23:20:28 rock64 kernel: [ 2531.059027] geany[4820]: unhandled level 1 translation fault (11) at 0x00000000, esr 0x92000005
Feb 22 23:20:28 rock64 kernel: [ 2531.059039] pgd = ffffffc0e5aac000
Feb 22 23:20:28 rock64 kernel: [ 2531.059352] [00000000] *pgd=0000000000000000, *pud=0000000000000000
Feb 22 23:20:28 rock64 kernel: [ 2531.060027] 
Feb 22 23:20:28 rock64 kernel: [ 2531.060042] CPU: 1 PID: 4820 Comm: geany Not tainted 4.4.103-rockchip-ayufan-175 #1
Feb 22 23:20:28 rock64 kernel: [ 2531.060046] Hardware name: Rockchip RK3328 Rock64 (DT)
Feb 22 23:20:28 rock64 kernel: [ 2531.060053] task: ffffffc0e5ab6e00 task.stack: ffffffc0e9cd4000
Feb 22 23:20:28 rock64 kernel: [ 2531.060061] PC is at 0x7f7c604260
Feb 22 23:20:28 rock64 kernel: [ 2531.060066] LR is at 0x7f7c604308
Feb 22 23:20:28 rock64 kernel: [ 2531.060071] pc : [<0000007f7c604260>] lr : [<0000007f7c604308>] pstate: 80000000
Feb 22 23:20:28 rock64 kernel: [ 2531.060075] sp : 0000007fc57a87c0
Feb 22 23:20:28 rock64 kernel: [ 2531.060080] x29: 0000007fc57a87c0 x28: 0000007fc57a8a50 
Feb 22 23:20:28 rock64 kernel: [ 2531.060087] x27: 0000007f7c9c6da8 x26: 0000007f7c9c6dc8 
Feb 22 23:20:28 rock64 kernel: [ 2531.060094] x25: 0000007f7cbbe000 x24: 0000007f7cbbe000 
Feb 22 23:20:28 rock64 kernel: [ 2531.060102] x23: 0000000000000028 x22: 000000007fffffff 
Feb 22 23:20:28 rock64 kernel: [ 2531.060109] x21: 0000007fc57a8888 x20: 0000000000000000 
Feb 22 23:20:28 rock64 kernel: [ 2531.060116] x19: 0000005566cd3200 x18: 0000000000000000 
Feb 22 23:20:28 rock64 kernel: [ 2531.060123] x17: 0000007f7cc43680 x16: 0000007f7c0aecb0 
Feb 22 23:20:28 rock64 kernel: [ 2531.060130] x15: 0000000000000000 x14: 0000000000000000 
Feb 22 23:20:28 rock64 kernel: [ 2531.060137] x13: 617628207465675f x12: 7265746e696f705f 
Feb 22 23:20:28 rock64 kernel: [ 2531.060144] x11: 000a64656c696166 x10: 20274c4c554e203d 
Feb 22 23:20:28 rock64 kernel: [ 2531.060151] x9 : 3d20296e6f697461 x8 : 636f6c5f65756c61 
Feb 22 23:20:28 rock64 kernel: [ 2531.060158] x7 : 7628207465675f72 x6 : 65746e696f705f63 
Feb 22 23:20:28 rock64 kernel: [ 2531.060165] x5 : 0000005566f60d20 x4 : 000000556725f750 
Feb 22 23:20:28 rock64 kernel: [ 2531.060172] x3 : 000000556659d038 x2 : 0000007f7c703020 
Feb 22 23:20:28 rock64 kernel: [ 2531.060179] x1 : 87e8f4418d4c9000 x0 : 0000005566691b29 
Feb 22 23:20:28 rock64 kernel: [ 2531.060185] 
Feb 22 23:20:48 rock64 dbus-daemon[481]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.26' (uid=0 pid=5732 comm="geany /var/log/syslog ")
Feb 22 23:20:48 rock64 systemd[1]: File /lib/systemd/system/systemd-hostnamed.service:33 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Feb 22 23:20:48 rock64 systemd[1]: Proceeding WITHOUT firewalling in effect!
Feb 22 23:20:48 rock64 rsyslogd-2007: action 'action 9' suspended, next retry is Thu Feb 22 23:22:18 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Feb 22 23:20:48 rock64 systemd[1]: Starting Hostname Service...
Feb 22 23:20:48 rock64 dbus-daemon[481]: [system] Successfully activated service 'org.freedesktop.hostname1'
Feb 22 23:20:48 rock64 systemd[1]: Started Hostname Service.
Feb 22 23:20:53 rock64 kernel: [ 2556.134047] geany[5732]: unhandled level 1 translation fault (11) at 0x00000000, esr 0x92000005
Feb 22 23:20:53 rock64 kernel: [ 2556.134077] pgd = ffffffc0e516e000
Feb 22 23:20:53 rock64 kernel: [ 2556.134465] [00000000] *pgd=0000000000000000, *pud=0000000000000000
Feb 22 23:20:53 rock64 kernel: [ 2556.135078] 
Feb 22 23:20:53 rock64 kernel: [ 2556.135089] CPU: 0 PID: 5732 Comm: geany Not tainted 4.4.103-rockchip-ayufan-175 #1
Feb 22 23:20:53 rock64 kernel: [ 2556.135094] Hardware name: Rockchip RK3328 Rock64 (DT)
Feb 22 23:20:53 rock64 kernel: [ 2556.135100] task: ffffffc0f4776e00 task.stack: ffffffc0e5cd0000
Feb 22 23:20:53 rock64 kernel: [ 2556.135108] PC is at 0x7fa70dc260
Feb 22 23:20:53 rock64 kernel: [ 2556.135143] LR is at 0x7fa70dc308
Feb 22 23:20:53 rock64 kernel: [ 2556.135149] pc : [<0000007fa70dc260>] lr : [<0000007fa70dc308>] pstate: 80000000
Feb 22 23:20:53 rock64 kernel: [ 2556.135153] sp : 0000007fcff47610
Feb 22 23:20:53 rock64 kernel: [ 2556.135157] x29: 0000007fcff47610 x28: 0000007fcff478e0 
Feb 22 23:20:53 rock64 kernel: [ 2556.135164] x27: 0000007fa749eda8 x26: 0000007fa749edc8 
Feb 22 23:20:53 rock64 kernel: [ 2556.135171] x25: 0000007fa7696000 x24: 0000007fa7696000 
Feb 22 23:20:53 rock64 kernel: [ 2556.135178] x23: 0000000000000028 x22: 000000007fffffff 
Feb 22 23:20:53 rock64 kernel: [ 2556.135184] x21: 0000007fcff476d8 x20: 0000000000000000 
Feb 22 23:20:53 rock64 kernel: [ 2556.135191] x19: 0000007fa50a0978 x18: 0000000000000000 
Feb 22 23:20:53 rock64 kernel: [ 2556.135197] x17: 0000007fa771b680 x16: 0000007fa6b86cb0 
Feb 22 23:20:53 rock64 kernel: [ 2556.135204] x15: 0000000000000000 x14: 000000000000000c 
Feb 22 23:20:53 rock64 kernel: [ 2556.135210] x13: 696f705f63696d6f x12: 74615f6727206e6f 
Feb 22 23:20:53 rock64 kernel: [ 2556.135217] x11: 000a64656c696166 x10: 20274c4c554e203d 
Feb 22 23:20:53 rock64 kernel: [ 2556.135223] x9 : 3d20296e6f697461 x8 : 636f6c5f65756c61 
Feb 22 23:20:53 rock64 kernel: [ 2556.135230] x7 : 7628207465675f72 x6 : 65746e696f705f63 
Feb 22 23:20:53 rock64 kernel: [ 2556.135236] x5 : 0000005591956790 x4 : 0000005591bc0b90 
Feb 22 23:20:53 rock64 kernel: [ 2556.135243] x3 : 0000005590c99038 x2 : 0000007fa71db020 
Feb 22 23:20:53 rock64 kernel: [ 2556.135249] x1 : b2306341f36c8500 x0 : 0000007fa768f1c0 
Feb 22 23:20:53 rock64 kernel: [ 2556.135256] 
Feb 22 23:21:01 rock64 CRON[5768]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
*
*

**Comment by xalius** [comment]
Latest pre-release should be more stable now.
