### ISSUE TITLE
Setting up Mali drivers from Minimal

### ISSUE THREAD

**Issue by interfect** [ayufan-rock64/linux-build#111]
I started with `xenial-minimal-rock64-0.6.22-188-arm64.img.xz` on my Rock64 and installed MATE and lightdm with apt. I also installed a bunch of random packages from Synaptic with "ayufan" in the version strings, which I think are from https://launchpad.net/%7Eayufan/+archive/ubuntu/rock64-ppa/

I now have a functional desktop, but `glxgears -info` still reports using llvmpipe instead of the real GPU.

What exctly do I need to install on the minimal images to set up the GPU drivers? Do I need to do something in particular with the X11 config to use them?

**Comment by ayufan** [comment]
This is supported if you do `install_desktop.sh <something>`.
