### ISSUE TITLE
GPT table not fit on pre-release 187 and 189

### ISSUE THREAD

**Issue by vasekch** [ayufan-rock64/linux-build#115]
ROCK64 4G - SD card (good quality and tested)

xenial-mate-rock64-0.6.21-187-arm64.img.xz
xenial-minimal-rock64-0.6.23-189-arm64

after dding .img onto card, various tools (fdisk, gparted, testdisk) complains about GPT 

```
# gparted /dev/mmcblk0
======================
libparted : 3.2
======================
Not all of the space available to /dev/mmcblk0 appears to be used, you can fix the GPT to use all of the space (an extra 25819136 blocks) or continue with the current setting?
```

If this is not fixed the image will boot up only once, after reboot it's stuck on
![image](https://user-images.githubusercontent.com/2572537/36846033-eed78c82-1d50-11e8-8376-cb71071e1615.png)

**Comment by ayufan** [comment]
Thanks. I will take a look at that.

**Comment by ayufan** [comment]
This is expected. The disk image is smaller than disk. GPT header is not stored at the end of disk.
