### ISSUE TITLE
systemd-gpt-auto-generate issue

### ISSUE THREAD

**Issue by shortyishere** [ayufan-rock64/linux-build#120]
get these on bionic...gpt_auto=0 fixes it..unless theres another way

**Comment by ayufan** [comment]
well, what you get? maybe some log? :)

**Comment by shortyishere** [comment]
https://bbs.archlinux.org/viewtopic.php?id=229412

this article on arch talks about it

**Comment by shortyishere** [comment]
Hmm I upgraded to newest kernel and pakcages I think the problem went away once I upgraded packages
