### ISSUE TITLE
eth1 resetting loop

### ISSUE THREAD

**Issue by inos-github** [ayufan-rock64/linux-build#121]
with kernel 4.4.114 build 193 there is a resetting loop of eth1 (about every second):
```
Rockchip integrated EPHY stmmac-1:00: rockchip_integrated_phy_fixup_100M: reset phy
rk_gmac-dwmac ff550000.ethernet eth1: Link is Down
rk_gmac-dwmac ff550000.ethernet eth1: Link is Up - 100Mbps/Half - flow control off
```

**Comment by shortyishere** [comment]
Same here

**Comment by inos-github** [comment]
As a workaround (eth1 is unused here), I have disabled ethernet1 in the device-tree:
```
#!/bin/bash
 
dts_org="/boot/dts.original"
dts_new="/boot/dts.new"
 
# Make sure only root can run the script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1

# install device-tree-compiler if not present
if ! command -v dtc; then
   apt install -y device-tree-compiler
fi

# copy and decompile dtb
cp /boot/efi/dtb /boot/dtb.original
dtc -I dtb -O dts -o $dts_org /boot/dtb.original
 
# disable ethernet1
eth1=$(sed -n -e 's/^.*ethernet1.*\(ethernet.*\)\".*$/\1/p' $dts_org)
cat $dts_org | tr '\n' '\f' | sed 's/\('$eth1'[^}]*status = \"\)okay/\1disabled/g' | tr '\f' '\n' > $dts_new
 
# compile new dts
dtc -O dtb -o /boot/efi/dtb $dts_new
```

**Comment by ayufan** [comment]
You can always use dtb overlays :)

Or. Just `unbind` specific interface.

I will check `eth1` soon.

**Comment by seocam** [comment]
Same here. Running `ip link eth1 down` the problem ceases. 
What's eth1 used for?

**Comment by seocam** [comment]
We have 3 devices at the office and only one of them is currently displaying those messages (even using the exactly same micro sd card).

**Comment by vasekch** [comment]
@seocam AFAIK, eth1 is secondary network interface on Pi P5+ pins - see [docs](http://files.pine64.org/doc/rock64/ROCK64_Pi-2%20_and_Pi_P5+_Bus.pdf) - so nothing everyone uses 
- disabling should be ok.

My approach to work around was to

1] disable NetworkManager `systemctl disable NetworkManager` and `systemctl disable tlp`, the latter has NetworkManager as dependency and will start it.

2] create a file `/etc/network/interfaces.d/eth1` containing single line `iface eth1 inet manual`

**Comment by xalius** [comment]
Latest pre-release (0.6.27) should fix this, eth1 is now disabled by default via dts...
