### ISSUE TITLE
Getting a lot of random kernel panics / spinlocks

### ISSUE THREAD

**Issue by wipeDx** [ayufan-rock64/linux-build#122]
Hello,
I'm getting a lot of kernel panics when doing specific as well as unspecific things.
I'm running a Rock64 with stable stretch minimal with 4Gigs of Ram and 64Gb eMMC module.
Kernel version is 4.4.77-rockchip-ayufan-136
Also, I'm running a btrfs setup on it. Though the issues were had when I first flashed dietpi on it.
On it is running a nextcloud server along with postgresql, plex and a jdownloader instance.

What I've noticed is I kernel panicked the rock twice while connecting to my nextcloud instance.
This was probably one of the instance where I did that:
[https://gist.github.com/wipeDx/0b0a7b885f50f88815fda12642d3e020](https://gist.github.com/wipeDx/0b0a7b885f50f88815fda12642d3e020)

The second kernelpanic that's still in my syslog seems to be caused by plex, even though it's just running in the background right now, not doing anything.

[https://gist.github.com/wipeDx/498da998a870f4aa7a6535ba42490259](https://gist.github.com/wipeDx/498da998a870f4aa7a6535ba42490259)

I'll update this as much as possible with recent kernelpanics and logs where it actually says spinlock on cpu.

**Comment by wipeDx** [comment]
Just started it again and wanted to sync my nextcloud on a different device, then this happened:

[https://gist.github.com/wipeDx/1f241730d47adec8d5e691f2c63bac08](https://gist.github.com/wipeDx/1f241730d47adec8d5e691f2c63bac08)
And the rock is unresponsive

**Comment by ayufan** [comment]
Try to use the pre-release kernel and see if this helps.

**Comment by wipeDx** [comment]
I tried kernel 4.16 -> bandwidth got below 100kbyte/s so I couldn't really do much with it. So I tried 4.15, which also had the same problem.
Now with 4.14, it stops booting (power LED blinks twice, then a short pause)

I'll debug that tomorrow with the serial console I guess

**Comment by ayufan** [comment]
Well, no. Try this: https://github.com/ayufan-rock64/linux-build/releases/download/0.6.25/linux-headers-4.4.114-rockchip-ayufan-193_0.6.25_arm64.deb.

**Comment by ayufan** [comment]
Still 4.4, but with latest patches and slightly different config.

**Comment by wipeDx** [comment]
Oh I see. Guess I'll still debug that very soon then.

Thanks for your amazingly fast support though!

**Comment by wipeDx** [comment]
Now I can't read the eMMC module anymore. I just can't. Guess the power LED blinking twice means there's a problem with it

**Comment by wipeDx** [comment]
Got the 4.4.114 finally installed on the eMMC (finally got it to show up again, if someone needs to know how:
if you can get into uboot somehow (via an SD for example), you can actually erase the whole eMMC via the mmc command)

But no dice. Here, in any way I try to create the btrfs partition and then boot, I end up with kernel panics.
I'm afraid this time I can't provide you any kernel panics, cause they're simply too huge. Overloading the serial terminal as well as (i think) the copy/paste buffer of my OS.

If I go: Flash on eMMC from SD -> convert mmcblk0p7 to btrfs and change the boot entry to look for a btrfs -> boot, I end up with a working system, but when doing a simple apt update and/or upgrade/install, I end up with a kernel panic caused by btrfs (if you wish, I can replicate that, it just takes a lot of time)
If I go: Flash on eMMC from SD -> boot eMMC -> reboot SD to convert btrfs and change the boot entry -> boot eMMC, I end up with a working system again, that kernel panics with a huge entry after just a few seconds.

I'm gonna try an earlier kernel now.

**Comment by ayufan** [comment]
You can use `screen` with file logging.

**Comment by wipeDx** [comment]
Okay, I've tried it with 4.4.191 now, same result.
This is approach 2 btw, first boot was after being converted to btrfs.
This is the kernel panic after apt upgrade

[https://gist.github.com/wipeDx/806977e5b5c4d545b30d7c6cd5e615c5](https://gist.github.com/wipeDx/806977e5b5c4d545b30d7c6cd5e615c5)

**Comment by wipeDx** [comment]
I tried again with my SD, falling into the same problems. Also not sure if you got notified on the gist, so I'm linking it here again.

[https://gist.github.com/wipeDx/806977e5b5c4d545b30d7c6cd5e615c5#file-kernel_panic_5_sd-txt](https://gist.github.com/wipeDx/806977e5b5c4d545b30d7c6cd5e615c5#file-kernel_panic_5_sd-txt)

**Comment by ayufan** [comment]
This should be fixed as of 0.6.30 (requires full install). We fixed some potential problem related to DRAM stability. Please comment if this is not solved and the issue will be re-opened.

**Comment by ayufan** [comment]
It is also possible to follow this: https://github.com/ayufan-rock64/linux-build/issues/152#issuecomment-377961475

**Comment by wipeDx** [comment]
I'm not entirely sure if this is related to my old problem, but now I can't seem to boot any of the images anymore.
Not even the original one I posted here.
Following builds have been tested:
`stretch minimal 0.5.15-136
stretch minimal 0.6.25-193
stretch minimal 0.6.30-208
stretch minimal 0.6.31-309
stretch minimal 0.6.32-310
stretch openmediavault 0.6.32-310`

All of them end up in the following scenario:
https://gist.github.com/wipeDx/d3c23f76523ba1c3e46124f8f0266e7a

Sometimes the trace ends with `Bad PC value`
Googling after that only brought some questionable results from 6-8 years ago, so I have no idea what to do anymore.
Can't boot anything anymore. I even tried booting from USB.

In contradiction, I tried booting the DietPi image and to my surprise, it worked.

If you need any more information, I'll gladly provide them
