### ISSUE TITLE
rock64_write_spi_flash.sh does not detect boot from mmcblk1 with / on USB

### ISSUE THREAD

**Issue by inos-github** [ayufan-rock64/linux-build#124]
due to unreliable USB3 detection within u-boot I am booting from mmc (/boot/efi) but with root (/) on USB.
Such situations are not detected by the script leading to an error.
To correct this, I did some changes to the script (mounts (p6) are tested against /boot/efi) :

```
MNT_DEV=$(findmnt /boot/efi -n -o SOURCE)
...
...
case $MNT_DEV in
    /dev/mmcblk0p6)
        write_nand loader /dev/mmcblk0p1
        ;;

    /dev/mmcblk1p6)
        write_nand loader /dev/mmcblk1p1
        ;;
...
```

**Comment by ayufan** [comment]
This is quite good change. Could you create a PR with that?

**Comment by ayufan** [comment]
Fixed with: https://github.com/ayufan-rock64/linux-build/commit/986671e9ab4800ab5e3fa372dabd02d2acb7ba10

**Comment by inos-github** [comment]
great, thank you very much!
