### ISSUE TITLE
bionic-minimal-rock64-0.6.25-193-arm64.img.xz can boot up once only. 

### ISSUE THREAD

**Issue by rontant** [ayufan-rock64/linux-build#126]
I tried the latest bionic-minimal-rock64-0.6.25-193-arm64.img.xz. It booted up fine but for one time only. The last several versions  had rather similar problem but it could be avoided by not rebooting while the "flash-kernel" process is running but with 193, no luck.  I just won't boot again ever after issuing "sudo reboot".

**Comment by vasekch** [comment]
Not sure why this was closed, just referencing to similar #127 . I had similar problem when doing "soft reboot", pressing reset button / power cycle booted ok.

**Comment by rontant** [comment]
flash-kernel was triggered somehow to run after the first successful login. If we do a soft reboot while this flash-kernel is still running, /boot/efi will get corrupted. As an interim workaround, wait for the flash-kernel to complete before doing the very first reboot. You can use this command to check "ps ax | grep flash" if it is still running or not. In the Pine IRC, I understand ayufan is aware of this issue but I am not sure if he's working on it.
