### ISSUE TITLE
Re issue 128: attempt to overwrite LibEGL.so

### ISSUE THREAD

**Issue by Pytheas54** [ayufan-rock64/linux-build#129]
I installed libmali-rk-dev as instructed
Thanks
Unfortunately, the same error still appears
```
dpkg: error processing archive /var/cache/apt/archives/libglvnd-dev_1.0.0-2ubuntu2_arm64.deb (--unpack):
 trying to overwrite '/usr/lib/aarch64-linux-gnu/libEGL.so', which is also in package libmali-rk-utgard-450-r7p0:arm64 1.6-1ayufan10
Errors were encountered while processing:
 /var/cache/apt/archives/libglvnd-dev_1.0.0-2ubuntu2_arm64.deb
```

**Comment by ayufan** [comment]
You don’t have to install libglvnd then

**Comment by timistof** [comment]
I'm trying to install freeglut3-dev, which fails on libglvnd-dev as well. I'm not sure this is problem with the distro, but in any case it's a conflict. 

Is it possible to remove "libmali-rk-utgard-450-r7p0:arm64 1.6-1ayufan10", installing freeglut3-dev and then again "libmali-rk-utgard-450-r7p0:arm64 1.6-1ayufan10" or is this a naive thought?

**Comment by Steven0706** [comment]
> I'm trying to install freeglut3-dev, which fails on libglvnd-dev as well. I'm not sure this is problem with the distro, but in any case it's a conflict.
> 
> Is it possible to remove "libmali-rk-utgard-450-r7p0:arm64 1.6-1ayufan10", installing freeglut3-dev and then again "libmali-rk-utgard-450-r7p0:arm64 1.6-1ayufan10" or is this a naive thought?

Did you solve the problem? I have the same issue as yours. Thanks.

**Comment by Steven0706** [comment]
> I installed libmali-rk-dev as instructed
> Thanks
> Unfortunately, the same error still appears
> 
> ```
> dpkg: error processing archive /var/cache/apt/archives/libglvnd-dev_1.0.0-2ubuntu2_arm64.deb (--unpack):
>  trying to overwrite '/usr/lib/aarch64-linux-gnu/libEGL.so', which is also in package libmali-rk-utgard-450-r7p0:arm64 1.6-1ayufan10
> Errors were encountered while processing:
>  /var/cache/apt/archives/libglvnd-dev_1.0.0-2ubuntu2_arm64.deb
> ```

did you solve it? how? Thank you !

**Comment by timistof** [comment]
No unfortunately not!

Sent from my teletypewriterphone.
