### ISSUE TITLE
Turning on ' Purge trash...' in Gnome/Settings/Privacy prevents shutdown

### ISSUE THREAD

**Issue by Pytheas54** [ayufan-rock64/linux-build#130]
... or so it seems to me....

**Comment by vasekch** [comment]
what version do you have? how did you install gnome?

**Comment by Pytheas54** [comment]
Clean -193 pre-release install - Gnome from your .sh file (3.27.92 today, cannot remember if there has been an upgrade since).
`shutdown now`  does work. 
Turning off " Purge trash..." enables shutdown from the pull-down menu

**Comment by Pytheas54** [comment]
Sorry, my bad
Turning on " Purge trash..." does  prevNOTent shutdown from the pull-down menu. It just delays it by almost a minute, which I took as the computer hanging...
