### ISSUE TITLE
arm64 or armhf images

### ISSUE THREAD

**Issue by vasekch** [ayufan-rock64/linux-build#133]
This is general question, what is the difference between arm64 and armhf [builds](https://github.com/ayufan-rock64/linux-build/releases) in terms of usage?
Which is better (more stable) e.g. for creating a desktop environment?
Thanks

**Comment by ayufan** [comment]
You should prefer to use arm64, but due to big RPI popularity and armhf some software might be only available for armhf. However, it is possible to extend arm64 with armhf userspace and have this binary compatibility.

**Comment by vasekch** [comment]
@ayufan Thanks for that, I have an issue on latest 0.6.25, tried xenial-minimal 
on _armhf_, I can do `apt update && apt upgrade` and `install_desktop.sh mate` everything is ok
on _arm64_ system is unbootable after `apt upgrade` or  `install_desktop.sh mate` without upgrade.

What is the best way to debug it (installing ~200 packages one by one with reboot in between seems unfeasible)?
