### ISSUE TITLE
Python 3.5 issues during apt-get update/upgrade

### ISSUE THREAD

**Issue by S3phi40T** [ayufan-rock64/linux-build#136]
As per my research, Python update fixes the problem:
`Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at                                                                                                                                                              0xf691d3d8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at                                                                                                                                                              0xf691d3d8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
`

**Comment by S3phi40T** [comment]
@xalius, this is not resolved.
@ayufan 
I'm on 0.6.29 Stretch OMV armhf upgraded from clean 0.6.28
Linux Kamyk 4.4.120-rockchip-ayufan-197 #1 SMP Thu Mar 29 22:00:14 UTC 2018 aarc
Issue exists since 0.6.25 - some bug with Python 3.5.

**Comment by ludenticus** [comment]
Why was this issue closed? It's not solved yet.

**Comment by immanuelfodor** [comment]
I get the same error on OMV4 after `omv-release-upgrade` from latest OMV3 on every `apt update` :( 

```python
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xb62ca390>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xb62ca390>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

```bash
# uname -a
Linux odroidxu4 4.9.61-odroidxu4 #2 SMP PREEMPT Wed Nov 22 16:34:23 CET 2017 armv7l GNU/Linux
```

OMV 4.1.7

**Comment by mrtestone** [comment]
same here... update throws the error... started btw. from a fresh OMV 4.0.

**Comment by OverByThere** [comment]
Same error here. Fresh install on VM of OMV 4.1.8.2-1 (Arrakis).

Full output below:
```
root@openmediavault:~# apt update ; apt upgrade
[...]
Ign:14 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch InRelease
Hit:15 https://downloads.plex.tv/repo/deb ./public InRelease
Ign:16 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-testing stretch InRelease
Ign:17 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-plex stretch InRelease
Ign:18 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-sync stretch InRelease
Hit:19 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch Release
Hit:21 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-testing stretch Release
Hit:22 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-plex stretch Release
Hit:23 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-sync stretch Release
Fetched 196 kB in 1s (105 kB/s)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xb7099d64>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xb7099d64>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@openmediavault:~#
```

**Comment by OverByThere** [comment]
This [seems to be fixable](https://forum.openmediavault.org/index.php/Thread/19658-Upgrade-Debian-9-and-4-x/?postID=164703#post164703).

In short open `/usr/lib/python3.5/weakref.py` and change line 109 to:
```
def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):
```

And line 117 to:
```
_atomic_removal(d, wr.key)
```

Note you need to do this with spaces, not tabs as this will cause other errors.

**Comment by immanuelfodor** [comment]
It worked like a charm, the error is now gone, thanks!

**Comment by Darcidride** [comment]
Thank you @OverByThere it worked ! :)

**Comment by cybercar** [comment]
Thanks, works perfect!

**Comment by cmcginty** [comment]
Has this bug been reported upstream to Debian? Maybe they backport the change to the next Python 3.5.3 release.

**Comment by ransur0t** [comment]
Thanks @OverByThere - this solved the issue on my OMV NAS.

**Comment by ayufan** [comment]
I think that desired fix is to push this upstream to debian and ubuntu.

**Comment by 001101** [comment]
Still present

**Comment by mf01** [comment]
I can approve. Issue still there.

**Comment by ghostry** [comment]
Thanks,  it good.

**Comment by R0Wi** [comment]
I'm on a fresh install OMV 4.1.3 and i was getting this error sometimes, too (when trying to apt-get update / upgrade). I was able to fix it by applying changes mentioned by @OverByThere , thx :-)

**Comment by OverByThere** [comment]
> I'm on a fresh install OMV 4.1.3 and i was getting this error sometimes, too (when trying to apt-get update / upgrade). I was able to fix it by applying changes mentioned by @OverByThere , thx :-)

I mean, I'm glad it works, but also concerned this hasn't been fixed in upstream, what's the best route to get this sorted?

**Comment by mrtestone** [comment]
> 
> I mean, I'm glad it still works, but also concerned this hasn't been fixed in upstream, what's the best route to get this sorted?
I believe, posting it either directly on OMV forums, so the main developers can see it, would be a good start. Otherwise I think Debian forums?

**Comment by stevefan1999-personal** [comment]
> 
> 
> This [seems to be fixable](https://forum.openmediavault.org/index.php/Thread/19658-Upgrade-Debian-9-and-4-x/?postID=164703#post164703).
> 
> In short open `/usr/lib/python3.5/weakref.py` and change line 109 to:
> 
> ```
> def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):
> ```
> 
> And line 117 to:
> 
> ```
> _atomic_removal(d, wr.key)
> ```
> 
> Note you need to do this with spaces, not tabs as this will cause other errors.

For people who are lazy and doesn't want to do it themselves:
```patch
--- /usr/lib/python3.5/weakref.py       2018-09-28 00:02:01.000000000 +0800
+++ weakref.py  2019-03-28 15:35:03.677097971 +0800
@@ -106,7 +106,7 @@
         self, *args = args
         if len(args) > 1:
             raise TypeError('expected at most 1 arguments, got %d' % len(args))
-        def remove(wr, selfref=ref(self)):
+        def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):
             self = selfref()
             if self is not None:
                 if self._iterating:
@@ -114,7 +114,7 @@
                 else:
                     # Atomic removal is necessary since this function
                     # can be called asynchronously by the GC
-                    _remove_dead_weakref(d, wr.key)
+                    _atomic_removal(d, wr.key)
         self._remove = remove
         # A list of keys to be removed
         self._pending_removals = []
```
Run `patch /usr/lib/python3.5/weakref.py weakref.patch`

**Comment by jodumont** [comment]
yes it is fixable simply by executing 

`wget -O /usr/lib/python3.5/weakref.py https://raw.githubusercontent.com/python/cpython/9cd7e17640a49635d1c1f8c2989578a8fc2c1de6/Lib/weakref.py`

thanks to [macom](https://forum.openmediavault.org/index.php/Thread/25520-Shut-Down-or-Restart-Hangs-after-updating-from-4-1-14-to-4-1-16-4-1-17/?postID=192428&highlight=weakref.py#post192428)

**Comment by alugowski** [comment]
Still a problem on a fresh install today.

It's worrisome that a problem that nearly everyone is hitting, and one that has a seemingly trivial fix, isn't getting fixed.

**Comment by kkkgo** [comment]
I can approve. Issue still there.

**Comment by alugowski** [comment]
Can anyone actually confirm that the problem exists in Debian? I've built many Debian and Ubuntu images in the past year that this bug has been occurring and never once seen this error.

**Comment by vomov** [comment]
> Can anyone actually confirm that the problem exists in Debian? I've built many Debian and Ubuntu images in the past year that this bug has been occurring and never once seen this error.

I can confirm: issue is still there, on a fresh (yesterday) install.

**Comment by frogale** [comment]
Also confirming.. latest OMV4..

**Comment by ayufan** [comment]
This is upstream debian problem :(

**Comment by francisek** [comment]
OMV users, when the `/var` is a mount point, ensure that the mount option `noexec` is not defined in `/etc/openmediavault.conf` and `/etc/fstab`.

**Comment by aarancon091372** [comment]
Thanks, works perfect!

**Comment by mylovesaber** [comment]
I did the same fix and got another problem:
Traceback (most recent call last):
  File "/usr/sbin/omv-mkaptidx", line 91, in <module>
    cache = apt.cache.Cache()
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 83, in __init__
    self._weakref = weakref.WeakValueDictionary()
  File "/usr/lib/python3.5/weakref.py", line 109, in __init__
    def remove(wr, selfref=ref(self), _atomic_removal=remove_dead_weakref):
NameError: name 'remove_dead_weakref' is not defined

**Comment by votdev** [comment]
This is a Debian upstream issue and must be fixed by the package maintainers.

**Comment by ayufan** [comment]
Unfortunately, yes @votdev. However, I added a quirk to fix that https://github.com/ayufan-rock64/linux-package/blob/master/root/usr/local/sbin/install_openmediavault.sh#L164 temporarily on all new installs.

**Comment by Darcidride** [comment]
> Run `patch /usr/lib/python3.5/weakref.py weakref.patch`
Thank you for the snippet, worked perfectly after patching

For information, it occurs in my side for `openmediavault` version `4.1.35-1` and `4.1.34-1`

My OS : Linux NAS01 4.19.0-0.bpo.2-amd64 #1 SMP Debian 4.19.16-1~bpo9+1 (2019-02-07) x86_64 GNU/Linux (Debian 9.8 up to date)

**Comment by thefunkygibbon** [comment]
so its been 2 years or so since this was flagged, do we have a fix for it yet? what is the work around?  i see there is a 'patch' comment but i assume thats relating to compiling. 
also the lines in the patch /usr/lib/python3.5/weakref.py weakref.patch file don't seem to be there in my 4.1.35-1

**Comment by ayufan** [comment]
It is on OMV4/5.
