### ISSUE TITLE
Error in -193 Bionic Gnome Package updater

### ISSUE THREAD

**Issue by Pytheas54** [ayufan-rock64/linux-build#137]
```
Spawn of helper '/usr/share/PackageKit/helpers/aptcc/get-distro-upgrade.py' 
failed: failed to spawn /usr/share/PackageKit/helpers/aptcc/get-distro-upgrade.py: 
Failed to execute child process “/usr/share/PackageKit/helpers/aptcc/get-distro-upgrade.py” 
(No such file or directory)
```

I've tried moving `get-distro-upgrade.py`  (got from somewhere in the Internet) into its proper folder to no avail...

**Comment by xalius** [comment]
This is probably a Bionic issue (which is still beta), so please report this bug upstream.

**Comment by venik212** [comment]
I have the same issue on a Yoga 2 Pro with Lubuntu 17.10.  As a result, I cannot upgrade my OS.

**Comment by srwood** [comment]
I have same issue on a Yoga 2 Pro with Ubuntu 18.04

**Comment by venik212** [comment]
After upgrading to 18.04 all is fine.

**Comment by SviatoslavBordovski** [comment]
reproduced on ubuntu 18.04.3
