### ISSUE TITLE
bionic Rockchip integrated ephy console spam 

### ISSUE THREAD

**Issue by LargePrime** [ayufan-rock64/linux-build#138]
Fresh boot from emmc, bionic-minimal-rock64-0.6.25-193-arm64

update and upgrade.  shutdown, power off, power on

cli gets spammed with 
Rockchip integrated EPHY stmmac-1:00: rockchip_integrated_phy_fixup_100M: reset phy 

approx every 17 seconds

perhaps related
https://github.com/ayufan-rock64/linux-build/issues/121

**Comment by xalius** [comment]
Latest pre-release (0.6.27) should fix this, eth1 is now disabled by default...
