### ISSUE TITLE
UARTs seem inoperable

### ISSUE THREAD

**Issue by estechnical** [ayufan-rock64/linux-build#141]
Hi,

Many thanks for great work on the RK3328/Rock64 :)

I'm trying to make use of some of the UARTs that are present in RK3328 and I'm having trouble.

```
rock64@rock64:~$ uname -a
Linux rock64 4.4.77-rockchip-ayufan-136 #1 SMP Thu Oct 12 09:14:48 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
rock64@rock64:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
I set up using the etcher tool to make the SD card.

I can see device nodes for five apparent serial devices, and the `FIQ0` which initially runs a console.

```
rock64@rock64:~$ ls /dev/tty* -la
...
crw-rw---- 1 root dialout 4, 64 Mar 24 15:32 /dev/ttyS0
crw-rw---- 1 root dialout 4, 65 Mar 24 15:32 /dev/ttyS1
crw-rw---- 1 root dialout 4, 66 Mar 24 15:32 /dev/ttyS2
crw-rw---- 1 root dialout 4, 67 Mar 24 15:32 /dev/ttyS3
crw-rw---- 1 root dialout 4, 68 Mar 24 15:32 /dev/ttyS4
...
crw-rw---- 1 rock64 rock64 254, 0 Mar 24 15:32 /dev/ttyFIQ0
```

While I have been able to send and receive data using `/dev/ttyFIQ0` it seems to be fixed at 1.5M baud but `stty` reports 115200 baud regardless of what I attempt to set.

```
root@rock64:/home/rock64# stty -a -F /dev/ttyFIQ0 
speed 115200 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop echoprt echoctl echoke -flusho -extproc
```

All the `ttyS*` devices give `input/output error` when trying to use `stty`:
```
root@rock64:/home/rock64# stty -a -F /dev/ttyS3
stty: /dev/ttyS3: Input/output error
```

I would really like to make use of at least one UART with the ability to set the baud rate. Searching through the schematics I have found UART1 and UART2 are accessible.

I there any plan to make these available to use?

Many thanks,
Ed

**Comment by estechnical** [comment]
Thanks for the info :) 

Is there a guide for this available anywhere, please?

Ed

**Comment by estechnical** [comment]
I have just been looking at `arch/arm64/boot/dts/rockchip/*` and see the serial/uarts mentioned.

I am trying to find where I "configure dtbs" - does this mean I need to compile both U Boot and the kernel?

Thank you! :)

**Comment by estechnical** [comment]
Now I have the tools working (I think correctly...) 

Please coud you clarify if this is correct?

Enable:
Kernel menuconfig:
```
-> Device Drivers
--> Device Tree and Open Firmware support
---> Device Tree overlays
```
Also, do I need to enable:
```
-> Boot options
--> Build a concatenated Image.gz.dtb by default
```
?

From `make u-boot-menuconfig`, I also assume that the options below (which appear to be already set) are needed, please can you confirm this is correct?
```
-> Device Tree Control
--> Run-time configuration via Device Tree
    Enable run-time configuration via Device Tree in SPL
    Enable run-time configuration via Device Tree in TPL
    Generate platform data for use in TPL
```
This is not enabled:
```
Generate platform data for use in SPL
```
... should it be?

Are these the correct settings?
```
    (rk3328-rock64) Default Device Tree for DT control
    (rk3328-rock64) List of device tree files to include for DT control 
```
It would be great to have a documented way of doing this right! I hope we can make this available here or incorporate into your docs.

**Comment by ayufan** [comment]
Well. No. This is https://github.com/ayufan-rock64/linux-kernel/blob/release-4.4/arch/arm64/boot/dts/rockchip/rk3328-rock64.dts#L46.

I will check if i can give you an overlay approach for this. This would be ideal.

**Comment by estechnical** [comment]
Thank you...

As you can probably guess, I'm trying to work this out and it has been years since I built any kernel.

**Comment by ayufan** [comment]
Well. Use this script: https://github.com/ayufan-rock64/linux-build/blob/master/package/root/usr/local/sbin/enable_dtoverlay.

Get the `target-path` from: https://github.com/ayufan-rock64/linux-kernel/blob/release-4.4/arch/arm64/boot/dts/rockchip/rk3328.dtsi

And use as:

```bash
enable_dtoverlay uart0 'serial@ff110000' enabled
disable_dtoverlay uart0
```

I don't guarantee that this will work, but this allows to dynamically change values.

**Comment by estechnical** [comment]
Thank you for the script and guidance. I can run the script and see output like:

```
rock64@rock64:~$ sudo enable_dtoverlay uart1 'serial@ff120000' okay
Applying...
/dts-v1/;
/ {
	fragment@0 {
		target-path = "/serial@ff120000";
		__overlay__ {
			status="okay";
		};
	};
};
Applied!
```

After running this for both uart1, I still can't seem to use the port, but setserial output looks better than before
```
rock64@rock64:~$ sudo setserial -a -G /dev/ttyS1
/dev/ttyS1 uart unknown port 0x0000 irq 191 baud_base 1500000 spd_normal
```

```
rock64@rock64:~$ sudo chown rock64:rock64 /dev/ttyS1
rock64@rock64:~$ echo "Testing testing" > /dev/ttyS1
-bash: echo: write error: Input/output error
```

**Comment by ayufan** [comment]
We definitely miss this patch:
https://github.com/rockchip-linux/kernel/pull/76/files.

**Comment by estechnical** [comment]
How do I get make to build again? It returns with "nothing to be done for..." when I want to build again after making changes.

For convenience, I'm building the xenial minimal image and loading with etcher - but I have not managed to rebuild with the changes I want, yet.

Thanks for your help :+1:

**Comment by ayufan** [comment]
remove the `*.deb` from local folder

**Comment by estechnical** [comment]
:D

Thank you for all the help, with the changes from the patch above applied to `kernel/arch/arm64/boot/dts/rockchip/rk3328-rock64.dts`

and the addition of 
```
&uart1 {
        status = "okay";
};
```
in `kernel/arch/arm64/boot/dts/rockchip/rk3328-rock64.dts`

I have succeeded in sending data from the UART (so far I have only confirmed TX causes something to happen at the pin with an oscilloscope) and I get no errors trying to do eg `cat /dev/ttyS1`

Very happy I can now use this UART.

**Comment by estechnical** [comment]
Opening the port causes a message to dmesg/console

```
rock64@rock64:~$ sudo cat /dev/ttyS1
[sudo] password for rock64: 
[   78.647057] of_dma_request_slave_channel: dma-names property of node '/serial@ff120000' missing or empty
```

**Comment by ayufan** [comment]
The patch will be added with 0.6.29

**Comment by jarednm** [comment]
Did the patch you referenced add uart1 functionality to /dev/ttyS1 by default, or do we still have to go through the overlay process?
