### ISSUE TITLE
xenial- 0.6.26-195-armhf endless reboot

### ISSUE THREAD

**Issue by ycllwl** [ayufan-rock64/linux-build#144]
xenial-minimal-rock64-0.6.26-195-armhf.img.xz
endless reboot！
Others are not tested

From China！ English is poor

**Comment by inos-github** [comment]
Same here.
stretch-minimal-rock64-0.6.26-195-arm64

**Comment by Pytheas54** [comment]
confirmed
stretch-minimal-rock64-0.6.26-195-arm64

**Comment by ayufan** [comment]
Yes, this is known. This should fix it: https://github.com/ayufan-rock64/linux-kernel/commit/27df1ab485b7a835fcf9e2ce797dd9da11ac829f
