### ISSUE TITLE
still failure to boot with bionic gnome install (0.6.28)

### ISSUE THREAD

**Issue by Pytheas54** [ayufan-rock64/linux-build#146]
After running `install_desktop_sh gnome` next reboot goes well until  (about) 'mounted Fuse control file system' then the screen page blinks 5 times and install stalls.
This was already the case for previous versions (0.6.25)
Installing lxde is OK, but installing Gnome over it (and selecting gmds) when prompted) leads to same problem

**Comment by ayufan** [comment]
Can you post full log?

**Comment by Pytheas54** [comment]
How can I get the log ? (sorry I'm a noob)

**Comment by ayufan** [comment]
Picture, UART, anything :)

**Comment by Pytheas54** [comment]
Could retrieve a syslog (see bottom part)
http://dl.free.fr/igqVS3zG7
Hope that helps

**Comment by ayufan** [comment]
Everything seems OK

**Comment by ayufan** [comment]
OK, gnome is crashing, because of OpenGL. Well, Gnome seems broken for now then :)

**Comment by Pytheas54** [comment]
Bionic gnome install failure with 0.6.29: same as with 0.6.28...

**Comment by ayufan** [comment]
well, it is not yet fixed.

**Comment by Pytheas54** [comment]
By the way, Gnome works fine from xenial-minimal 0.6.29 !

**Comment by Pytheas54** [comment]
Re Gnome from xenial-minimal 0.6.29
Running` apt-get upgrade gnome` leads to system crashing
see syslog here
http://dl.free.fr/gtYF8FezG

**Comment by Pytheas54** [comment]
Re Gnome from xenial-minimal 0.6.31
Running apt-get upgrade  leads to some kind of screen reboot and freeze. Pressing interrupt (thus rebooting) brings back normal operation...

**Comment by Pytheas54** [comment]
Now, got an UART to USB device
Here is the log for clean install of bionic-minimal-rock64-0.6.31-209-arm64.img.xz
with gnome desktop including reboot
http://dl.free.fr/qa1LsYWz5
As described above, on HDMI screen
"After running install_desktop_sh gnome next reboot goes well until (about) 'mounted Fuse control file system' then the screen page blinks 5 times and install stalls."

**Comment by ayufan** [comment]
This is solved: https://github.com/ayufan-rock64/linux-build/releases/tag/0.6.40
