### ISSUE TITLE
OneWire gpio support

### ISSUE THREAD

**Issue by GrilleGustav** [ayufan-rock64/linux-build#148]
Why the w1-gpio is not enabled in kernel ?
Please enable it.
When i want to compile the arm64 by my self it always fails with some errors.
I need the w1-gpio with ds2408 and temperature sensors.
Some error on compile is:

`Makefile:1051: recipe for target 'block' failed
make: *** [block] Error 2
make: *** Waiting for unfinished jobs....
  CC [M]  fs/cifs/file.o
  CC      kernel/auditsc.o
  CC [M]  fs/cifs/inode.o
  CC      fs/btrfs/free-space-cache.o
  CC      kernel/audit_watch.o
fs/cifs/inode.c: In function 'cifs_revalidate_dentry_attr':
fs/cifs/inode.c:1934:5: internal compiler error: Segmentation fault
 int cifs_revalidate_dentry_attr(struct dentry *dentry)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
scripts/Makefile.build:324: recipe for target 'fs/cifs/inode.o' failed
make[2]: *** [fs/cifs/inode.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  CC      kernel/audit_fsnotify.o
*** Error in `/usr/lib/gcc/aarch64-linux-gnu/6/cc1': free(): invalid pointer: 0x0000007fa0d77e80 ***
fs/btrfs/free-space-cache.c: In function 'btrfs_set_inode_generation':
fs/btrfs/free-space-cache.c:3714:1: internal compiler error: Aborted
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
scripts/Makefile.build:324: recipe for target 'fs/btrfs/free-space-cache.o' failed
make[2]: *** [fs/btrfs/free-space-cache.o] Error 1
scripts/Makefile.build:583: recipe for target 'fs/btrfs' failed
make[1]: *** [fs/btrfs] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      kernel/audit_tree.o
scripts/Makefile.build:583: recipe for target 'fs/cifs' failed
make[1]: *** [fs/cifs] Error 2
Makefile:1051: recipe for target 'fs' failed
make: *** [fs] Error 2
  CC      kernel/hung_task.o
  CC      kernel/seccomp.o
  CC      kernel/relay.o
  CC      kernel/utsname_sysctl.o
  CC      kernel/delayacct.o
  CC      kernel/taskstats.o
  CC      kernel/tsacct.o
  CC      kernel/tracepoint.o
  CC      kernel/elfcore.o
  CC      kernel/irq_work.o
  CC      kernel/cpu_pm.o
  CC      kernel/padata.o
  CC      kernel/memremap.o
  CHK     kernel/config_data.h
  UPD     kernel/config_data.h
  CC      kernel/configs.o
^Cscripts/Makefile.build:324: recipe for target 'kernel/audit_tree.o' failed
make[1]: *** [kernel/audit_tree.o] Interrupt
scripts/Makefile.build:324: recipe for target 'kernel/audit_watch.o' failed
make[1]: *** [kernel/audit_watch.o] Interrupt
scripts/Makefile.build:324: recipe for target 'kernel/audit_fsnotify.o' failed
make[1]: *** [kernel/audit_fsnotify.o] Interrupt
Makefile:1051: recipe for target 'kernel' failed
make: *** [kernel] Interrupt
`
thanks for help
And sorry for my bad Englisch

Fabian

**Comment by GrilleGustav** [comment]
Hi, i have compiled the kernel with Dallas OneWire support without errors, how does the implementaion of w1-gpio works now ?


If you build a PC and praise it in with both pins of the Rasberry Pi then they have to support everything the Rpi can do.

**Comment by ayufan** [comment]
According to: https://github.com/ayufan-rock64/linux-kernel/blob/release-4.4/Documentation/devicetree/bindings/w1/w1-gpio.txt#L18, you have to add the `w1-gpio` to dts and select the right GPIO that you gonna use.

**Comment by ayufan** [comment]
This should be fixed.

**Comment by GrilleGustav** [comment]
this must be a standard of you linux images

**Comment by GrilleGustav** [comment]
and your help doesn't work

**Comment by ayufan** [comment]
Well. I cannot test that, documentation clearly states how to use gpios for emulating this protocol. I believe that this is already quite well documented.
