### ISSUE TITLE
Fix for Netatalk's CNID database path issues

### ISSUE THREAD

**Issue by ThomasKaiser** [ayufan-rock64/linux-build#15]
https://forum.openmediavault.org/index.php/Thread/17598-AFP-on-OMV3-crashing-all-system/?postID=150080#post150080

Proposed action: Wait until fixed upstream, then remove workarounds. I'll ping you when something happens.

**Comment by ThomasKaiser** [comment]
Will be added so time to remove workarounds on our side since `/var/lib/netatalk/CNID/` will be handled with next update of the flashmemory plugin :)

**Comment by ayufan** [comment]
Yay!

**Comment by ThomasKaiser** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/commit/a2e86978f31c41e80a4e41d545ef7d5824c18153 :)
