### ISSUE TITLE
Include module for playstation eye webcam

### ISSUE THREAD

**Issue by fczuardi** [ayufan-rock64/linux-build#153]
Pluging a PS3 webcam on the latest bionic image wont mount it on /dev/video and it looks like the missing module is ``gspca_ov534``

A more detailed report can be found at https://forum.pine64.org/showthread.php?tid=5909

**Comment by xalius** [comment]
I'll add CONFIG_USB_GSPCA_OV534 and some others to my next PR...

**Comment by ayufan** [comment]
This is fixed. Will be in next pre-release (0.6.31).
