### ISSUE TITLE
Root serial login does not work on rock64 images

### ISSUE THREAD

**Issue by pfeerick** [ayufan-rock64/linux-build#16]
Started digging into this issue further, and finally found some logs that start explaining _why_ TTY root login hasn't been working on the OMV images (and then checked a Xenial Image and it actually suffers from the same problem, just hadn't seen it before as I was used to the root account being locked by default) by running ```sudo tailf /var/log/auth.log``` and trying another root login...

```
Jul 28 11:14:05 rock64 login[16389]: pam_securetty(login:auth): access denied: tty '/dev/ttyFIQ0' is not secure !
Jul 28 11:14:08 rock64 login[16389]: FAILED LOGIN (1) on '/dev/ttyFIQ0' FOR 'root', Authentication failure
```

One 'solution' to this is to append something like
```
#rock64 serial console
ttyFIQ0
```

to ```/etc/securetty```, but I was wondering if there is a better option. Since it looks to be a overall rock64 issue, it looks like it should go in https://github.com/ayufan-rock64/linux-build/blob/master/rootfs/make_rootfs.sh?

**Comment by ayufan** [comment]
Can you check what is permission of `/dev/ttyFIQ0`?

**Comment by pfeerick** [comment]
Hm... interesting... on Xenial it was rock64 because I was logged in as the rock64 user. 

```
crw--w---- 1 root   tty       4,  9 Feb 11  2016 /dev/tty9
crw------- 1 rock64 tty     254,  0 Jul 28 12:40 /dev/ttyFIQ0
crw-rw---- 1 root   dialout   4, 64 Feb 11  2016 /dev/ttyS0
```

When logged in as root on OMV (now that I corrected the /etc/securetty setting, it was root when logged in as root.
```
crw------- 1 root tty     254,  0 Jan  1 00:00 /dev/ttyFIQ0
crw-rw---- 1 root dialout   4, 64 Jan  1 00:00 /dev/ttyS0
```

If I log in as the 'pfeerick' user, it the owner becomes pfeerick

```
crw--w---- 1 root     tty       4,  9 Jan  1 00:00 /dev/tty9
crw------- 1 pfeerick tty     254,  0 Jan  1 00:01 /dev/ttyFIQ0
crw-rw---- 1 root     dialout   4, 64 Jan  1 00:00 /dev/ttyS0
```

It isn't a permission issue. it is because the entry for ttyFIQ0 is missing from /etc/securetty is misisng, so when [pam_securetty](https://linux.die.net/man/8/pam_securetty) checks /etc/securetty to see if the root user (and only the root user) is permitted to log in via that serial terminal, and doesn't find the entry, it fails.
