### ISSUE TITLE
Add FAQ Section

### ISSUE THREAD

**Issue by cricket007** [ayufan-rock64/linux-build#168]
Got a new Rock64, and all the lights come on and seem to blink occasionally, but there's no display. I'm fairly sure my power supply is okay - I've tried two different ones, but I got a Picocluster box, and the board was from the official site. 

I'm booting from the SD card, and tried several images from the 6.x branch as well as the latest 5.x release. Ideally, I would like to use the containers build. I was going to wait for your 6.x stable builds, but I am under the impression things should be working anyway. 

Searching over the forums, I see various solutions like waiting for awhile or not having any peripherals/ethernet attached.

Since this seems to be a common problem, so it would be nice to see an FAQ section with a way to debug the problem. Especially for those of us who just expect it to run after flashing an image using Etcher or Pine Installer. I also tried flashing on Mac and Windows, and booting 3 different SD cards... I'm at a loss.

If this post should be moved to the forums, place let me know

**Comment by hyptechdev2015** [comment]
hi,
what version of image did you use? please try the release version first. I am sure It will work.
[https://github.com/ayufan-rock64/linux-build/releases/tag/0.5.15](url)

**Comment by cricket007** [comment]
Hello @hyptechdev2015 , 

I'm fairly sure I tried both 

- xenial-mate-rock64-0.5.15-136-arm64.img.xz
- xenial-minimal-rock64-0.5.15-136-arm64.img.xz

I've tried so many images, and at one point there was a black screen, but no noticeable prompt, but otherwise, I have "no signal" on my display. Also, forgot to mention, my router isn't seeing any entries either for the board.

**Comment by hyptechdev2015** [comment]
@cricket007 , you might get a defected board? so many factors, hard to tell :(

**Comment by cricket007** [comment]
Hello @tpoechtrager

Would the flasher tools work without doing that? I did get ISOs from both Keka on my Mac and 7zip on Windows. 

The cards are all the same. Some variant of SanDisk 16GB UHC-1, I believe.

https://www.picocluster.com/collections/pico-3/products/pico-3-application-cluster-sets

And I even think they were pre-flashed with an image by Picocluster (would need to mount on a Linux box to verify that), but not even that image boots. I tried 2 out of the 3 I got. 

I bought the Pico 3 from the above site with the switch in the box, and the power supply works to power both the one Rock64 I bought, as well as the switch, so I doubt it's a power supply issue. To be sure, I also tried the USB wall charger for my phone, which says 5V on it. Same problem there. My monitor works fine when attached to my Pi3, so the cable isn't the issue.

**Comment by tpoechtrager** [comment]
> Would the flasher tools work without doing that? I did get ISOs from both Keka on my Mac and 7zip on Windows.

Not sure. Try decompressing the image by using the xz command line utility before flashing. `xz -d <img>.xz`

> The cards are all the same. Some variant of SanDisk 16GB UHC-1, I believe.

My board doesn't like SanDisk microSD cards for some reason (tried an _Extreme 32 GB UHS-3_). A _Samsung EVO Plus Micro SDHC 32GB_ works absolutely flawlessly. However, I cannot guarantee it will fix the problem for you.

**Comment by cricket007** [comment]
@tpoechtrager

Out of all the microSDs I own, all I can find are SanDisk :)

I extracted as you said, then used `dd bs=1M if=<img>.img of=/dev/sdb` for flashing the card. Still no luck.

Funny thing is that the 6.33 xenial minimal image gives me a black screen with a signal, but the 5.15 stretch minimal image gives no signal. Still neither image makes the board appear on my router despite the flashing lights on the NIC

**Comment by pfeerick** [comment]
If you use Etcher, there is no need to unpack the xz images, it will do that itself, as well as verify the write. I can confirm the flaky behaviour of SanDisk cards on at lease the pine64 boards, not sure about the rock64. But if you have images that are making the lights on the NIC blink, it sounds like it is actually booting. Have you tried to SSH into the system once it has booted? It should be enabled by default, and login details are on the release notes (rock64/rock64). I can't say I've tried HDMI of late, my stuff is headless with SSH or HTTP login...

**Comment by pfeerick** [comment]
Well, that's no fun! :( If it doesn't appear in your router logs, then it may still be misbehaving (i.e. devices on network, IPs in use, etc), then there may be something else going on. OOTB those images should be connecting via ethernet and claiming an IP via DHCP. After the first boot, the MAC address for the device should be constant also, so you can do a set a static DHCP address via your router if you choose.... but obviously, you need to get there first. :) If you've tried a 0.6.x mate image also, all I can suggest is get yourself a USB to serial adapter (or a Serial console cable) so you can plug into the devices UART/serial pins, and find out what is hanging it up. I would also usually suggest getting a Samsung EVO card, but I would have thought picocluster would be supplying a card they know to be compatible (and it is supposed to be pre-imaged btw).

**Comment by sskinnider** [comment]
I have five now.  Here is what I have found.  
The Jessie-rock64-0.5.15-136-arm64.img.xz seems rock solid and works consistently across all five boards all the time.
The Stretch, Xenial and Artful versions of the same build are not consistently stable.  One of the board crashes on everything except the Jessie 5.15 build.  I have loaded the Jessie and Stretch builds for 6.x and just about all the rock64 boards I have are unstable. On all five boards I am using eMMC.
I used win32disdkimager to burn the image.  Initially I tried Etcher on windows but had problems.

**Comment by cricket007** [comment]
> get yourself a USB to serial adapter (3.3 / 3v3 compaitable) (or a Serial console cable) so you can plug into the devices UART/serial pins, and find out what is hanging it up

Is there some documentation I can follow on getting that setup? I have some familiarity with using Putty over a serial connection, but I would be working with a Mac now. 

> The Jessie-rock64-0.5.15-136-arm64.img.xz seems rock solid

I'll try again 🤞 

> I am using eMMC

Might have to give in to buying those after I can figure out the issue using a serial connection 

> I used win32disdkimager to burn the image

I've tried that as well 😞

**Comment by sskinnider** [comment]
USB UART setup tutorial -
https://forum.pine64.org/showthread.php?tid=5029

I also had problems with stability when USB devices were plugged in, especially a wireless keyboard mouse dongle and USB storage devices.

**Comment by cricket007** [comment]
Jessie image also is a no-go for me. 

So, will this work? - https://www.amazon.com/Adapter-Serial-Converter-Development-Projects/dp/B075N82CDL

**Comment by pfeerick** [comment]
@cricket007 Yeah, that should work just fine... there is a switch on it to change between 5v and 3.3v on the output drive and supports in excess of the 1.5Mb  baud rate you need for the rock64, ~~so you'll just need some female to female dupont style breadboard leads to connect it to the rock64~~- scratch that, it looks like it comes with them. For reference, this may works also, but technically it shouldn't as the CP2102 is only supposed to go up to 921600 baud, and you need 1,500,000... https://www.amazon.com/ADAFRUIT-INDUSTRIES-954-SERIAL-RASPBERRY/dp/B00DJUHGHI/ref=sr_1_8?s=electronics&ie=UTF8&qid=1526619432&sr=1-8&keywords=serial+console

**Comment by cricket007** [comment]
Got two more boards to complete my Pico3 cluster, then trying the 2/3 cards I already flashed, those wouldn't bring up a display either. 

So, I tried the third card, and the display came up very briefly with "Rock64 icon", then to a "Erasing" screen, however, it seems the power drops out after that, and the display goes completely green while the white light on the board goes out 😞 

The first board I tried does the same thing. At least I now can rule out the first board was a dud.

**Comment by cricket007** [comment]
Booting with UART, just seems to be stuck 

```
DDR version 1.06 20170424
In
LPDDR3
786MHz
Bus Width=32 Col=11 Bank=8 Row=15/15 CS=2 Die Bus-Width=32 Size=4096MB
ddrconfig:7
OUT
Boot1 Release Time: 2017-05-18, version: 2.43
ChipType = 0x11, 127
emmc reinit
emmc reinit
SdmmcInit=2 20
SdmmcInit=0 0
BootCapSize=0
UserCapSize=15193MB
FwPartOffset=2000 , 0
StorageInit ok = 61909
Raw SecureMode = 0
SecureInit read PBA: 0x4
SecureInit read PBA: 0x404
SecureInit read PBA: 0x804
SecureInit read PBA: 0xc04
SecureInit read PBA: 0x1004
SecureInit ret = 0, SecureMode = 0
LoadTrustBL
No find bl30.bin
No find bl32.bin
Load uboot, ReadLba = 2000
Load OK, addr=0x200000, size=0x92d74
RunBL31 0x10000
NOTICE:  BL31: v1.3(debug):f947c7e
NOTICE:  BL31: Built : 09:28:45, May 31 2017
NOTICE:  BL31:Rockchip release version: v1.3
INFO:    ARM GICv2 driver initialized
INFO:    Using opteed sec cpu_context!
INFO:    boot cpu mask: 1
INFO:    plat_rockchip_pmu_init: pd status 0xe
INFO:    BL31: Initializing runtime services
WARNING: No OPTEE provided by BL2 boot loader, Booting device without OPTEE initialization. SMC`s destined for OPTEE will return SMC_UNK
ERROR:   Error initializing runtime service opteed_fast
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x200000
INFO:    SPSR = 0x3c9


U-Boot 2017.09-g5aef9f7 (Oct 12 2017 - 09:11:39 +0000), Build: jenkins-linux-build-rock-64-136

Model: Pine64 Rock64
DRAM:  4 GiB
MMC:   rksdmmc@ff500000: 1, rksdmmc@ff520000: 0
*** Warning - bad CRC, using default environment

In:    serial@ff130000
Out:   serial@ff130000
Err:   serial@ff130000
Model: Pine64 Rock64
Net:   eth0: ethernet@ff540000
Hit any key to stop autoboot:  0
Card did not respond to voltage select!
mmc_init: -95, time 9
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:6...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
reading /extlinux/extlinux.conf
259 bytes read in 4 ms (62.5 KiB/s)
1:      kernel-4.4
Retrieving file: /initrd.img
reading /initrd.img
2176178 bytes read in 99 ms (21 MiB/s)
Retrieving file: /Image
reading /Image
18606088 bytes read in 815 ms (21.8 MiB/s)
append: earlycon=uart8250,mmio32,0xff130000 rw root=LABEL=linux-root rootwait rootfstype=ext4 init=/sbin/init coherent_pool=1M ethaddr=46:1a:02:c4:bd:37 eth1addr=46:1a:02:c4:bd:57 serial=be9cc7df4f71f0a
Retrieving file: /dtb
reading /dtb
42707 bytes read in 5 ms (8.1 MiB/s)
## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
   Loading Ramdisk to fcd07000, end fcf1a4b2 ... OK
   Loading Device Tree to 00000000fccf9000, end 00000000fcd066d2 ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 4.4.77-rockchip-ayufan-136 (root@713b8312374e) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) ) #1 SMP Thu Oct 12 09:14:48 UTC 2017
[    0.000000] Boot CPU: AArch64 Processor [410fd034]
[    0.000000] earlycon: Early serial console at MMIO32 0xff130000 (options '')
[    0.000000] bootconsole [uart0] enabled```

**Comment by cricket007** [comment]
Turns out it was a power supply problem all along. I am able to use a USB port on the back of my desktop to get it booting. However, now I almost consistently get these `spinlock lockup` errors on both the bionic-containers and stretch-minimal... Seems to happen primarily when doing an I/O work like `apt-get update` + `upgrade` or `docker pull`

```
[   64.955556] BUG: spinlock lockup suspected on CPU#0, store/1056
[   64.956205]  lock: 0xffffffc0fef31c00, .magic: dead4ead, .owner: <none>/-1, .owner_cpu: -1
[   64.957073] CPU: 0 PID: 1056 Comm: store Not tainted 4.4.126-rockchip-ayufan-227 #1
```

Also during boot, I see a few of these. 

```
[    8.578448] mmcblk1: error -84 transferring data, sector 624696, nr 256, cmd response 0x900, card status 0xb00
[    8.601665] mmc_host mmc1: Bus speed (slot 0) = 400000Hz (slot req 400000Hz, actual 400000HZ div = 0)
[    8.668108] mmc_host mmc1: Bus speed (slot 0) = 50000000Hz (slot req 50000000Hz, actual 50000000HZ div = 0)
[    8.676110] mmc1: tried to reset card
```

**Comment by sebt3** [comment]
your micro-sdcard seem at a fault here, try an other one

**Comment by cricket007** [comment]
Going to open other issues with specific errors.
