### ISSUE TITLE
missing netplan config (eth0 cant connect on bionic)

### ISSUE THREAD

**Issue by fczuardi** [ayufan-rock64/linux-build#169]
I have just flashed a rock64 with the [bionic minimal 0.6.33](https://github.com/ayufan-rock64/linux-build/releases/download/0.6.33/bionic-minimal-rock64-0.6.33-211-arm64.img.xz) and after booting there is no network on eth0. Pinging 8.8.8.8 will error with ``Network is unreachable``

Then I went to check the file at ``/etc/network/interfaces`` and the contents were:
```
# ifupdown has been replaced by netplan(5) on this system.  See
# /etc/netplan for current configuration.
# To re-enable ifupdown on this system, you can run:
#    sudo apt install ifupdown
```

And then I looked into the ``/etc/netplan`` and it was empty.

So, apparently Ubuntu is migrating to this https://netplan.io/ thing, and indeed, creating a ``/etc/netplan/config.yaml`` file with the contents of that website brought the network up on the next reboot:

```
network:
  version: 2
  renderer: NetworkManager
```

**Comment by Pytheas54** [comment]
Thanks to the pointer to netplan.io
I was stuck on that, and gave up...

**Comment by ayufan** [comment]
I will re-enable ifupdown.

**Comment by shortyishere** [comment]
I kind of like the netplan idea as you can pick systemd or networkmanager pretty easily. Going forward I wonder if it is better to supplpy a netplan config.yaml for systemd for headless and networkmanager for desktop being ubuntu is using this going forward?

**Comment by ayufan** [comment]
netplan is natively supported now
