### ISSUE TITLE
Additional packages

### ISSUE THREAD

**Issue by ThomasKaiser** [ayufan-rock64/linux-build#17]
I propose adding the following packages to default list: `usbutils sysstat fping iozone3 iperf3`

     root@rock64:~# for i in usbutils sysstat fping iozone3 iperf3 ; do
     > echo -e "$i: $(apt-cache show $i | awk -F" " '/Installed-Size/ {print $2}')"
     > done
     usbutils: 673
     sysstat: 1170
     fping: 120
     iozone3: 650
     iperf3: 58

We still need to do a lot of diagnostics so adding these helpers to default installation might help also encouraging other users contributing.

**Comment by ayufan** [comment]
Closed by https://github.com/ayufan-rock64/linux-build/commit/06ec9b856fc9539456396dcd4b96eaaf4a1df3fd
