### ISSUE TITLE
Is Android actually operating at the selected screen resolution?

### ISSUE THREAD

**Issue by tpoechtrager** [ayufan-rock64/linux-build#171]
A lot of applications claim the screen resolution is 1280x720 instead of 1920x1080. It seems like 1280x720 is somewhere hardcoded. Is the UI actually running at the selected screen resolution or is it always 1280x720 up/down scaled? YouTube seems to top out at 1280x720 as well when I take a look at "nerd statistics".

What's going on?

**Comment by ayufan** [comment]
This is wrong repo. Please open it in correct one https://github.com/ayufan-rock64.

The Pine Inc Android renders GUI in 1280x720. My Android renders GUI in 1920x1080.
