### ISSUE TITLE
filesystem, external usb hard drive freeze...

### ISSUE THREAD

**Issue by hyptechdev2015** [ayufan-rock64/linux-build#177]
First of all,  I am very new to linux system, please help me to understands the issue I am about to describe:

Current testing system on Rock64 with lastest: stretch-openmediavault-rock64-0.6.34-213-armhf.img.xz

I installed Airsonic.war music application (running on tomcat8) to scan over 150 GB of music files on the external drive, the scan seems working fine, then at about 39 GB, the usb hard drive is **FREEZE...not accessible** anymore, so as other drives on the filesystem in OMV 4. However, other services seem to run fine like I still able to brow OMV web interface.

is it because of the limit in USB pool? can someone show me other log files' location, so I can share here?

Here is the message.log in /var/log/
[https://paste.ee/p/LUOGs](https://paste.ee/p/LUOGs
)

PS (updated): I have been reading about USB3 on rock64 and other SCB, it seems  the is problem is UAS  on USB3 issues; connecting to multiple drives. I am going to disable UAS and see if it's help. more info here: [https://forum.pine64.org/showthread.php?tid=5137&page=2](https://forum.pine64.org/showthread.php?tid=5137&page=2)

**Comment by hyptechdev2015** [comment]
I went through the process, and disable UAS. It seems to make OMV stable and running without crash or freeze on the usb hard drives.

**Comment by ayufan** [comment]
This is solved: https://github.com/ayufan-rock64/linux-build/releases/tag/0.6.40
