### ISSUE TITLE
openmediavault - no network interface, no console login

### ISSUE THREAD

**Issue by mentaluproar** [ayufan-rock64/linux-build#179]
I can get as far as a console login prompt on SD and eMMC, both 32 and 64 bit images, but no farther.  It doesn't matter if I use the built-in ethernet port or either of my 2 USB network adaptors, I get an error saying "No network interface(s) available" at the login screen.  If I try to log in, it briefly flashes "No directory, logging in with HOME=/
This account is currently not avaliable."

I can boot, but that's it.  I'm using the latest prerelease, 0.6.34-213.

**Comment by ayufan** [comment]
This is solved: https://github.com/ayufan-rock64/linux-build/releases/tag/0.6.40

**Comment by benhur85** [comment]
This issue is again seen with latest labels of [0.7.9] armhf and aarc64 , I have tried even the development versions.

**Comment by benhur85** [comment]
Sorry to not mention earlier. Issue is seen with rockpro64.

**Comment by Amolith** [comment]
I'm experiencing this as well. I have 0.8.3 for arm64, the build linked in [Pine64's wiki](https://wiki.pine64.org/index.php/ROCKPro64_Software_Release#Stretch_64bit_.28aarch64.29_.5BmicroSD_.2F_eMMC_Boot.5D_.5B0.8.3.5D).
