### ISSUE TITLE
cannot boot issue

### ISSUE THREAD

**Issue by rock64-linux** [ayufan-rock64/linux-build#18]
I am having boot issue 50% or more times when tested 0.4.12 version on 2G and 1G.

Then, I tested xenial-minimal-rock64 0.4.0, 0.4.6, 0.4.3, 0.4.4, 0.4.5 versions, looks like the problem started on 0.4.6, although, somehow, it happened 1 out of 10 boot on 0.4.4.  All the (0.4.0, 0.4.3, 0.4.5) boot just fine for 10 times. I started seeing problems on 0.4.6, it happened 7 out of 10 boot. It also happen on the latest 0.4.15.

It just hang half way during boot and showing black screen on TV. Attached [cannot_boot.zip](https://github.com/ayufan-rock64/linux-build/files/1186767/cannot_boot.zip) contains all the debug log. Note that, I didn't test all for 10 boot, except those I mentioned above, so most of them have only few log files.

**Comment by ayufan** [comment]
Can you test https://github.com/ayufan-rock64/linux-build/releases/tag/0.4.15? It contains some very important fixes that may have fixed that already :)

**Comment by rock64-linux** [comment]
Yes, I did tested on 0.4.15 xenial-i3 and xenial-minimal, the boot problem still happen. Their log files are in the attached also.

**Comment by ayufan** [comment]
is it SD or eMMC boot?

**Comment by ayufan** [comment]
I'm pushing 0.4.16 that reverts some kernel changes.

**Comment by rock64-linux** [comment]
eMMC boot.

**Comment by ayufan** [comment]
Does 0.4.16 fix the problem?

**Comment by rock64-linux** [comment]
Tested all below for 10 boot each:
jessie-minimal-rock64-0.4.16-83-arm64.img

**Comment by ayufan** [comment]
yes, but does it work? :)

**Comment by rock64-linux** [comment]
Sorry, just completed the previous comment, accidentally submitted. I think it should be fixed, except for the 3 cannot boot which maybe you can have a look at it. Thanks.

**Comment by rock64-linux** [comment]
Are you going to release 0.4.16? or do you have critical changes on newer version?

**Comment by ayufan** [comment]
To make it release not pre-release?

Kamil

**Comment by rock64-linux** [comment]
Yes.

**Comment by ayufan** [comment]
I will make it probably tomorrow.

**Comment by ayufan** [comment]
Made 0.4.16 a release. Now pushing 0.4.17 with a few fixes from @tkaiser.

**Comment by rock64-linux** [comment]
Closing this. Thanks.
