### ISSUE TITLE
Soft reboot problem

### ISSUE THREAD

**Issue by ulysse132** [ayufan-rock64/linux-build#181]
Hello,

Using the last stable release, I am unable to reboot using `sudo reboot`. I don't want to wait for the next stable version, I just want this one to work well as long as this one fit me.
I've seen [here](https://github.com/ayufan-rock64/linux-build/issues/101) and [there](https://github.com/ayufan-rock64/linux-build/issues/127) that it might be a problem of bootloader.

I want to know if the new version of u-boot fix my problem and if so, how to install it. 
Please, use step by step instruction and give links because I'm a noob...

Thanks a lot for your help !

**Comment by phinxy** [comment]
Have you tried "sudo reboot now"?

**Comment by ulysse132** [comment]
My problem is not that `sudo reboot` doesn't work, but doing so, I have the same problem as the problem described on [that page](https://github.com/ayufan-rock64/linux-build/issues/127).

On that thread, it is said that @ayufan will write later how to upgrade bootloader. I don't see where. When I try to download the latest u-boot, [here](https://github.com/ayufan-rock64/linux-u-boot/releases), I only get un archive file that I can't flash to sd card.

How should I do that ?

**Comment by ulysse132** [comment]
I found how to flash it : just download u-boot-flash-spi-rock64.img.xz on that page and it worked for me. 
@ayufan : the file given in 0.6.35 release didn't worked for me, I had to flash the file given in 0.6.34.

**Comment by pfeerick** [comment]
@ulysse132 I tried the 0.6.35 erase and flash SPI images [last night just after the build was released](https://pastebin.com/CWcKCirp), and they did work... they just don't flash the LED at the end, so there seems to be some form of regression there... I can also confirm that on at least my 1G v1.1 rock64 that I was unable to reboot (`sudo reboot`) on `xenial-minimal-rock64-0.6.35-217-arm64.img.xz` it just sat there after shutting down the system. Plus there are [some other issues still present](https://pastebin.com/0zpfbW3b)...
