### ISSUE TITLE
Crash during boot with 0.6.37

### ISSUE THREAD

**Issue by ErikDeridder** [ayufan-rock64/linux-build#185]
I tried the new 0.6.37-221 bionic images bu theyall crash after booting with " Fixing recursive fault but reboot is needed!" and then halts

**Comment by btbxbob** [comment]
the same here. 0.6.37 bionic cannot boot with full screen of backtrace.

**Comment by Pytheas54** [comment]
For the record
Upgrading from bionic lxde 0.6.35 to 0.6.36 to 0.6.37 went OK

**Comment by ayufan** [comment]
Strange. I tested and it seems to work OK.

**Comment by ayufan** [comment]
This is solved in: https://github.com/ayufan-rock64/linux-build/releases/tag/0.6.40
