### ISSUE TITLE
did not boot. screen shows ffffff800......errors/states

### ISSUE THREAD

**Issue by core66** [ayufan-rock64/linux-build#188]
kernel problem?

**Comment by core66** [comment]
ok sorry, i was hoping you know the problem :-)

when iam flash my sd card for example with the image "stretch-openmediavault-rock64-0.6.41-227-arm64.img.xz" the boot sequence looks like this:
![img_20180522_160428_resized_20180522_040540106](https://user-images.githubusercontent.com/37327446/40367707-536fd5f4-5dda-11e8-92eb-571404cb0ff1.jpg)

**Comment by core66** [comment]
anyone can help?

**Comment by hyptechdev2015** [comment]
@core66 , I flashed version 226, it seems to work for me.

**Comment by core66** [comment]
tried both...not working.

iam new to rock64 board....have i to erase and flash the spi with the given images?

**Comment by btbxbob** [comment]
![img_20180523_213213](https://user-images.githubusercontent.com/2234266/40427726-1aa9c2fa-5ed1-11e8-878a-9b5e01a71c59.jpg)
random halt, too

**Comment by ulysse132** [comment]
I have the same kind of problem trying to boot from ssd. Even using the u-boot given with the latest stable version.

**Comment by penndennis** [comment]
I have the same problem. I'm booting from sd card and using the serial output

**Comment by ayufan** [comment]
Anyone. I need boot log from uart. I also need the board model that you
have and model of memory chip that your board uses.

**Comment by ayufan** [comment]
Uart

**Comment by ulysse132** [comment]
**ayufan** said :

> Uart

I don't understand how to get the required log but if anyone understand what to do, I let him explain or give the result

**Comment by penndennis** [comment]
@ayufan : Let me know if you require anymore or my submissions are insufficient.
Kind Regards,
Penndennis.

**Comment by penndennis** [comment]
@ayufan The Memory Chip - Very faded but
A logo in the shape of an 'S'
Number in the corner 8NP0 (last char could be Q)
Number - PB039-107-BT
-------------------------------------------------------
The Board
E320008
94v-0
DT-4
1734
ROCK64_V2.0
2017-0713
That's all I could find. Let me know if you need more.
Kind Regards,
Penndennis.

**Comment by ulysse132** [comment]
**Pytheas54** said :

> I have no problem with bionic-minimal-rock64-0.6.41-227-arm64.img.xz 
> eth0 works fine too

I tried flashing this release on ssd and it worked just fine. I just had to install MATE to have a desktop working.

**Comment by Pytheas54** [comment]
I confirm that MATE works fine.
But installing GNOME still fails, as I mentioned long ago in an issue that was deleted without solving recently...

**Comment by hyptechdev2015** [comment]
Hi @ayufan  @core66 

I was able to replicate @btbxbob screenshot error, maybe @ayufan  can answer how and look into the issue....

It looked like the issue is in  **u-boot-flash-spi-rock64.img (for example lastest img with md5: AFBB8EF35736C96D36FC5CFE626C8B08)**, when I flashed this, I got the same error as @@btbxbob's screenshot.

However I erased and flash with **u-boot-flash-spi-rock64.img (md5: 136748285FB22F286DB398907C4A9D28)** I was able to boot without any issue. This **u-boot-flash-spi-rock64.img** was created with pre-release version 0.6.34, which I download on April 13th.

**Comment by ayufan** [comment]
Everyone, please test the latest 0.6.44. It seems to be working OK for some.

**Comment by hyptechdev2015** [comment]
hi @ayufan 

I just correct the **md5**, please review

**Comment by penndennis** [comment]
@ayufan Thank you so much. Works a treat.

**Comment by ulysse132** [comment]
@penndennis You only flashed U-Boot and it worked ? 
Write now, I boot on sd and the system work on ssd but I'm not very well with this. I'm worried about the reliability of my sd. But right now, the system is ready and I don't want to reinstall the entire system.

**Comment by penndennis** [comment]
@ulysse132 I installed the latest 0.6.44 on an ssd and I was able to boot Bionic. Until then every version since and including the 0.6.41: jenkins-linux-build-rock-64-227 has failed. For now I'm staying with the previous stable release, I think it's 136

**Comment by ayufan** [comment]
This seems solved.

**Comment by penndennis** [comment]
Solved but not stable.

**Comment by ayufan** [comment]
@penndennis Why you think that?
