### ISSUE TITLE
eth0 doesn't come up after latest release

### ISSUE THREAD

**Issue by moderation** [ayufan-rock64/linux-build#189]
In the latest [release](https://github.com/ayufan-rock64/linux-build/releases/tag/0.6.41) the netplan [commit](https://github.com/ayufan-rock64/linux-build/commit/9515624dbd6edb42175827668309a4d2c2382e29) results in my Rock64 booting but `eth0` does not come up. I had previously used [this](https://github.com/ayufan-rock64/linux-build/issues/169#issue-318754229) modification to get `eth0` to come up.

I presume I need to remove the `config.yaml` for this to work? I've tried that but I still can't get the interface to come up.

**Comment by ayufan** [comment]
What is `config.yaml`?

**Comment by moderation** [comment]
I updated my comment with the link, however prior to this release, the addition of `config.yaml` as described in this issue was required for `eth0` to come up - https://github.com/ayufan-rock64/linux-build/issues/169#issue-318754229

**Comment by ayufan** [comment]
Well, right now it is colliding. `netplan` is being used properly, just handling eth0.

**Comment by moderation** [comment]
I've removed the old config and used the new default. I cannot get my Rock64 online. The DHCP settings are not working. I've tried setting static IP and gateways and nameservers. Can't get anything to work. Do I need to `sudo systemctl stop NetworkManager.service` for this to work?

Dead in the water right now.

**Comment by BaronKrause** [comment]
Same here after updating from 0.6.37 to 0.6.40. Few people on the rock64 forums are reporting it too with this build.

**Comment by hyptechdev2015** [comment]
I am confirmed that stretch-openmediavault-rock64-0.6.41-227-armhf.img.xz has issue with eth0

**Comment by pfeerick** [comment]
@BaronKrause Try the 0.6.41 release, as I had the same issue with 0.6.40, and it's gone for me in 0.6.41 (and for @moderation from the comment on the forum.

**Comment by pfeerick** [comment]
@hyptechdev2015 Did you mean 0.6.40 there? build 226 = 0.6.40, build 227 is 0.6.41 ;) Glad it sounds like it's fixed for you also though.

**Comment by BaronKrause** [comment]
@pfeerick Thanks, just updated and all is well. Dont know if it was related, or just a heavy load on the server, but the download took around 45min to finish with the network connection on the 6.40 build when just the previous night the download to that build took 15 seconds.

**Comment by pfeerick** [comment]
@BaronKrause Great! yeah, github releases seem inconsistent sometimes... sometimes they are really fast, sometimes they are really slow. Bit odd when you consider it's powered by AWS, but hey, can't complain when they're hosting the files for free!

**Comment by neolah** [comment]
so it still can't connect at the moment, I flashed bionic-lxde-rock64-0.6.41-227-arm64 image but the connection is not stable, losing 50% packet. I used it as headless server. No ethernet connection, no SSH as well, any idea? waiting for another stable release?? thanks guys for the effort

**Comment by jonasfoe** [comment]
Turns out I was probably experiencing Issue #190 all along.

**Comment by ayufan** [comment]
This seems to be solved.
