### ISSUE TITLE
Recent images will crash on boot 

### ISSUE THREAD

**Issue by whirm** [ayufan-rock64/linux-build#190]
I've been unable to boot my Rock64 4GB boards with recent images:

[bionic-containers-rock64-0.6.40-226-arm64.boot.log](https://github.com/ayufan-rock64/linux-build/files/2038622/bionic-containers-rock64-0.6.40-226-arm64.boot.log)
[bionic-containers-rock64-0.6.41-227-arm64.boot.log](https://github.com/ayufan-rock64/linux-build/files/2038623/bionic-containers-rock64-0.6.41-227-arm64.boot.log)

Artful minimal seems to work:
[artful-minimal-rock64-0.5.15-136-arm64.before_upgrade.boot.log](https://github.com/ayufan-rock64/linux-build/files/2038624/artful-minimal-rock64-0.5.15-136-arm64.before_upgrade.boot.log)

But if I upgrade with the following commands:
```
      mkdir /run/resolvconf
      echo nameserver 1.1.1.1 > /run/resolvconf/resolv.conf
      apt update
      apt update -y
      sudo apt-get install linux-rock64 -y
      sudo apt install linux-firmware-image-4.4.126-rockchip-ayufan-227
      rock64_upgrade_bootloader.sh
      rock64_write_spi_flash.sh
```

It will fail to boot with the following output:

[artful-minimal-rock64-0.5.15-136-arm64.after_upgrade.boot.log](https://github.com/ayufan-rock64/linux-build/files/2038626/artful-minimal-rock64-0.5.15-136-arm64.after_upgrade.boot.log)

I tried clearing the SPI from the bootable image and I'm able to boot again. But some files have been corrupted (python, linux-firmware, libc-bin) I'll attempt to fix that and post back the results. 

I'll attach a picture of the RAM chip shortly. Let me know if I can provide any more info or help with anything to debug this, I've got two  identical boards, UART cable and good linux knowledge.

**Comment by ErikDeridder** [comment]
I have the same board with 4GB. None of the recent images are working. I had to use an older 0.5 image thats "working" with crashes but at least that one is somewhat stable

**Comment by whirm** [comment]
I've been running memtest a few times and docker containers on the whole day and there's zero issues.

I'm running the following versions:

```
ii  linux-firmware-image-4.4.77-rockchip-ayufan-136 0.5.15                            arm64        Linux kernel firmware, version 4.4.77-rockchip-ayufan-136                                                                                  
ii  linux-headers-4.4.77-rockchip-ayufan-136        0.5.15                            arm64        Linux kernel headers for 4.4.77-rockchip-ayufan-136 on arm64                                                                               
ii  linux-image-4.4.77-rockchip-ayufan-136          0.5.15                            arm64        Linux kernel, version 4.4.77-rockchip-ayufan-136                                                                                           
ii  linux-rock64                                    0.5.15                            arm64        Rock64 Linux virtual package: depends on kernel and compatibility package                                                                  
ii  linux-rock64-package                            0.5.15                            all          Rock64 Linux support package                                                                                                               
ii  u-boot-rock64                                   0.6.41                            all          Rock64 U-boot package     
```

**Comment by pfeerick** [comment]
Did you have the same problems with earlier 0.6.x images? I only started having problems after 0.6.27, and for my boards at least, the issue went away again in 0.6.41. Maybe try 0.6.25 or 0.6.27 (I was using xenial-containers) and then we might be able to pin it down to something else that changed in the rockchip kernel when it was updated around then.

**Comment by whirm** [comment]
@pfeerick I just got started using those boards, I'll give a shot at 0.6.27 tonight and report back. 0.6.41 is broken for my boards.

**Comment by ayufan** [comment]
Everyone: I need help, please test each of these releases: 0.5.15, 0.6.21, 0.6.25, 0.6.34, 0.6.41 and tell me which are stable. This will allow pinpointing when the problem started happening.

**Comment by Pytheas54** [comment]
bionic-minimal 0.6.41 (+mate) is OK with me. Upgrading it to 7.0.4 under mate went OK too.  
Following tkaiser's advice
I use a 32Go Sandisk Ultra Plus C10 A1 burned with latest Etcher, and the Pine 2.5 A power supply.
bionic-minimal 0.6.41 using a 32Go Sandisk Ultra C10 A1 works as well

**Comment by pfeerick** [comment]
I'll go back and download each of those in the minimal flavor and try. Do you just want a boot test, or is it more a test of if the ability to upgrade? I have had the occasional crash on boot, but it's usually just the first boot, and the kernel automatically triggers a reboot.

If it's boot test, I do have some logs already here from a few images from 0.6.25 onwards: https://pastebin.com/u/pfeerick/1/kuiy6Mtf

This line from the log above is interesting though... I had that _quite_ a few times since 0.6.27, but I still haven't confirmed if it was media or image specific, as it _could_ have been the Samsung EVO+ (note the plus) 16GB microSD that the rock64 didn't like as well. 

```[2018-05-25 10:19:29] [    5.193748] vendor storage:20160801 ret = -1```

**Comment by ayufan** [comment]
So. I started trying out different things. And it turned out that as suspected, and already reported by others it seems to be some misconfiguration of RAM:

```
$ memtester 3G
Loop 1:
  Stuck Address       : ok
  Random Value        : ok
  Compare XOR         : ok
  Compare SUB         : ok
  Compare MUL         : ok
  Compare DIV         : ok
  Compare OR          : ok
  Compare AND         : ok
  Sequential Increment: ok
  Solid Bits          : ok
  Block Sequential    : testing 176                                                                      ok
  Checkerboard        : ok
  Bit Spread          : testing   1FAILURE: 0x0000400a != 0x0000000a at offset 0x1cea2820.
  Bit Flip            : testing  24FAILURE: 0x00000008 != 0x0000ff08 at offset 0x084ca488.
FAILURE: 0x00000008 != 0x0000ff08 at offset 0x0a497c68.
FAILURE: 0x00000008 != 0x0000ff08 at offset 0x4b478648.
  Walking Ones        : ok
  Walking Zeroes      : ok
  8-bit Writes        : ok
  16-bit Writes       : ok
```

We need to find:
1. Whether this error happens on 0.5.15,
2. Whether this error happens on 0.6.41/0.7.4,
3. Whether this error happens on any of the versions between to pinpoint when it started.

**Comment by whirm** [comment]
All the previous tests were made on a clean `artful-minimal-rock64-0.5.15-136-arm64.img`. I also installed the corresponding firmware packages but I doubt that makes any difference.

**Comment by whirm** [comment]
` linux-image-4.4.126-rockchip-ayufan-235_0.7.5_arm64.deb` is also crashing.

**Comment by ayufan** [comment]
This is strange:

```
FAILURE: 0x6bcf457fff7fb869 != 0xffffffe76c7fdfef at offset 0x0004a828.
FAILURE: 0xffffffe76cffdfef != 0x6bcf457fffffb879 at offset 0x0004a830.
FAILURE: 0x6bcf457fff7fb879 != 0xffffffe76c7fdfff at offset 0x0004a838.
FAILURE: 0xffffffe76cffdfff != 0x6bcf457fffffb869 at offset 0x0004a840.
```

**Comment by ayufan** [comment]
I found out this pattern:
1. I use `MEMTESTER_TEST_MASK=6144 memtester 3G` to test verify the stability of DRAM (you can also run full `memtester 3G`),
1. Anyone noticing that some versions work, some do not, it is circumstantial, it purely depends where in mem / or timing data are loaded, it is likely that even if it seems stable, you are affected by this, 
1. If I fresh boot on `0.5.15`, everything seems to work fine,
1. If I boot the `0.6.41` I see failures:
```
Loop 1:
  Stuck Address       : ok         
  Bit Spread          : testing   1FAILURE: 0x0000ff0a != 0x0000000a at offset 0x00f5bf70.
  Bit Flip            : testing  26FAILURE: 0x00000008 != 0x0000ff08 at offset 0x56dd6418.
```
1. If I force the `flash-kernel --force 4.4.77-rockchip-ayufan-136`, and reboot, I still the above failures,
1. In order to get rid of them. I have to power-off to boot the `0.5.15`,

Can anyone check that?
1. Flash `0.5.15`,
2. Install the latest kernel: `wget https://github.com/ayufan-rock64/linux-build/releases/download/0.6.41/linux-image-4.4.126-rockchip-ayufan-227_0.6.41_arm64.deb && dpkg -i linux-image-4.4.126-rockchip-ayufan-227_0.6.41_arm64.deb`,
3. Try `memtester...`, try changing kernel versions with `flash-kernel` (will use latest), `flash-kernel --force 4.4.77-rockchip-ayufan-136` (will use this particular one).

**Comment by ayufan** [comment]
Tried, it seems that `0.6.42` is also affected.

**Comment by whirm** [comment]
Let me know if I can test anything else.

**Comment by pfeerick** [comment]
I've gone through the following images, and each one has failed the memory test within 2 minutes. 

Process: Write clean image to Samsung EVO 16GB. Serial console is connected but only GND and RX to prevent reverse power feed. EMMC and SPI clocks are both GND'd so disabled. Boot each image, log in via SSH, and run a script which basically installs and runs memtester, grabs some other info and then uploads the log to ix.io. 

Is it worth going back to earlier images or trying the armhf ones instead? As a side note, I noticed after running memtester repeatedly on my desktop with the same mask and 3G test that it also failed at one point... so memtester _could_ be temperamental also at times...

i.e. Run `curl -s https://raw.githubusercontent.com/pfeerick/rock64-scripts/master/testing/mem-diagnostics.sh | sudo bash` on each image and check back after 2 minutes to see if it has fallen over.

fail - artful-minimal-rock64-0.5.15-136-arm64.img - https://pastebin.com/qakDuGsT

fail - xenial-minimal-rock64-0.5.15-136-arm64.img - http://ix.io/1bBk 
serial console: https://pastebin.com/s6uXUb45

fail - bionic-minimal-rock64-0.6.41-227-arm64.img - http://ix.io/1bBq 
serial console: https://pastebin.com/U0gjj7QM

fail - bionic-minimal-rock64-0.6.44-239-arm64.img - http://ix.io/1bBt 
serial console: https://pastebin.com/Vbvb6FGR

fail - bionic-minimal-rock64-0.7.4-234-arm64.img  - http://ix.io/1bBw 
serial console: https://pastebin.com/FdCeC91W

**Comment by ayufan** [comment]
@pfeerick Memtester is broken if you use incorrect mask. Please check with mask `6144`, as in others i might generate false positive :(

**Comment by pfeerick** [comment]
@ayufan Ah... god dang it... I did 6114 instead of 6144... I retract my earlier logs... :sigh: At least that may hopefully explain why 0.5.15 didn't like me... rinse and repeat...

**Comment by whirm** [comment]
> Try 0.6.44

Working great! Thanks!
