### ISSUE TITLE
0.7.3 Can't restart successful 

### ISSUE THREAD

**Issue by 3000gto** [ayufan-rock64/linux-build#192]
Then I  used "restart, init 6 or  shutdown -r now".It respond  below and freeze.
U-Boot 2017.09-g03a332b (May 25 2018 - 17:04:30 +0000), Build: jenkins-linux-build-rock-64-232

Model: Pine64 RockPro64
DRAM:  3.9 GiB

**Comment by pfeerick** [comment]
This build doesn't exist anymore, close the issue?

**Comment by ayufan** [comment]
The problem I think still exists.
