### ISSUE TITLE
0.6.44 - Local USB keyboard usage results in rockchip-sip messages

### ISSUE THREAD

**Issue by jl-678** [ayufan-rock64/linux-build#196]
Hi,

I was running 0.6.41 and just upgraded to 0.6.44 using Stretch Minimal.  In .41, my USB keyboard worked perfectly, and I used it to initiate the upgrade without a problem.  Now, that I am running 0.6.44, I see the following message every time I press a key on the USB keyboard as picture [here](https://imgur.com/a/Bv83k72). (Notice how the text appears after I type a letter.  You can see it with the "r" and then the "o."  It does this for every key including shift where it repeats rapidly if I hold shift down.)

rockchip-sip: function[82000008]: args:[2,0,2] => res:[0,2ed96880,0,0]

This is repeated no matter what key I press.  My keypresses are interpretted correctly; however, it is virtually impossible to use the keyboard in this situation.  I have no issues with SSH.

Here is some additional dmesg content and note the SIP messages that match the one listed above.

[  230.564388] usb 3-1: new low-speed USB device number 2 using ohci-platform
[  230.753450] usb 3-1: New USB device found, idVendor=04f2, idProduct=0833
[  230.754506] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  230.755622] usb 3-1: Product: USB Keyboard
[  230.756241] usb 3-1: Manufacturer: CHICONY
[  230.770351] input: CHICONY USB Keyboard as /devices/platform/ff5d0000.usb/usb3/3-1/3-1:1.0/0003:04F2:0833.0003/input/input3
[  230.826027] hid-generic 0003:04F2:0833.0003: input,hidraw0: USB HID v1.11 Keyboard [CHICONY USB Keyboard] on usb-ff5d0000.usb-1/input0
[  230.843429] input: CHICONY USB Keyboard as /devices/platform/ff5d0000.usb/usb3/3-1/3-1:1.1/0003:04F2:0833.0004/input/input4
[  230.898658] hid-generic 0003:04F2:0833.0004: input,hiddev0,hidraw1: USB HID v1.11 Device [CHICONY USB Keyboard] on usb-ff5d0000.usb-1/input1
[  236.814581] rockchip-sip: function[82000008]: args:[2,0,2] => res:[0,2ed96880,0,0]
[  236.862555] rockchip-sip: function[82000008]: args:[2,0,2] => res:[0,2ed96880,0,0]
[  259.457757] usb 3-1: USB disconnect, device number 2

**Comment by jl-678** [comment]
Adding full dmesg to help with troubleshooting.....

[ayufan.txt](https://github.com/ayufan-rock64/linux-build/files/2055576/ayufan.txt)

**Comment by jl-678** [comment]
Update: I [posted]([https://forum.pine64.org/showthread.php?tid=6121]) about this issue on the forum, and someone pointed at the commit linked below,  Is that causing this?

https://github.com/ayufan-rock64/linux-kernel/commit/551b0cbf6ebc1cdc11615a804c7ffdc2dd3dff1d

**Comment by pfeerick** [comment]
I believe the issue resolved for now and can be closed... https://forum.pine64.org/showthread.php?tid=6121&pid=38179#pid38179

**Comment by Kunibert-007** [comment]
Hi,
have the same problem with my Rock64. Under the Preview-Images I can't see a new image, only for the Rockpro64. Can you give me a hint what to do to solve the problem?

**Comment by jl-678** [comment]
This issue has been resolved, and I will close the case.  Please see the thread linked below for the solution.

[https://forum.pine64.org/showthread.php?tid=6121&pid=38179#pid38179](https://forum.pine64.org/showthread.php?tid=6121&pid=38179#pid38179)

**Comment by jmarkow** [comment]
Sorry to comment on a closed issue, but I'm seeing the same behavior on the Stretch Minimal 0.6.44 image for the Rock64 at the password prompt for logging in.  As far as I can tell this is preventing me from entering the correct password to actually log into the device.  

What should I do to get around this to apply the fix cited in the thread?
