### ISSUE TITLE
rockpro64 6.47-244-arm64 boot log

### ISSUE THREAD

**Issue by deeproot2k** [ayufan-rock64/linux-build#205]
Newest build is not booting rockpro64:

[bionic-minimal-rockpro64_244output.txt](https://github.com/ayufan-rock64/linux-build/files/2065312/bionic-minimal-rockpro64_244output.txt)

Just attaching my output log in case it helps any.

**Comment by ayufan** [comment]
But. This output is from 0.6.46.

**Comment by deeproot2k** [comment]
[bionic-minimal-rockpro64.txt](https://github.com/ayufan-rock64/linux-build/files/2065334/bionic-minimal-rockpro64.txt)

**Comment by deeproot2k** [comment]
0.6.49: jenkins-linux-build-rock-64-247
bionic minimal fully booted. Thanks
