### ISSUE TITLE
rockpro64-0.6.51 crashes

### ISSUE THREAD

**Issue by evilbunny2008** [ayufan-rock64/linux-build#207]
[0.6.51-log.txt](https://github.com/ayufan-rock64/linux-build/files/2067906/0.6.51-log.txt)

**Comment by bingmann** [comment]
And that one works for me (though not every time).

**Comment by bullet64** [comment]
Sometimes it crashes when you boot, sometimes not. When it runs it's very stable for me.

**Comment by evilbunny2008** [comment]
Seems to be fixed in 0.6.53
