### ISSUE TITLE
NanoPC-T4 Debian Image

### ISSUE THREAD

**Issue by hanshaze** [ayufan-rock64/linux-build#210]
Hello.......i bought a NanoPC-T4, but somehow i just dont get it to run Linux on it......
i flashed a few versions, but anytime i switch power on it just happens nothing, no tv output, no nothing.....i do see the NanoPC IP in my router menu but cannot connect in any way.........but the lan leds look like theyre working........maybe you can give me a tip which image i need to fire this thing up!

best regards

**Comment by ayufan** [comment]
Sorry, I don't have `NanoPC-T4`, nor I know what it is, nor I do plan to support it.

**Comment by pfeerick** [comment]
@hanshaze It might help if you are on the right site ;)

'NanoPC-T4' is a friendlyarm product, so you need to check out what they have to say about it. 

http://wiki.friendlyarm.com/wiki/index.php/NanoPC-T4

@ayufan  It might be worth keeping an eye on that NanoPC-T4 - it is RK3399 based, and is very similar to the ROCKPro64 feature-wise. If they make any code available there might be stuff that can be borrowed ;)
