### ISSUE TITLE
0.6.x stretch builds fail to boot on rock64 SD

### ISSUE THREAD

**Issue by biskyt** [ayufan-rock64/linux-build#215]
Hi,

I got a new Rock64 he other week, I want to use it for Open Media Vault. I can successfully get 0.5.15 to run, but have had no success with 0.6.44 or 0.6.51 (those are the only 0.6.x builds I've tried). I have tried both the armhf and arm64 buillds

Also same issue with the stretch-minimal-x.x.xx-rock64-arm64 images.

I have, however, been able to run the bionic-lxde-rock64-0.6.44-239-arm64 image without issue. This leads me to believe it is an issue with the stretch builds?

**To reproduce**
1. Download an affected build (e.g., stretch-openmediavault-rock64-0.6.44-239-armhf.img.xz)
2. Open etcher
  2.1 Select image
  2.2 Select SD card
  2.3 Flash and wait to verify
3 Insert newly flashed SD card into Rock64
4 Power On

**Expected**
- Power leds light up
- Machine boots
- Console outputs text over HDMI and eventually settles at login prompt
- Machine is accessible over network (e.,g. SSH, HTTP, shown in network scans, etc)

**Current behavior**
- Power leds light up
- No signal on HDMI
- Machine is not visible on network
- (i.e, same behaviour as if no SD card was inserted)

I have tried a selection of SD cards. I have tried with HDMI plugged in and not plugged in, and ethernet connected / not connected

Any ideas?

If there is more information that you need, please let me know, although without any access to a console, I'm not sure what else I can tell you!

Further info: I have also tried upgrading from 0.5.15. Whilst on stable channel, apt-get dist-upgrade runs fine and machine is still bootable. However, when I changed `/etc/apt/sources.list.d/ayufan-rock64.list` to pre-release and tried `dist-upgrade` again, I then got the above described behaviour (i.e, a brick)

on 0.5.15, my DVB-T usb adaptor (Geniatech T230) was unable to scan channels (with tvheadend or w_scan), which was one of the reasons I want to try a later build, to see if that fixes it. On the bionic build it is scanning fine though (as it dos on my rPi. If I manage to get the strecth builds working, and DVB is still having issues, then I'll raise that as a new issue.

Thanks for your help

PS> I have a Rock64 2GB board, with no eMMC. Using etcher 1.4.4 on Windows 10 to write the image.

**Comment by biskyt** [comment]
Some additional info. I also just tried the rock64Pro builds, just in case. Unsurprisingly, that didn't work. There was one difference though.

On the Rock64 builds, the ethernet link light does come on, and even flashes a few times. On the Rock64Pro builds, the link light stays off though. So that would insinuate something is happening with the Rock64 builds, but it is failing before the graphics card is initialised.

**Comment by ayufan** [comment]
Rockpro64 is for different board.

**Comment by biskyt** [comment]
Hi @ayufan - Thanks for the reply. Yes, I knew it was for a different board. I thought I'd just check though in case he Rock64 and Rock64Pro builds had become switched around and that was why the Rock64 images would not boot.

Any idea why the Rock64 stretch images are failing to boot (on the Rock64 board of course)

**Comment by jerryfudd** [comment]
Hi,

Just had the same thing - thought I'd give the 'omv-release-upgrade' a go as I was already prepared for the worst.... which unsurprisingly happened.

Thought since I was starting over I'd give the 'stretch-openmediavault-rock64-0.6.44-239-arm64.img.xz' a go and just as described on this thread nothing happened, well no HDMI output or network activity at all.

Reverted back to 'jessie-openmediavault-rock64-0.5.15-136-arm64.img.xz' which I was using before and no problems.

**Comment by biskyt** [comment]
I have also just tried 0.6.53 stretch minimal rock64, and still no joy. No ethernet light, no HDMI signal.

**Comment by biskyt** [comment]
Could this be related to #213 ?

**Comment by matsbengtsson** [comment]
Hi. I also got a new Rock64 board recently. I first tried bionic-containers and that worked brilliantly as far as I can tell. But when i tried stretch-openmediavault there is a crash regardless if I try to run arm64 or armhf. Here's a small part of the console log.

Begin: Loading essential drivers ... [    3.042986] md: linear personality registered for level -1
[    3.056265] md: multipath personality registered for level -4
[    3.069222] md: raid0 personality registered for level 0
[    3.077863] md: raid1 personality registered for level 1
[    3.086003] async_tx: api initialized (async)
[    3.094881] md: raid6 personality registered for level 6
[    3.098421] md: raid5 personality registered for level 5
[    3.101830] md: raid4 personality registered for level 4
[    3.115709] md: raid10 personality registered for level 10
done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... Scanning for Btrfs filesystems
[    3.217295] BUG: spinlock bad magic on CPU#1, btrfs/217
[    3.226181]  lock: 0xffffffc0ebf74b28, .magic: deadffad, .owner: <none>/-1, .owner_cpu: -1
[    3.235674] CPU: 1 PID: 217 Comm: btrfs Not tainted 4.4.132-rockchip-ayufan-271 #1
[    3.245267] Hardware name: Pine64 Rock64 (DT)
[    3.254646] Call trace:
[    3.263739] [<ffffff80080888d8>] dump_backtrace+0x0/0x220
[    3.273226] [<ffffff8008088b1c>] show_stack+0x24/0x30
[    3.282681] [<ffffff800855cd2c>] dump_stack+0x98/0xc0
[    3.292003] [<ffffff80081042ac>] spin_dump+0x84/0xa4
[    3.301305] [<ffffff80081042fc>] spin_bug+0x30/0x3c
[    3.310576] [<ffffff80081043ac>] do_raw_spin_lock+0x40/0x164
[    3.320046] [<ffffff8008c0d7f8>] _raw_spin_lock+0x20/0x2c
[    3.329543] [<ffffff800822346c>] fsnotify_find_inode_mark+0x2c/0x58
[    3.339234] [<ffffff80082249cc>] dnotify_flush+0x48/0x10c
[    3.348720] [<ffffff80081e2594>] filp_close+0x7c/0x9c
[    3.358200] [<ffffff8008200400>] __close_fd+0xb8/0xd8
[    3.367691] [<ffffff80081e25dc>] SyS_close+0x28/0x5c
[    3.377162] [<ffffff8008082f30>] el0_svc_naked+0x24/0x28
[    3.629831] BUG: Bad page map in process btrfs  pte:200000f464ffd3 pmd:e33be003

**Comment by biskyt** [comment]
Closing, as this is now very old. I moved to using DietPi
