### ISSUE TITLE
Missing PHY driver for USB3 in mainline

### ISSUE THREAD

**Issue by bullet64** [ayufan-rock64/linux-build#223]
@ayufan Is it possible that this is missing?

https://github.com/rockchip-linux/kernel/issues/83

my usb3 SSD isn't detected.

`rock64@rockpro64:/media$ uname -a
Linux rockpro64 4.17.0-rc6-1019-ayufan-gfafc3e1c913f `

**Comment by bullet64** [comment]
I found an old 3,5 Zoll HDD with external power supply.  ;)

`rock64@rockpro64:/mnt$ lsusb
Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 002: ID 152d:2336 JMicron Technology Corp. / JMicron USA Technology Corp. Hard Disk Drive
`

**Comment by bullet64** [comment]
Keyboard is working well on usb3 port.

`rock64@rockpro64:/$ lsusb
Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 003: ID 046d:c31c Logitech, Inc. Keyboard K120
`

**Comment by ayufan** [comment]
I will check that later.

**Comment by ShapeShifter499** [comment]
Any updates with this?

**Comment by bullet64** [comment]
Ayufan has fixed it in last kernel '4.17.0-rc6-1021-ayufan' Thank you!
