### ISSUE TITLE
Wiki to understand the partitions in the rock64 imgs

### ISSUE THREAD

**Issue by jonnyfoxy** [ayufan-rock64/linux-build#229]
Hi, 

Does anyone have a guide to better understand what each partition, in the Pine/Rock 64 img, does. For instance, after flashing my sd card with the [bionic-minimal-rock64-0.6.44-239-arm64.img.xz](https://github.com/ayufan-rock64/linux-build/releases/download/0.6.44/bionic-minimal-rock64-0.6.44-239-arm64.img.xz) I noticed 7 partitions have been created. only 3 of them are self explanatory (the boot, the home and the free space partitios). what about the other 4 partitions? what are they for?

Thanks

**Comment by pfeerick** [comment]
The partitions from start to finish (on a currently running rock64 /w 32gb eMMC) are:

```
Number  Start (sector)    End (sector)  Size       Code  Name
   1              64            8063   3.9 MiB     8300  loader1
   2            8064            8191   64.0 KiB    8300  reserved1
   3            8192           16383   4.0 MiB     8300  reserved2
   4           16384           24575   4.0 MiB     8300  loader2
   5           24576           32767   4.0 MiB     8300  atf
   6           32768          262143   112.0 MiB   0700  boot
   7          262144        61071326   29.0 GiB    8300  root
```

Partitions 1 - 5 are essentially system-use-only, and are needed for the rock64 boot process. Partitions 6 & 7 being the familiar /boot and / (root) partitions.

**Comment by Xake** [comment]
http://opensource.rock-chips.com/wiki_Partitions

**Comment by jonnyfoxy** [comment]
Thank you very much for your answers, this clarifies a lot.
