### ISSUE TITLE
How to enable spidev0,0 on rock64?

### ISSUE THREAD

**Issue by kappuchino** [ayufan-rock64/linux-build#237]
As discussed on IRC in #Rock64, how can a user **enable /dev/spidev0,0** - for example by "using overlayfs interface of configfs" (as @ayufan suggested - but honestly have no clue how to ...)? 

I would appreciate a "put this into this file" or "run this command" pointer. Or an article I have not found(yet) - see the ones that _didn't_ help (me) below. 

Current os (uname -a) is Linux rock64 _4.4.126-rockchip-ayufan-239 aarch64_ GNU/Linux

Question aims at making python demo code of Waveshare ePaper (like https://www.waveshare.com/wiki/E-Paper_Driver_HAT) work with Rock64. Already took different python lib (with RPi.GPIO-PineA64) into account as well as different Pinout.

Current Error is: 
  File "/root/code-red/python/epdif.py", line 43, in <module>
    SPI = spidev.SpiDev(0, 0)
FileNotFoundError: [Errno 2] No such file or directory

should go away with spidev0,0 present in /dev 
(yes, might be other problems, one step at a time ...)

I think it might be just a command similar to 
"enable_dtoverlay i2c0 i2c@ff150000 okay" or "enable_dtoverlay i2c0 i2c@ff150000 okay" but I have not figured out what the magic words are. 

For reference:
Similar unanswered Questions are:
https://forum.armbian.com/topic/5951-activate-spidev-on-the-rock64/
https://forum.pine64.org/showthread.php?tid=5409

Not understood to the point that I can act on it:
https://github.com/ayufan-rock64/linux-build/blob/master/recipes/additional-devices.md#use-additional-devices

Similar Questions with an answer that does not work (anymore) or are beyond my skills are:
https://forum.pine64.org/showthread.php?tid=5682 (didn't work)
https://forum.pine64.org/showthread.php?tid=4869 (modprobe did not do the trick for me)
https://forum.pine64.org/showthread.php?tid=5473  (no clue if its related)
https://forum.pine64.org/showthread.php?tid=1297&page=5 (other distro, right?)

Thank you for any help in advance.

**Comment by kappuchino** [comment]
Wrap-Up: In the only reply within a month to this problem it has been suggested [to change the distro](https://stackoverflow.com/questions/51321788/how-can-i-enable-dev-spidev0-0-on-a-rock64-system). That, of course, creates other problems and itself isn't helping with a solution. For now, am I wrong to consider spidev and using 08/15 displays on rock64 non-functional? I'm sorry that we can't provide a secure display for our journalists to verify against, but it seems it is beyond reach.

**Comment by tikonen** [comment]
At least it looks like that in the RockPro64 RK3399 the spi0 device and Ethernet are sharing the pin gpio3-A7 so only one of them can be enabled at a time.  (Pin can be either configured to SPI0_CSN0 chip select or  GMAC MAC_R XD1)

Tested this with instructions here http://synfare.com/599N105E/hwdocs/pine64/spidev.html
/dev/spidev appears but error I see in dmesg is 
`rockchip-pinctrl pinctrl: pin gpio3-7 already requested by ff1c0000.spi; cannot claim for fe300000.ethernet`
