### ISSUE TITLE
Suspect some missing kernel code while docker swarm is not working properly

### ISSUE THREAD

**Issue by giminni** [ayufan-rock64/linux-build#238]
Hi am not shure, but can someone proof if docker swarm 18.03 can run under
>.4.126-rockchip-ayufan-239 \#1 SMP Sun May 27 18:38:24 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

I use a Rock64 SBC and cannot call the nginx external published port running a service in endpoint-mode=vip

**Comment by ayufan** [comment]
It is likely that we might miss some kernel modules, but this should be easy to fix.

**Comment by ayufan** [comment]
I'm sure that this is covered in mainline.

**Comment by giminni** [comment]
Which mainline kernel should I use for stability?

**Comment by ayufan** [comment]
mine 4.18.0-rc3 is fine

**Comment by giminni** [comment]
@ayufan can you include as a kernel module also the other ip_vs_xxx balancers and TCP and UDP in your next kernel 4.4 run?

**Comment by giminni** [comment]
@ayufan  Please find attached my ipvs.txt file from 'make menuconfig' made from the last git linux-build pull. Can you please build the rock64 and rockpro64 images from it?

[ipvs.txt](https://github.com/ayufan-rock64/linux-build/files/2198177/ipvs.txt)

**Comment by ayufan** [comment]
C'mon prepare PR, this does not help: I don't know what was added/changed, nor I can use it :)

**Comment by giminni** [comment]
@ayufan I forked the linux-kernel repo, instantiated a docker container, added the missing kernel modules and was successfully compiled a new kernel. How to I make a PR if I use git status I see no changes at all. Please advise.

**Comment by giminni** [comment]
wrong place after I know how to make a PR, guessing from forum
1) make rockchip_linux_config
2) make menuconfig
3) make -j 4

got a fatal error> curses.h: no such file or directorz
