### ISSUE TITLE
want some kernel option to be effective

### ISSUE THREAD

**Issue by kometchtech** [ayufan-rock64/linux-build#24]
Hello,

The following error message is output when starting up.
Since there seems to be no module even if the package is included, is it possible to enable the kernel option?

**CONFIG_AUTOFS4_FS**
`systemd[1]: Failed to insert module 'autofs4': No such file or directory`

**CONFIG_ZRAM**
`init-zram-swapping[508]: modinfo: ERROR: Module zram not found.`

For now it has been confirmed in the following image.
- xenial-minimal-rock64-0.4.17-85-arm64.img.xz

**Comment by ayufan** [comment]
Please prepare a PR to https://github.com/ayufan-rock64/linux-kernel/

**Comment by ayufan** [comment]
`CONFIG_AUTOFS4_FS` is added.

**Comment by ESProcessing** [comment]
It has not shown up in 0.5.10 though?

**Comment by xalius** [comment]
The config options have been added, should be in the next release/pre-release.
