### ISSUE TITLE
0.7.9 RockPro64 with 4.18 kernel - NVMe for rootfs

### ISSUE THREAD

**Issue by dukla2000** [ayufan-rock64/linux-build#262]
Please could next build of 4.18 kernel include PCIe & NVMe modules by default?

It seems at 4.18-rc3-1060 they are loaded after rootfs is mounted which prevents use of NVMe for rootfs. See https://forum.pine64.org/showthread.php?tid=6082&pid=39898#pid398980 (post 26 & 27)

Thanks

**Comment by ayufan** [comment]
No. It can't. You can add these kernel modules to initramfs.
