### ISSUE TITLE
Avahi - headless discovery

### ISSUE THREAD

**Issue by alexellis** [ayufan-rock64/linux-build#27]
Would you consider adding Avahi into the Ubuntu images? It's a very convenient experience with the RPi - you flash the image, then plug in and "raspberrypi.local" appears on the network for renaming / IP discovery etc. When I use these images I must have a screen to find the IP given by DHCP.

**Comment by skyway22** [comment]
you know that ```sudo apt-get install avahi-daemon``` does this for you?
