### ISSUE TITLE
RockPro64: mainline don't work on eMMC

### ISSUE THREAD

**Issue by bullet64** [ayufan-rock64/linux-build#273]
I updated kernel 4.4. to 4.18.0.rc8-1060 but it don't boot.

- PCIe SATA card with two 2,5'' HDD
- USB3 2,5'' HDD 
- 32GB eMMC Modul
- RockPro64 v2.2 with 2GB RAM

Kernel 4.4.x without any problem.

https://pastebin.com/90yRyc1f

**Comment by bullet64** [comment]
Maybe -> https://forum.pine64.org/showthread.php?tid=6552&pid=41169#pid41169

**Comment by stikonas** [comment]
I'm on linux-rockchip kernel (for-next branch which will become mainline 4.20). This patch helped me.

**Comment by ayufan** [comment]
I reverted problematic patch and it should make my 4.19 to work correctly.
