### ISSUE TITLE
how to build kernel for rockpro64

### ISSUE THREAD

**Issue by harinchandu** [ayufan-rock64/linux-build#284]
hi 
I am new to this,
please guide me,
How to build u-boot and kernel for rockpro 64 
Thank you

**Comment by ayufan** [comment]
Look at `dev.mk`: https://github.com/ayufan-rock64/linux-kernel.

**Comment by harinchandu** [comment]
is the defconfig (rockchip_linux_defconfig) same for rock and rockpro64??
thank you
