### ISSUE TITLE
Requesting build name change...

### ISSUE THREAD

**Issue by duckartes** [ayufan-rock64/linux-build#289]
Could the builds have a PREFIX such as rockpro64 and rock64 so the builds are separated for easier readability on https://github.com/ayufan-rock64/linux-build/releases/?

I just spent a good hour freaking out that my board might have been dead (I don't have any dev tools, I just rely on being able to write a SD and view it on a screen) because I downloaded TWO rock64 images when I needed rockpro64. 

It's a bit difficult to see them in the list....

**Comment by ayufan** [comment]
I think that this is controversial change. I would rather stick with current scheme.
