### ISSUE TITLE
Kernell wrong

### ISSUE THREAD

**Issue by oskr70** [ayufan-rock64/linux-build#316]
I have installed a wrong kernell for my rockpro64. The commands line I type are:

`wget: https://github.com/ayufan-rock64/linux-mainline-kernel/releases/download/4.20.0-1083-ayufan/linux-headers-4.20.0-1083-ayufan-g686e1f1aa461_4.20.0-1083-ayufan_arm64.deb

#wget: https://github.com/ayufan-rock64/linux-mainline-kernel/releases/download/4.20.0-1081-ayufan/linux-image-4.20.0-1081-ayufan-ge8f6e497ec01-dbg_4.20.0-1081-ayufan_arm64.deb

 #wget: https://github.com/ayufan-rock64/linux-mainline-kernel/releases/download/4.20.0-1083-ayufan/linux-image-4.20.0-1083-ayufan-g686e1f1aa461_4.20.0-1083-ayufan_arm64.deb

 #sudo dpkg -i *.deb`
Yes, I hnow, sorry for it, the second command is not a same version than the others.
My question is how to revert to a linux kernel original (4.4) from the original version,

And what kernel are the best for my rock64 if I update a kernel? (for rockpro64 and mmc 32gb)
Thanks in advance and sorry for my english but is not my native language

**Comment by ayufan** [comment]
`change-default-kernel.sh` or remove old kernels

The 4.4 is best for now.

**Comment by oskr70** [comment]
ok thanks I'll try it
