### ISSUE TITLE
Request to update kernel config to enable Kubernetes support

### ISSUE THREAD

**Issue by tslpre** [ayufan-rock64/linux-build#32]
Hello!

I've installed the relevant packages to test the ROCK64 as master for a new cluster and found that the kernel config would require some flags to allow proper init of the master node.

By using:

curl -L https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh | CONFIG=/path/to/.config /bin/bash

I could see what is missing:

CONFIG_POSIX_MQUEUE: missing
CONFIG_MEMCG_SWAP_ENABLED: missing
CONFIG_BLK_DEV_THROTTLING: missing
CONFIG_CFQ_GROUP_IOSCHED: missing
CONFIG_CGROUP_HUGETLB: missing
CONFIG_NET_CLS_CGROUP: missing
CONFIG_CGROUP_NET_PRIO: missing
CONFIG_RT_GROUP_SCHED: missing
CONFIG_IP_VS_NFCT: missing
CONFIG_IP_VS_RR: missing
CONFIG_AUFS_FS: missing
/dev/zfs: missing

CONFIG_POSIX_MQUEUE is the only that is really needed/necessary - the others are optional (depending on what you will use later).

Would it be possible to add them to the standard config?

**Comment by ayufan** [comment]
Yes. Please prepare a kernel config change.

**Comment by tslpre** [comment]
Excellent - I've updated ../arch/arm64/configs/rockchip_linux_defconfig on my machine and will test it soon before sharing.

Just to confirm, Is that the right defconfig to target or I should prefer another one?

**Comment by ayufan** [comment]
Yes

**Comment by tslpre** [comment]
Tested succesfully on my ROCK64 - Kubernetes now works fine.

Made a PR in ayufan-rock64/linux-kernel:
(https://github.com/ayufan-rock64/linux-kernel/pull/14)

**Comment by ayufan** [comment]
This is done.
