### ISSUE TITLE
Errors when trying to update to latest pre-release build

### ISSUE THREAD

**Issue by thewonderer73** [ayufan-rock64/linux-build#321]
Went from stable rock64 0.79 to 0.711 by editing so that pre-release would be enabled.  Got the following error at the end of the update using the command

sudo apt-get install linux-rock64 -y

rock64@rock64:/etc$ sudo apt-get install linux-rock64 -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  board-package-rock64-0.7-44 linux-headers-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1
  u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1033-gdf02018479
Suggested packages:
  linux-firmware-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1
The following packages will be REMOVED:
  board-package-rock64-0.7-30 u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1025-g482cd6ec8b
The following NEW packages will be installed:
  board-package-rock64-0.7-44 linux-headers-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1
  u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1033-gdf02018479
The following packages will be upgraded:
  linux-rock64
1 upgraded, 4 newly installed, 2 to remove and 0 not upgraded.
Need to get 25.9 MB of archives.
After this operation, 144 MB of additional disk space will be used.
Get:1 http://deb.ayufan.eu/orgs/ayufan-rock64/pre-releases  linux-rock64 0.7.11 [1182 B]
Get:2 http://deb.ayufan.eu/orgs/ayufan-rock64/releases  board-package-rock64-0.7-44 0.7-44 [1312 kB]
Get:3 http://deb.ayufan.eu/orgs/ayufan-rock64/releases  u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1033-gdf02018479 2017.09-rockchip-ayufan-1033-gdf02018479 [365 kB]
Get:4 http://deb.ayufan.eu/orgs/ayufan-rock64/releases  linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 4.4.154-1124-rockchip-ayufan [13.9 MB]
Get:5 http://deb.ayufan.eu/orgs/ayufan-rock64/releases  linux-headers-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 4.4.154-1124-rockchip-ayufan [10.3 MB]
Fetched 25.9 MB in 1min 30s (286 kB/s)
(Reading database ... 53925 files and directories currently installed.)
Preparing to unpack .../linux-rock64_0.7.11_arm64.deb ...
Unpacking linux-rock64 (0.7.11) over (0.7.9) ...
(Reading database ... 53925 files and directories currently installed.)
Removing board-package-rock64-0.7-30 (0.7-30) ...
Selecting previously unselected package board-package-rock64-0.7-44.
(Reading database ... 53869 files and directories currently installed.)
Preparing to unpack .../board-package-rock64-0.7-44_0.7-44_all.deb ...
Unpacking board-package-rock64-0.7-44 (0.7-44) ...
(Reading database ... 53930 files and directories currently installed.)
Removing u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1025-g482cd6ec8b (2017.09-rockchip-ayufan-1025-g482cd6ec8b) ...
Selecting previously unselected package u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1033-gdf02018479.
(Reading database ... 53923 files and directories currently installed.)
Preparing to unpack .../u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1033-gdf02018479_2017.09-rockchip-ayufan-1033-gdf02018479_all.deb ...
Unpacking u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1033-gdf02018479 (2017.09-rockchip-ayufan-1033-gdf02018479) ...
Selecting previously unselected package linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1.
Preparing to unpack .../linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1_4.4.154-1124-rockchip-ayufan_arm64.deb ...
Unpacking linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 (4.4.154-1124-rockchip-ayufan) ...
Selecting previously unselected package linux-headers-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1.
Preparing to unpack .../linux-headers-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1_4.4.154-1124-rockchip-ayufan_arm64.deb ...
Unpacking linux-headers-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 (4.4.154-1124-rockchip-ayufan) ...
Setting up linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 (4.4.154-1124-rockchip-ayufan) ...
update-initramfs: Generating /boot/initrd.img-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1
kdump-tools: Generating /var/lib/kdump/initrd.img-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1
/etc/kernel/postinst.d/zz-update-extlinux: line 3: /usr/local/sbin/update_extlinux.sh: No such file or directory
run-parts: /etc/kernel/postinst.d/zz-update-extlinux exited with return code 127
dpkg: error processing package linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 (--configure):
 installed linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 package post-installation script subprocess returned error exit status 1
Setting up u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1033-gdf02018479 (2017.09-rockchip-ayufan-1033-gdf02018479) ...
Consider upgrading device bootloader with 'rock64_upgrade_bootloader.sh'.
Setting up board-package-rock64-0.7-44 (0.7-44) ...
Installing new version of config file /etc/kernel/postinst.d/zz-update-extlinux ...
Creating new extlinux.conf...
Installing new extlinux.conf...
dpkg: dependency problems prevent configuration of linux-rock64:
 linux-rock64 depends on linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1; however:
  Package linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 is not configured yet.

dpkg: error processing package linux-rock64 (--configure):
 dependency problems - leaving unconfigured
Setting up linux-headers-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 (4.4.154-1124-rockchip-ayufan) ...
Processing triggers for rsyslog (8.32.0-1ubuntu4) ...
Errors were encountered while processing:
 linux-image-4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1
 linux-rock64
E: Sub-process /usr/bin/dpkg returned an error code (1)

UPDATE.

When i restart my rock64 it seem to have updated the linux image to 1124

Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 aarch64)
                _     __   _  _

**Comment by ayufan** [comment]
It should be fixed.
