### ISSUE TITLE
machine-id conflict

### ISSUE THREAD

**Issue by moikot** [ayufan-rock64/linux-build#324]
I'm using bionic-containers-rock64-0.7.11-1075-arm64.img.xz from 0.7.11: gitlab-ci-linux-build-75 in my Kubernetes cluster and I have problems with Weave overlay network. The nodes are not connecting to each other because all the boards have the same machine-id (/etc/machine-id). 
I'm not a Linux expert but would it be possible to delete /etc/machine-id while bionic-containers-rock64 image creation (as the last step before the final shutdown) so that it can be recreated when I start my SBC the first time?

**Comment by ayufan** [comment]
It will be part of next release, the 0.8.0rc5 or later.
