### ISSUE TITLE
ffmpeg dependencies broken in bionic-minimal-rock64-0.7.12-1077-arm64

### ISSUE THREAD

**Issue by dowoco** [ayufan-rock64/linux-build#328]
`ffmpeg : Depends: libavdevice58 (>= 7:3.5~git20180113) but it is not going to be installed`

libgl1-mesa-dri : Depends: libdrm-amdgpu1 (>= 2.4.90) but 2.4.89-1ayufan1 is to be installed Depends: libdrm-freedreno1 (>= 2.4.92) but 2.4.89-1ayufan1 is to be installed

Could these dependencies be updated?

**Comment by didi1357** [comment]
@dowoco This was fixed meanwhile. At least for me it worked. Can be closed now.

**Comment by ayufan** [comment]
This is resolved

**Comment by dowoco** [comment]
I can also confirm this is resolved
