### ISSUE TITLE
Building image

### ISSUE THREAD

**Issue by marksaitis** [ayufan-rock64/linux-build#330]
Hi,

Can somebody just do a normal 1 page quick guide on how to build the image? I looked at sources on rock and ayufan repos and it's just too much all over the place.
I want to know how to simply build kernel with it's dtbs + initrd or whatever else is needed here so I can simply put it in an empty ext4 sdcard and just boot it up from there.

**Comment by ayufan** [comment]
This is a little scattered across multiple repos, but starting point would be:
- https://github.com/ayufan-rock64/linux-build/blob/master/recipes/compilation.md
- https://github.com/ayufan-rock64/linux-build/blob/master/.gitlab-ci.yml
- https://github.com/ayufan-rock64/linux-kernel/blob/master/.gitlab-ci.yml
- https://github.com/ayufan-rock64/linux-u-boot/blob/master/.gitlab-ci.yml
- https://github.com/ayufan-rock64/linux-package/blob/master/.gitlab-ci.yml
