### ISSUE TITLE
RP64: mainline boot delay

### ISSUE THREAD

**Issue by bullet64** [ayufan-rock64/linux-build#331]
In mainline 5.0.0 we will get an boot delay.

[dmesg](https://pastebin.com/cECVRFBR)

`[    5.760869] Trying to unpack rootfs image as initramfs...
[   25.802478] Freeing initrd memory: 5460K`

**Comment by ayufan** [comment]
Yes, to investigate.

**Comment by bullet64** [comment]
Works with 5.6
