### ISSUE TITLE
rp64: wireguard kernel module

### ISSUE THREAD

**Issue by bullet64** [ayufan-rock64/linux-build#333]
Hi Kamil, do you plan to add kernel-module for wireguard?

```
rock64@rockpro64:~$ sudo ip link add dev wg0 type wireguard
[sudo] password for rock64: 
RTNETLINK answers: Operation not supported
```

**Comment by ayufan** [comment]
Not really. There's dkms for that.

**Comment by bullet64** [comment]
@ayufan Thanks for the hint. For other people, build it himself.

`sudo apt-get install libmnl-dev libelf-dev linux-headers-$(uname -r) build-essential pkg-config
git clone https://git.zx2c4.com/WireGuard
cd WireGuard/src
make
sudo make install`

Tested on 4.4.167-1140-rockchip-ayufan-g6f266fb5d677 and it works!

**Comment by RussianNeuroMancer** [comment]
It's also available here, including armhf and arm64 builds: https://launchpad.net/~wireguard/+archive/ubuntu/wireguard

**Comment by ayufan** [comment]
Yes, but you still need working dkms, per.: https://github.com/ayufan-rock64/linux-build/blob/master/recipes/dkms.md
