### ISSUE TITLE
rp64: wlan crash

### ISSUE THREAD

**Issue by bullet64** [ayufan-rock64/linux-build#334]
Yesterday my rp64 crashes. wifi wasn't fully configured.

https://pastebin.com/JWXajREi

The cause was a reboot of my router.

Kernel
`Linux rp64_nextcloud 4.4.167-1140-rockchip-ayufan-g6f266fb5d677 #1 SMP Fri Mar 8 22:31:21 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by ayufan** [comment]
Interesting. Maybe we need different binary blob.

**Comment by bullet64** [comment]
Some news about this bug.

It has nothing to do with wifi. I removed the wifi-modul and this error happens again. So i removed pcie-nvme-ssd and then the error don't come back.

@ayufan : This error occurs when i am testing wireguard. This rp64 was one endpoint.

On another rp64 (second endpoint) with pcie-nvme-ssd this error doesn't occur.

Only difference seems to be that rp64 with problems run on 0.7.14, and the other rp64 on 0.7.11 (i think) Both using same kernel.

`Linux rp_64_test 4.4.167-1140-rockchip-ayufan-g6f266fb5d677 #1 SMP Fri Mar 8 22:31:21 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
`
