### ISSUE TITLE
bionic container 0.8 rc5 not expand filesystem to all my 64gb microsd

### ISSUE THREAD

**Issue by daveraver** [ayufan-rock64/linux-build#335]
I have installed this image and it doesn't expand the filesystem to all 64gb microsd. I dont know why, it hasn't never happened before... thanks in advance!

**Comment by daveraver** [comment]
I want to say I burn the image with etcher... Has it happened to anyone else!

**Comment by bullet64** [comment]
Under **/usr/local/sbin** you will find **resize_rootfs.sh**

This script will expand the rootfs. Script is from ayufan.

**Comment by daveraver** [comment]
ok, thanks, it works!!

**Comment by bullet64** [comment]
Nice that it works. Please close your issue.
