### ISSUE TITLE
hardware acceleration not working after updating libmali-rk-utgard-450-r7p0

### ISSUE THREAD

**Issue by unicorn-farts** [ayufan-rock64/linux-build#336]
Rock64 using bionic-lxde: Hardware video acceleration seems to have broken for me. Flashing to a older image had resolved the problem. After some testing, I find once the libmali-rk-utgard-450-r7p0 package is updated to 1.6-3ayufan5, fullscreen video became very choppy in mpv, and rkmpv fails to open videos at all.

My solution is to downgrade to package version 1.6-1ayufan10 from wget https://launchpad.net/~ayufan/+archive/ubuntu/rock64-testing-ppa/+build/14420231/+files/libmali-rk-utgard-450-r7p0_1.6-1ayufan10_arm64.deb

and install with dpkg -i libmali-rk-utgard-450-r7p0_1.6-1ayufan10_arm64.deb

I hope this was helpful for some

**Comment by DmitryMyadzelets** [comment]
Why this issue is closed? If something is broken it should be fixed, I think.
