### ISSUE TITLE
Run docker in 0.4.17: jenkins-linux-build-rock-64-85

### ISSUE THREAD

**Issue by Mimuni** [ayufan-rock64/linux-build#34]
After I successfully installed Docker I get the following error message

> could not create session key: function not implemented

It does not matter which docker version I use. Is the error possibly due to the fact that the kernel does not support certain functions? is there a possibility to change this?

**Comment by rockford** [comment]
I suggest trying a newer build. 0.4.17 is quite old. Try 0.5.6.

[https://github.com/ayufan-rock64/linux-build/releases](url)

**Comment by Mimuni** [comment]
I would like to try the newer image, but unfortunately I get the network interface not to work. This works in the older image without problems.
ifconfig eth0 outputs the following:
```
stmmac_hw_setup:
DMA engine initialization failed
stmmac_open: HW setup failed
SIOCSIFFLAGS: Device or resource busy
```

**Comment by ayufan** [comment]
This is done as part of 0.5.8.

**Comment by Mimuni** [comment]
Many thanks for the docker adjustments, but the problem with the network card is unfortunately with version 0.5.8 not yet fixed. It still exists only eth0, which I can not configure. 
Is there a workaround for this?

**Comment by ayufan** [comment]
I need more information, as this I do not have this problem.

**Comment by ayufan** [comment]
Can you create a new issue?
