### ISSUE TITLE
How can I update from version 0.7.9

### ISSUE THREAD

**Issue by gedas07** [ayufan-rock64/linux-build#344]
How can I update from 0.7.9 
I try apt-get update
apt-get dist-upgrade 
and  sudo apt-get install linux-rock64 -y ç

And don't update ,what can i do?

**Comment by ayufan** [comment]
Update does work, but `0.7.9` is last release that is marked as stable. All rest ones are pre-releases, so you have to explicitly enable pre-release.

**Comment by gedas07** [comment]
And how can I enable?

**Comment by bullet64** [comment]
Look @ https://github.com/ayufan-rock64/linux-build/releases/

> To enable upgrading to pre-releases edit nano /etc/apt/sources.list.d/ayufan-rock64.list

**Comment by gedas07** [comment]
Thanks a lot , I see now in the archive 
I des comment the third line 
I try tomorrow 
Thanks another time
