### ISSUE TITLE
Rockpro64 ethernet not connecting

### ISSUE THREAD

**Issue by Itsmejonny** [ayufan-rock64/linux-build#349]
I did the bionic-mate-rockpro64-0.8.0rc7-1114-armhf.img.xz upgrade and first started getting errors and now cannot connect to the internet ethO. says "ethO is down", iwconfig says "no wireless extensions" ALso only the right orange LED light is on on the ethernet input and the green left one only comes on during system boot.
ifconfig says" eth0: flags=4099<UP ,BROADCAST , MULTICAST>  mtu 1500
                                inet6 fe80::281e:d9ff:fe14:ef1d  prefixlen 64  scopeid 0x20<link>
                                RX packets 0  bytes (0.0 B)
                                RX errors  0  dropped 0  overruns  0  frame 0
                                TX  packets  7 bytes 841 (841.0 B)
                                TX errors  0  dropped  0  overrruns 0  carrier  0  collisions  0
                                device interrupt 24

                         lo:  flags=73<UP ,LOOPBACK .RUNNING>  mtu 65536
                                inet  127.0.0.1  netmask  255.0.0.0
                                inet6  : :  prefixlen  128  scopeid  0x10<host>
                                loop  txqueuelen  1   (Local Loopback)
                                RX  packets  3400  bytes  242504  (242.5 KB)
                                RX errors 0  dropped  0  overrruns  0  frame  0
                                TX  packets  3400  bytes  242504  (242.5  KB)
                                TX  errors  0  dropped 0  overruns  0  carrier  0  collisions  0

lo, eth0, wlx are not responding

Thanks for any help beforehand. Im a noob to linux so Im still learning my way around...

**Comment by evilbunny2008** [comment]
@Itsmejonny what happens if you do the following?

`sudo ifconfig -a`

**Comment by Itsmejonny** [comment]
Hey evilbunny2008,
I ran the ifconfig -a and it gave the status of the etho and lo. Pretty much the same stuff i shared a before in my original post.

**Comment by evilbunny2008** [comment]
@Itsmejonny  what power supply are you using?

**Comment by Itsmejonny** [comment]
I'm using the 12V 5 cause I plan to upgrade to the NAS case with HD'S

**Comment by Itsmejonny** [comment]
got an update

got a new error connection failure, failed to add/edit connection
(3) device not found

**Comment by BHSPitMonkey** [comment]
Any update on how you resolved this? I'm having the same problem.
