### ISSUE TITLE
USB 3.0 disconnect hangs USB subsystem

### ISSUE THREAD

**Issue by rmbusy** [ayufan-rock64/linux-build#36]
First saw this with xenial-minimal-rock64-0.4.17-85-arm64.img.  Next tried jessie-minimal-rock64-0.5.7-101-arm64.img, and seeing same basic issue.  After disconnecting USB HD, any attempt to interface with USB causes timeout and kernel panic.

Using rock64 4GB, booting from 4G SD Card.  Connected a USB 3.0 external disk drive (already formatted w/ 2 linux partitions).  Drive is a Seagate 2GB 2.5" hybrid.

Mounted both partitions under /media/sda1 & /media/sda3.  Did 'ls -ahl' on both mounts.  Then unmounted both partitions, and verified with "mount".  

The jessie image console output at disconnect was : 
[  873.393783] usb usb5-port1: Cannot enable. Maybe the USB cable is bad?
[  873.394805] xhci-hcd xhci-hcd.8.auto: Cannot set link state.
[  873.395754] usb usb5-port1: cannot disable (err = -32)
[  875.910788] usb usb5-port1: Cannot enable. Maybe the USB cable is bad?
[  875.911801] xhci-hcd xhci-hcd.8.auto: Cannot set link state.
[  875.912735] usb usb5-port1: cannot disable (err = -32)
[  878.426774] usb usb5-port1: Cannot enable. Maybe the USB cable is bad?
[  878.427787] xhci-hcd xhci-hcd.8.auto: Cannot set link state.
[  878.428729] usb usb5-port1: cannot disable (err = -32)
[  880.943791] usb usb5-port1: Cannot enable. Maybe the USB cable is bad?
[  880.944809] xhci-hcd xhci-hcd.8.auto: Cannot set link state.
[  880.945741] usb usb5-port1: cannot disable (err = -32)
[  880.946543] xhci-hcd xhci-hcd.8.auto: Cannot set link state.
[  880.947492] usb usb5-port1: cannot disable (err = -32)
[  880.948328] scsi host0: uas_post_reset: alloc streams error -19 after reset
[  880.952607] sd 0:0:0:0: [sda] Synchronizing SCSI cache

Awhile later, tried to do a lsusb, and it hung.  Then kernel panic was next : 
[ 5400.438255] INFO: task lsusb:4202 blocked for more than 120 seconds.
[ 5400.438942]       Not tainted 4.4.77-rockchip-ayufan-101 #1
[ 5400.439562] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 5400.440415] lsusb           D ffffff8008084f28     0  4202    873 0x00000000
[ 5400.441203] Call trace:
[ 5400.441483] [<ffffff8008084f28>] __switch_to+0x9c/0xa8
[ 5400.446148] [<ffffff8008b75514>] __schedule+0x42c/0x6c4
[ 5400.450771] [<ffffff8008b75834>] schedule+0x88/0x9c
[ 5400.455345] [<ffffff8008b75aec>] schedule_preempt_disabled+0x14/0x1c
[ 5400.460089] [<ffffff8008b76f6c>] __mutex_lock_slowpath+0xc8/0x124
[ 5400.464750] [<ffffff8008b77004>] mutex_lock+0x3c/0x54
[ 5400.469251] [<ffffff800874d2fc>] read_descriptors+0x54/0xf4
[ 5400.473846] [<ffffff8008253318>] sysfs_kf_bin_read+0x8c/0x9c
[ 5400.478392] [<ffffff8008252a2c>] kernfs_fop_read+0xe8/0x178
[ 5400.482946] [<ffffff80081de574>] __vfs_read+0x48/0xe0
[ 5400.487455] [<ffffff80081dee20>] vfs_read+0x90/0x134
[ 5400.491928] [<ffffff80081df940>] SyS_read+0x54/0x98
[ 5400.496328] [<ffffff80080826f0>] el0_svc_naked+0x24/0x28
[ 5400.500756] Kernel panic - not syncing: hung_task: blocked tasks
[ 5400.505212] CPU: 0 PID: 29 Comm: khungtaskd Not tainted 4.4.77-rockchip-ayufan-101 #1
[ 5400.509836] Hardware name: Rockchip RK3328 Rock64 (DT)
[ 5400.514204] Call trace:
[ 5400.518325] [<ffffff80080881b0>] dump_backtrace+0x0/0x1e0
[ 5400.522723] [<ffffff80080883b4>] show_stack+0x24/0x30
[ 5400.527010] [<ffffff8008524778>] dump_stack+0x94/0xb4
[ 5400.531223] [<ffffff800818cde4>] panic+0xe8/0x234
[ 5400.535325] [<ffffff8008153dfc>] watchdog+0x2d8/0x300
[ 5400.539450] [<ffffff80080d3cf4>] kthread+0xf0/0xf8
[ 5400.543481] [<ffffff8008082690>] ret_from_fork+0x10/0x40
[ 5400.547472] CPU3: stopping
[ 5400.551171] CPU: 3 PID: 0 Comm: swapper/3 Not tainted 4.4.77-rockchip-ayufan-101 #1
[ 5400.555341] Hardware name: Rockchip RK3328 Rock64 (DT)
[ 5400.559247] Call trace:
[ 5400.562857] [<ffffff80080881b0>] dump_backtrace+0x0/0x1e0
[ 5400.566760] [<ffffff80080883b4>] show_stack+0x24/0x30
[ 5400.570619] [<ffffff8008524778>] dump_stack+0x94/0xb4
[ 5400.574420] [<ffffff800808d1fc>] handle_IPI+0x138/0x240
[ 5400.578203] [<ffffff8008080cf8>] gic_handle_irq+0xa0/0xc8
[ 5400.581987] Exception stack(0xffffffc0f581fe10 to 0xffffffc0f581ff40)
[ 5400.585889] fe00:                                   ffffffc0f581c000 0000000000000000
[ 5400.589952] fe20: 0000000000000000 ffffff80090e0d40 0100000000000000 0000001e36670c1b
[ 5400.594039] fe40: 00000000003a14ec 0000000000000000 ffffffc0f581ff5c ffffffc0f581c000
[ 5400.598124] fe60: 00000000000009c0 0000000000000000 0000000000000400 0000000000000001
[ 5400.602195] fe80: 0000000000000001 ffffffffffffffed ffffff80081df8ec 0000007f7c5c1780
[ 5400.606266] fea0: 0000000000000010 ffffff80091f2000 0000000000000000 ffffff80091f2928
[ 5400.610333] fec0: ffffff80091f2000 ffffff80090c573c 0000000000000000 00000000032e5000
[ 5400.614367] fee0: 00000000032e8000 0000000002b7e234 0000000000000000 ffffffc0f581ff40
[ 5400.618376] ff00: ffffff80080848e0 ffffffc0f581ff40 ffffff80080848e4 0000000060000145
[ 5400.622388] ff20: ffffffc0f581c000 ffffff80090c5000 ffffffffffffffff 0000000000000000
[ 5400.626374] [<ffffff8008081fb4>] el1_irq+0xb4/0x140
[ 5400.630050] [<ffffff80080848e4>] arch_cpu_idle+0x70/0x108
[ 5400.633717] [<ffffff80080fbe64>] default_idle_call+0x28/0x30
[ 5400.637395] [<ffffff80080fc0a8>] cpu_startup_entry+0x1cc/0x2b8
[ 5400.641075] [<ffffff800808ccb0>] secondary_start_kernel+0x194/0x1a0
[ 5400.644814] [<0000000002b7e178>] 0x2b7e178
[ 5400.648364] CPU1: stopping
[ 5400.651779] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 4.4.77-rockchip-ayufan-101 #1
[ 5400.655731] Hardware name: Rockchip RK3328 Rock64 (DT)
[ 5400.659468] Call trace:
[ 5400.662947] [<ffffff80080881b0>] dump_backtrace+0x0/0x1e0
[ 5400.666740] [<ffffff80080883b4>] show_stack+0x24/0x30
[ 5400.670496] [<ffffff8008524778>] dump_stack+0x94/0xb4
[ 5400.674231] [<ffffff800808d1fc>] handle_IPI+0x138/0x240
[ 5400.677983] [<ffffff8008080cf8>] gic_handle_irq+0xa0/0xc8
[ 5400.681768] Exception stack(0xffffffc0f5817e10 to 0xffffffc0f5817f40)
[ 5400.685716] 7e00:                                   ffffffc0f5814000 0000000000000000
[ 5400.689816] 7e20: 0000000000000000 ffffff80090e0d40 0100000000000000 0000001e3677e49b
[ 5400.693897] 7e40: 00000000003a150c 0000000000000000 ffffffc0f5817f5c ffffffc0f5814000
[ 5400.697952] 7e60: 00000000000009c0 0000000000000400 0000000000000400 0000000000000001
[ 5400.702006] 7e80: 0000000000000001 000003f98e90a718 ffffff8008223a14 0000007fadf6f41c
[ 5400.706058] 7ea0: 0000000000000010 ffffff80091f2000 0000000000000000 ffffff80091f2928
[ 5400.710145] 7ec0: ffffff80091f2000 ffffff80090c573c 0000000000000000 00000000032e5000
[ 5400.714263] 7ee0: 00000000032e8000 0000000002b7e234 0000000000000000 ffffffc0f5817f40
[ 5400.718405] 7f00: ffffff80080848e0 ffffffc0f5817f40 ffffff80080848e4 0000000060000145
[ 5400.722602] 7f20: ffffffc0f5814000 ffffff80090c5000 ffffffffffffffff 0000000000000000
[ 5400.726810] [<ffffff8008081fb4>] el1_irq+0xb4/0x140
[ 5400.730765] [<ffffff80080848e4>] arch_cpu_idle+0x70/0x108
[ 5400.734753] [<ffffff80080fbe64>] default_idle_call+0x28/0x30
[ 5400.738727] [<ffffff80080fc0a8>] cpu_startup_entry+0x1cc/0x2b8
[ 5400.742660] [<ffffff800808ccb0>] secondary_start_kernel+0x194/0x1a0
[ 5400.746630] [<0000000002b7e178>] 0x2b7e178
[ 5400.750383] CPU2: stopping
[ 5400.754010] CPU: 2 PID: 0 Comm: swapper/2 Not tainted 4.4.77-rockchip-ayufan-101 #1
[ 5400.758207] Hardware name: Rockchip RK3328 Rock64 (DT)
[ 5400.762204] Call trace:
[ 5400.765946] [<ffffff80080881b0>] dump_backtrace+0x0/0x1e0
[ 5400.769968] [<ffffff80080883b4>] show_stack+0x24/0x30
[ 5400.773914] [<ffffff8008524778>] dump_stack+0x94/0xb4
[ 5400.777800] [<ffffff800808d1fc>] handle_IPI+0x138/0x240
[ 5400.781660] [<ffffff8008080cf8>] gic_handle_irq+0xa0/0xc8
[ 5400.785519] Exception stack(0xffffffc0f581be10 to 0xffffffc0f581bf40)
[ 5400.789506] be00:                                   ffffffc0f5818000 0000000000000000
[ 5400.793658] be20: 0000000000000000 ffffff80090e0d40 0100000000000000 0000001e3677e49b
[ 5400.797839] be40: 00000000003a150c 0000000000000000 ffffffc0f581bf5c ffffffc0f5818000
[ 5400.802035] be60: 00000000000009c0 0000000000000400 0000000000000400 0000000000000001
[ 5400.806202] be80: 0000000000000001 000000000000000a ffffff80081f233c 0000007f8440c1b4
[ 5400.810366] bea0: 0000000000000001 ffffff80091f2000 0000000000000000 ffffff80091f2928
[ 5400.814498] bec0: ffffff80091f2000 ffffff80090c573c 0000000000000000 00000000032e5000
[ 5400.818641] bee0: 00000000032e8000 0000000002b7e234 0000000000000000 ffffffc0f581bf40
[ 5400.822800] bf00: ffffff80080848e0 ffffffc0f581bf40 ffffff80080848e4 0000000060000145
[ 5400.827006] bf20: ffffffc0f5818000 ffffff80090c5000 ffffffffffffffff 0000000000000000
[ 5400.831205] [<ffffff8008081fb4>] el1_irq+0xb4/0x140
[ 5400.835124] [<ffffff80080848e4>] arch_cpu_idle+0x70/0x108
[ 5400.839095] [<ffffff80080fbe64>] default_idle_call+0x28/0x30
[ 5400.843051] [<ffffff80080fc0a8>] cpu_startup_entry+0x1cc/0x2b8
[ 5400.846968] [<ffffff800808ccb0>] secondary_start_kernel+0x194/0x1a0
[ 5400.850920] [<0000000002b7e178>] 0x2b7e178
[ 5400.854659] CRU:
[ 5400.858177] 00000000: 000070d7 00000486 000a3d70 00000000 00000000 00000000 00000000 00000000
[ 5400.862468] 00000020: 00002083 00001441 00000001 00000000 00000000 00000000 00000000 00000000
[ 5400.866745] 00000040: 00001032 00001441 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.870992] 00000060: 000023d7 00000458 000a3d70 00000000 00000000 00000000 00000000 00000000
[ 5400.875177] 00000080: 00001113 00002000 00005a5a 00000000 3a98c064 00000001 00000000 00000000
[ 5400.879316] 000000a0: 00001036 00001441 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.883406] 000000c0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.887436] 000000e0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.891409] 00000100: 000007c0 00001115 00000003 00000000 00002c80 00008004 0000000f 00010014
[ 5400.895354] 00000120: 0000000f 00010014 0000000f 00010014 0000000f 00010014 00000207 00010014
[ 5400.899263] 00000140: 00000207 00010014 00000207 00010014 00008087 0000170c 000001df 000001e0
[ 5400.903156] 00000160: 00000717 00000244 0000000f 00000705 00004107 00000011 0000000b 00000017
[ 5400.907035] 00000180: 00000277 00008800 00000707 00000707 00000305 00000203 00007a97 00000002
[ 5400.910862] 000001a0: 00003111 0bb8ea60 00003113 00000003 00000042 0000001f 00000000 00000000
[ 5400.914689] 000001c0: 00000340 00000041 00000003 00000505 00000b31 00000000 00000000 00000000
[ 5400.918453] 000001e0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.922197] 00000200: 00000440 0000ffbe 0000ffbf 00000123 00000611 0000006a 000000bf 00000000
[ 5400.925935] 00000220: 000007e0 000000de 00000000 00000111 00000000 00000000 00000000 00000de2
[ 5400.929667] 00000240: 00009cf7 0000b800 00000000 00008002 00000000 00008fcc 00000021 00000003
[ 5400.933382] 00000260: 00000003 00000003 00000003 00000000 00000001 00000000 00000000 00000000
[ 5400.937063] 00000280: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.940712] 000002a0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.944269] 000002c0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.947729] 000002e0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.951135] 00000300: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.954482] 00000320: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.957794] 00000340: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.961086] 00000360: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.964346] 00000380: 00000004 00000000 00000004 00000000 00000004 00000000 00000004 00000000
[ 5400.967572] 000003a0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.970729] 000003c0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.973804] 000003e0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.976791] Kernel Offset: disabled
[ 5400.979293] Memory Limit: none
[ 5400.981734] rockchip-thermal ff250000.tsadc: channal 0: temperature(44 C)
[ 5400.984586] THERMAL REGS:
[ 5400.987031] 00000000: 00000200 00010013 00000101 00000000 00000000 00000000 00000000 00000000
[ 5400.990146] 00000020: 000001e1 00000000 00000000 00000000 00000209 00000000 00000000 00000000
[ 5400.993223] 00000040: 00000258 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5400.996219] 00000060: 00000004 00000004 000000fa 00000032 00000000 00000000 00000000 00000000
[ 5400.999180] 00000080: 00000000 00000000

**Comment by rmbusy** [comment]
Looks like the page formatting intercepted some of the addresses in the trace.  Attaching a text file with the trace information.

[kernelpanic.txt](https://github.com/ayufan-rock64/linux-build/files/1290194/kernelpanic.txt)

**Comment by ayufan** [comment]
This seems more to be problem with kernel, can you create an issue in this issue tracker: https://github.com/rockchip-linux/kernel/issues so it will be noticed by RK?

**Comment by rmbusy** [comment]
Moved issue to [](https://github.com/rockchip-linux/kernel/issues) so it can be tracked there.
