### ISSUE TITLE
rc10 breaks crappy rock64 boards again (rc9 was ok)

### ISSUE THREAD

**Issue by ketominer** [ayufan-rock64/linux-build#362]
Hi,

we talked on IRC about the issues I have with ~20 to 80% of rock64 boards depending on the batch. rc9 seemed to fix the problem but rc10 breaks it again. As u-boot didn't change, the change apparently is in the kernel but when reading the diff between the kernels I don't see anything RK3328 related, only RK3399. Tell me if I can help narrowing it down...

**Comment by Xeddius** [comment]
RC9 Mate build and RC10 Mate builds still broken. Rock64 V2 board.

**Comment by ayufan** [comment]
I did remove Mate from list of builds for Rock64, as the speed of the desktop composition was pretty bad on modesetting. The only supported for LXDE (even though it also has some bugs related to glamor that are not yet fixed).
