### ISSUE TITLE
RockPro64: root on lvm (nvme-disk) not booting

### ISSUE THREAD

**Issue by ftim-nl** [ayufan-rock64/linux-build#365]
@ayufan 

I have a RockPro64 with a nvme-disk connected via pcie. I would like to put root on lvm on this disk, but don't know how to do that.
When I don't use lvm, but format the disk with ext4 it works fine (I followed this post: https://yuncloud.ddns.net/wordpress/blog/2018/08/06/rockpro64-boot-from-the-nvme-disk/), but when I use lvm the rockpro64 will not boot. I think it has to do something with initrd of initramfs, but don't know how to solve this. Do you know a solution or can you make an image with this?

Many thanks for your very good work on this project.

**Comment by ayufan** [comment]
It should be fine with latest 0.8.2, as rockchip-pcie nad phy is compiled into kernel.
