### ISSUE TITLE
dm-crypt modules in latest kernel missing

### ISSUE THREAD

**Issue by georghildebrand** [ayufan-rock64/linux-build#366]
Hey there, 

in the latest kernel the dm-crypt modules are missing so luks disk encryption can not be used. Does anyone know if there is a newer kernel release upcoming containing these modules?

**Comment by ayufan** [comment]
Seems a bug. Can you revisit defconfig and add relevant modules?

**Comment by georghildebrand** [comment]
@ayufan where can i find the defconfig? sorry, never used this.

**Comment by ayufan** [comment]
https://github.com/ayufan-rock64/linux-kernel/, search for rockchip_linux_defconfig
