### ISSUE TITLE
Could you provide a real-time (PREEMPT_RT) kernel option?

### ISSUE THREAD

**Issue by laodouya** [ayufan-rock64/linux-build#368]
Hi,
  I'm enjoying rock64 and your images such as volumio, openmediavault, etc. Now I'm trying another audio software. But it seems to work greater with a real-time kernel. Could you please release a Debian image with PREEMPT_RT path, or provide a tutorial？

Thanks.

**Comment by ayufan** [comment]
I accept kernel patches tot https://github.com/ayufan-rock64/linux-kernel/
