### ISSUE TITLE
Please enable CONFIG_SND_USB_AUDIO in mainline builds

### ISSUE THREAD

**Issue by RussianNeuroMancer** [ayufan-rock64/linux-build#374]
Hello!

I noticed that CONFIG_SND_USB_AUDIO is currently not enabled in mainline builds. Is it possible to enable it?

**Comment by ayufan** [comment]
I accept contributions to https://github.com/ayufan-rock64/linux-mainline-kernel/ that does that.

**Comment by RussianNeuroMancer** [comment]
https://github.com/ayufan-rock64/linux-mainline-kernel/pull/12
