### ISSUE TITLE
[request] OpenSuse Tumbleweed Build for RockPro64

### ISSUE THREAD

**Issue by ibrainventures** [ayufan-rock64/linux-build#375]
Thank you for your great Work.

Only for testing, is it possible to have one edition with a 
Suse Build 

https://en.opensuse.org/Portal:ARM
15.1 

Suse Linux is a very Hardend and great running (e.g. Server) System with
a great support.

There was a :

https://en.opensuse.org/HCL:Pine64

but it would be great to see a Rockpro64 Build.

https://en.opensuse.org/HCL:Rock64

Best regards

**Comment by ayufan** [comment]
Unlikely that this repository will support this distro.

**Comment by patjak** [comment]
Hi, I've managed to build a Tumbleweed JeOS image for the RockPro64. It boots fine but I haven't tested much yet.

Image is available at:
https://download.opensuse.org/repositories/home:/patrikjakobsson:/rockpro64/images/
