### ISSUE TITLE
Which rockpro64 LXDE/other image does have sound output.

### ISSUE THREAD

**Issue by rahulsharma11** [ayufan-rock64/linux-build#380]
Hi, I am using rockpro64. And flashed Ubuntu18 LXDE Desktop image (build - 0.8.3-11.41)with pine-installer. Here i am able to hear sound from audio jack. But it seems 32 bit image and i am having trouble installing ComputeLibrary and other projects. So can you please verify which LXDE 64 bit ubuntu image does have sound output support for rockpro64? 
I have used "bionic lxde-rockpro64-0.8.0rc16-1136-arm64.img". But no sound is there.
Thanks.

**Comment by ayufan** [comment]
Change sound output.

**Comment by rahulsharma11** [comment]
Got this.
Thanks.
