### ISSUE TITLE
bionic-minimal-rock64: How to install and configure xorg?

### ISSUE THREAD

**Issue by matwey** [ayufan-rock64/linux-build#384]
Hello,

I've tried bionic-minimal-rock64-0.9.3 and bionic-minimal-rock64-0.8.3 on rock64 board, and I cannot figure out how to correctly install and configure xorg on this minimal image.

I use apt to install all required packaged including libmali-rk-utgard-450-r7p0 and use preconfigured glamour config.

In /var/log/X.org.log I see the following error:
```
[    60.272] (II) glamor: OpenGL accelerated X.org driver based.
[    60.275] (II) glamor: EGL version 1.4 Linux-r7p0-00rel0:
[    60.275] EGL_KHR_gl_renderbuffer_image required.
[    60.275] EGL_KHR_surfaceless_context required.
[    60.275] EGL_KHR_surfaceless_gles2 required.
[    60.276] (EE) modeset(0): Failed to create EGL context
[    60.276] (EE) modeset(0): glamor initialization failed
```

However, when I use bionic-lxde-rock64 image with preconfigured Xorg and LXDM, there is no such error, glamor is initialized successfully.

What could be the difference?

**Comment by ayufan** [comment]
There is install_desktop.sh that should install everything. Secondly, the
0.9.3 usage for that purpose is bad idea. It is unstable :$

**Comment by matwey** [comment]
Thanks. It seems that installing `libmali-rk-dev` fixes the things.
