### ISSUE TITLE
Disable debug console on serial 1 and enable it for serial communications

### ISSUE THREAD

**Issue by gnitzan** [ayufan-rock64/linux-build#387]
Hello,
I need to connect Pixhawk flight controller to Rockpro64 on serial pins. From what I read, serial is connected to debug console, can any one shed some light on how to remove the debug console and enable the pins for serial communication?
On RPI its simple as running raspi-config, is there anything like it in Rockpro64?
Thanks,
Gal

**Comment by gnitzan** [comment]
got answer somewhere

**Comment by qm3ster** [comment]
`sudo systemctl mask serial-getty@ttyS2` worked.
`disable` didn't, it would just come back upon reboot.
