### ISSUE TITLE
The network interface eth0 can not be configured and used

### ISSUE THREAD

**Issue by Mimuni** [ayufan-rock64/linux-build#39]
I would like to try the newer image, but I get the network interface not to work. This works until version 0.4.17 without problems. According to change log eth1 has been disabled since the release 0.5.1. Can it be that this is the gigabit card? In the previous release I always used eth1 and when I try to configure eth0 I received the same error message. 
Is it possible to reactivate eth1 temporary to check if it is?
Which log does it need for a better error search?

`ifconfig eth0 192.168.2.50` outputs the following:
```
stmmac_hw_setup:
DMA engine initialization failed
stmmac_open: HW setup failed
SIOCSIFFLAGS: Device or resource busy
```

**Comment by Mimuni** [comment]
Can someone tell me how I can temporarily re-enable the network interface eth1? What was changed for the switch off in version 0.5.1? In the Git I can not find the change.

**Comment by ayufan** [comment]
Mimuni: the 0.5.x misses patches for enabling internal-phy as I reverted
them as they were not fully stable. eth1 is being supported by mainline
kernel today.

**Comment by xalius** [comment]
eth1 is enabled by default now

**Comment by Averell7** [comment]
I have installed the audio POT boardm which  has a second ethernet port.
I have tried with Community Debian Stretch minimal (0.6) and community Bionic lxde 0.6) : there is no eth1. 
ifconfig eth1 192.168.1.5 returns : no such device 
What can I do to get a second ethernet port ?
