### ISSUE TITLE
How to enable bluetooth in OMV image?

### ISSUE THREAD

**Issue by brainstormi** [ayufan-rock64/linux-build#397]
I'm trying to get BT running in OMV image 0.9.x, unfortunately I can't get a hciX device. Running dmesg command I see:

[    1.484780] Bluetooth: Core ver 2.21
[    1.484843] Bluetooth: HCI device and connection manager initialized
[    1.484868] Bluetooth: HCI socket layer initialized
[    1.484891] Bluetooth: L2CAP socket layer initialized
[    1.484931] Bluetooth: SCO socket layer initialized
[    2.869635] Bluetooth: Virtual HCI driver ver 1.5
[    2.870196] Bluetooth: HCI UART driver ver 2.3
[    2.870621] Bluetooth: HCI UART protocol H4 registered
[    2.871088] Bluetooth: HCI UART protocol LL registered
[    2.871553] Bluetooth: HCI UART protocol ATH3K registered
[    3.005576] Bluetooth: RFCOMM socket layer initialized
[    3.006117] Bluetooth: RFCOMM ver 1.11
[    3.006513] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[    3.007069] Bluetooth: HIDP socket layer initialized
[    3.014613] [BT_RFKILL]: Enter rfkill_rk_init
[    3.015732] of_get_named_gpiod_flags: parsed 'uart_rts_gpios' property of node '/wireless-bluetooth[0]' - status (0)
[    3.015742] [BT_RFKILL]: bluetooth_platdata_parse_dt: get property: uart_rts_gpios = 83.
[    3.016501] of_get_named_gpiod_flags: can't parse 'BT,power_gpio' property of node '/wireless-bluetooth[0]'
[    3.016536] of_get_named_gpiod_flags: parsed 'BT,reset_gpio' property of node '/wireless-bluetooth[0]' - status (0)
[    3.016545] [BT_RFKILL]: bluetooth_platdata_parse_dt: get property: BT,reset_gpio = 9.
[    3.017307] of_get_named_gpiod_flags: parsed 'BT,wake_gpio' property of node '/wireless-bluetooth[0]' - status (0)
[    3.017315] [BT_RFKILL]: bluetooth_platdata_parse_dt: get property: BT,wake_gpio = 91.
[    3.018077] of_get_named_gpiod_flags: parsed 'BT,wake_host_irq' property of node '/wireless-bluetooth[0]' - status (0)
[    3.018085] [BT_RFKILL]: bluetooth_platdata_parse_dt: get property: BT,wake_host_irq = 4.
[    3.019189] [BT_RFKILL]: Request irq for bt wakeup host
[    3.019741] [BT_RFKILL]: ** disable irq
[    3.020277] [BT_RFKILL]: bt_default device registered. 

The output from 'rfkill list all': 
0: bt_default: Bluetooth
	Soft blocked: no
	Hard blocked: no

Curiously this last command doesn't list WIFI interface, which reports similar issues in dmesg output like bluetooth. Investigating a bit I saw some old threads that pointed bt was disabled to get PCIE working, but not sure if this is the case anymore. How could bluetooth get enabled?.

**Comment by ayufan** [comment]
Can you post more details what board do you use, what module do you use, etc?

**Comment by brainstormi** [comment]
Excuse me ayufan I just discovered it was my mistake reviewing the specs of my board, Rockpro64. I wrongly understood that it includes BT/WIFI modules, but taking a quick look to manufacturer page it seems it's an external module sold separately.
