### ISSUE TITLE
Kernel crash

### ISSUE THREAD

**Issue by Boia11** [ayufan-rock64/linux-build#398]
Hi @ayufan , my Rock64 crash during the night without reason, with last release [0.9.14](https://github.com/ayufan-rock64/linux-build/releases/tag/0.9.14).
I attach the kernel event log here: [kernel_crash_r0.9.14.txt](https://github.com/ayufan-rock64/linux-build/files/3612569/kernel_crash_r0.9.14.txt)

armbianmonitor -u (at start): http://ix.io/1V6k

after 11 min the server crash again: [kernel_crash_r0.9.14_bis.txt](https://github.com/ayufan-rock64/linux-build/files/3612580/kernel_crash_r0.9.14_bis.txt)

It's the same "virtual address 000002ac" look here : #278

**Comment by SmallAndSoft** [comment]
My Rock64_V2.0 with 4 GB of RAM crashes with the release 0.9.14 too when I try memory-intensive 7zip benchmark. The power is supplied by DC-DC step down converter set to 5.1V (works fine with other boards). The crashes I get are inconsistent, sometimes it is segfault, sometimes it is kernel panic.

**Comment by Boia11** [comment]
The problem is the 'uart' but was cause by a loose wires connect to pins 6, 8 and 10 but not attached to anything.

I removed those loose wires and the problem disappeared.
