### ISSUE TITLE
SSH first time login fails to change password

### ISSUE THREAD

**Issue by markus-seidl** [ayufan-rock64/linux-build#406]
### Problem:

* Flashing a sd card with etcher, using "bionic-minimal-rock64-0.9.14-1159-arm64.img.xz"
* Connecting network and power supply
* Trying to login on a rock64 v3

### What happens

```
WARNING: Your password has expired.
You must change your password now and login again!
Changing password for rock64.
(current) UNIX password:
passwd: Authentication token manipulation error
passwd: password unchanged
Connection to 192.168.178.54 closed.
```

### What has been tried
* Changing the power supply
* Changing the sd card
* Replacing the board

Nothing works

### What does work?

Using the image "bionic-minimal-rock64-0.8.3-1141-arm64.img.xz" (because I had that installed on my other rock64 some time ago).
I've updated and dist-upgraded the image without problems (which makes me believe, that the power supply and SD card is actually good)

**Comment by ayufan** [comment]
I tested that millions of times. It does work:

```
WARNING: Your password has expired.
You must change your password now and login again!
Changing password for rock64.
(current) UNIX password: <you have to type current password, which is: rock64 the same as for login>
```

Only after that you are asked to type a new password.

**Comment by markus-seidl** [comment]
I think I tried that around 10 times, to no avail. I'm also sure that I exactly did that.
To make sure that it's not a PEBKAC problem I'll try again in a few days, when I'm back home again.

**Comment by markus-seidl** [comment]
Sorry, it seems to be a power problem after all. Very weird...
