### ISSUE TITLE
Moving to a read-only fileaystem

### ISSUE THREAD

**Issue by Darkvater** [ayufan-rock64/linux-build#409]
Hi,

I am rewiring my rock64 running the latest ayufan 4.4-190 loosely following this guide https://www.domoticz.com/wiki/Setting_up_overlayFS_on_Raspberry_Pi

I am quite confused by the boot partition bit. Under /boot there is an /boot/extlinux and a /boot/efi/extlinux partition. /etc/fstab mounts label=BOOT to /boot/efi.

What do I change to mount /boot as to? /boot/efi/extlinux/extlinux.cmd or /boot/extlinux/extlinux.cmd or neither of them as I see /etc/default/extlinux is supposed to be updated so it survives upgrades? However there is only an APPEND option there, so I presume I cannot change the "rw" to "to".
Any help would be appreciated

I have the boot partition on the emmc, this is what fdisk says:
```
root@rock64:~# fdisk -l
Disk /dev/ram0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/mtdblock0: 4 MiB, 4128768 bytes, 8064 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mmcblk0: 14.5 GiB, 15518924800 bytes, 30310400 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: C989EB79-6CD9-43DA-9AB4-9E11956FD426

Device          Start     End Sectors  Size Type
/dev/mmcblk0p1     64    8063    8000  3.9M Linux filesystem
/dev/mmcblk0p2   8064    8191     128   64K Linux filesystem
/dev/mmcblk0p3   8192   16383    8192    4M Linux filesystem
/dev/mmcblk0p4  16384   24575    8192    4M Linux filesystem
/dev/mmcblk0p5  24576   32767    8192    4M Linux filesystem
/dev/mmcblk0p6  32768  262143  229376  112M Microsoft basic data
/dev/mmcblk0p7 262144 4186111 3923968  1.9G Linux filesystem

Disk /dev/mmcblk0boot1: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes                                         

Disk /dev/mmcblk0boot0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

**Comment by ayufan** [comment]
We do not use `/boot` anymore. It is a legacy thing that should go away.

You can force `ro` by:
1. edit `/etc/default/extlinux` and append `ro`
2. run `update-extlinux.sh`,
3. you could modify `/etc/fstab` to setup overlay if needed,
4. reboot

**Comment by Darkvater** [comment]
Thanks ayufan, I tried that before but now the extlinux options include both "rw" _and_ "ro", I will have to check when I'm home and reboot which of the flags take precedence or whether the system refuses to boot at all.

If you are saying /boot is not used anymore, should just remove the whole line "LABEL=boot      /boot/efi       vfat..." from /etc/fstab?

**Comment by Darkvater** [comment]
Thanks ayufan, works now (in ro). Didn't solve my instability issues but this issue is resolved.
