### ISSUE TITLE
standby led cannot be controlled in 0.9.14 Rock64

### ISSUE THREAD

**Issue by tanus10** [ayufan-rock64/linux-build#410]
1. for RED LED
```sh -c "echo '0' > /sys/devices/platform/leds/leds/standby-led/brightness"```
does not work. It used to. Hence I report this as an issue.

2. for WHITE LED
```sh -c "echo '0' > /sys/devices/platform/leds/leds/power-led/brightness"```
does not work, because there is no 'power-led' directory.
It must have been changed to 'work-led'
and 
```sh -c "echo '0' > /sys/devices/platform/leds/leds/work-led/brightness"```
works. It turns off the WHITE LED.

I am using stretch-openmediavault-rock64-0.9.14-1159-arm64.img.xz

**Comment by ayufan** [comment]
This is supported as part of 0.10.x.
