### ISSUE TITLE
Bionic minimal for PineBook Pro

### ISSUE THREAD

**Issue by futurejones** [ayufan-rock64/linux-build#413]
Release 0.9.0 contained a 64bit release for the PineBook Pro
https://github.com/ayufan-rock64/linux-build/releases/download/0.9.0/bionic-minimal-pinebookpro-0.9.0-1142-arm64.img.xz
Is there any reason why this is not available on the later releases?
I have tried the `Rockpro64` builds but they do not work.

**Comment by ayufan** [comment]
I decided that minimal does not make a lot of sense for PBPro. It is currently being build as part of pre-releases 0.10.x.
