### ISSUE TITLE
Sound on mainline linux 5.4.6

### ISSUE THREAD

**Issue by mbakhterev** [ayufan-rock64/linux-build#415]
Hi. I am running ArchLinux with Linux 5.4.6. It seems, that DTB for rock64 describes sound devices incorrectly. Unfortunately i have no experience to port DTB from ayufan kernel sources. So, it would be nice to add some instructions about online editing sound configuration for rock64 to the

https://github.com/ayufan-rock64/linux-build/blob/master/recipes/additional-devices.md

- Respectfully, Mike.

**Comment by ayufan** [comment]
Please re-test with mainline kernel. It vastly improves support.
