### ISSUE TITLE
**Notice to SBC users** OMV4 on SBC's is no longer supported.

### ISSUE THREAD

**Issue by hemertje** [ayufan-rock64/linux-build#418]
Hi Ayufan,

In this forumlink we read the following:

https://forum.openmediavault.org/index.php/Thread/27073-New-User-Guide-Getting-Started-with-Openmediavault-4-5/

**Notice to SBC users** OMV4 on SBC's is no longer supported.
OMV5, for SBC's, should be build in accordance with one of the guides in this -> post.**

https://forum.openmediavault.org/index.php/Thread/28789-Installing-OMV5-on-Raspberry-PI-s-Armbian-SBC-s-i386-32-bit-platforms/?postID=214407#post214407

I want to use OMV on my Pine64 NASCase with a ROCKPro 64 4GB SBC.
Can you update your OMV-github to OMV5?

**Comment by ayufan** [comment]
Yes, I will update to OMV5. I was waiting for having OMV4 stable, there's even a build of OMV5 already in wild :)

**Comment by hemertje** [comment]
Good to hear!
Do you have in mind when to expect your OMV5 builds?

**Comment by ayufan** [comment]
By end of Feb

**Comment by hemertje** [comment]
how does the existing OMV5 run?
ready for daily usage?
do you have the url for me?

**Comment by hemertje** [comment]
with OMV4 I have a problem creating a File System on the HDD, related to OMV4 you think?

https://forum.openmediavault.org/index.php/Thread/30666-Create-filesystem-error-communication-failure/

**Comment by ayufan** [comment]
Unlikely

**Comment by hemertje** [comment]
> how does the existing OMV5 run?
> ready for daily usage?
> do you have the url for me so I can try it?

do you have an answer for above? thx!

**Comment by hyptechdev2015** [comment]
> By end of Feb
> […](#)

Cant wait to test out

**Comment by KorribanMaster** [comment]
@ayufan  Have you made any progress on the subject?

**Comment by KorribanMaster** [comment]
> with OMV4 I have a problem creating a File System on the HDD, related to OMV4 you think?
> 
> https://forum.openmediavault.org/index.php/Thread/30666-Create-filesystem-error-communication-failure/

Hey I ran into the same error and doing the same while using @ayufan mainline kernel (5.3) fixed the issue but resulted in very long boot times. I fixed that by installing the recent v2020-ci u-boot from @sigmaris ( https://github.com/sigmaris/u-boot/releases/tag/v2020.01-ci ). Seems to run nice now

**Comment by ayufan** [comment]
The OMV5 is part of pre-releases and uses mainline u-boot.
