### ISSUE TITLE
Differences in rk3399-rockpro64.dts across upstream mainline kernel

### ISSUE THREAD

**Issue by pfremm** [ayufan-rock64/linux-build#419]
I was curious if it's detailed anywhere what the specific differences still exist in rk3399-rockpro64.dts?  Is this specifically for the fan and SPI?

Comparing: https://github.com/torvalds/linux/blob/v5.5/arch/arm64/boot/dts/rockchip/rk3399-rockpro64.dts

to 

https://github.com/ayufan-rock64/linux-mainline-kernel/blob/5.4.0-rc1-1120-ayufan/arch/arm64/boot/dts/rockchip/rk3399-rockpro64.dts

**Comment by ayufan** [comment]
The most of diff is removed now.
