### ISSUE TITLE
Unable to come back from screensaver on rock64-0.5.9-104

### ISSUE THREAD

**Issue by rock64-linux** [ayufan-rock64/linux-build#42]
During my testing on some images for rock64-0.5.9-104 (e.g. xenial-i3 and xenial-minimal), when idle too long and went into screensaver mode, I was unable to bring it back on by moving my mouse and keyboard input. It came back on when I unplug and plug back the hdmi cable.

**Comment by ayufan** [comment]
It does not seem to be an issue any longer
