### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by DmitryMyadzelets** [ayufan-rock64/linux-build#424]
There is no sound on Rock64 v2 on the [pre-release 0.10.10](https://github.com/ayufan-rock64/linux-build/releases/tag/0.10.10)
```bash
dmesg | grep sound
[    4.028924]   No soundcards found.
```
```
uname -a
Linux rock64 5.6.0-1134-ayufan-g652fb97d87eb 
#ayufan SMP Thu Apr 9 22:26:01 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```
Though it works on the [stable minimal baster 0.9.14](https://github.com/ayufan-rock64/linux-build/releases/download/0.9.14/buster-minimal-rock64-0.9.14-1159-arm64.img.xz)

**Comment by ayufan** [comment]
It is pre release. It is supposed to not work :)
