### ISSUE TITLE
Slow USB3.0 HDD speed

### ISSUE THREAD

**Issue by bcanterac** [ayufan-rock64/linux-build#449]
Hello, I have a rock64 in which I have installed stable OMV image ([https://github.com/ayufan-rock64/linux-build/releases/download/0.9.14/stretch-openmediavault-rock64-0.9.14-1159-armhf.img.xz](url).

I am willing to use my Seagate Expansion Desk drive (8TB) for samba shares, when I connect my drive directly to my desktop PC, I can read/write at 100MBps or more, but in rock64 it drops to 20-30MBps write and 30-40 read speeds.

I tried installing armbian and blacklisting UAS driver, which made me able to have 120MBps read speeds. Maybe there are problems with UAS driver in OMV image?

To reproduce, hook up a USB3.0 Seagate external HDD and test read/write speeds of OMV images

**Comment by JulianGro** [comment]
External Seagate drives have been known to be buggy for years. If it's a fairly new one, I would assume that there might be workarounds missing from the Kernel. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/usb/storage/unusual_uas.h?h=v5.10.1
Personally I have not tested USB3.0 storage on the Rock64, so I cannot say if there is any devices that run faster.

**Comment by bcanterac** [comment]
I found the reason, it was that the disk has NTFS partitions, and you must use "-o big_writes" option when mounting them.
Using it enables the rock64 to get all the performance out of it's USB3 port :+1:
