### ISSUE TITLE
USB OTG (Mass Storage Gadget)

### ISSUE THREAD

**Issue by motla** [ayufan-rock64/linux-build#468]
Hi !!

First thanks a lot for your work on this project, your builds work very nicely.
I use 0.9.14 on Rock64 and I would like to use the USB OTG capability, you marked it working on the [compatibility list](https://docs.google.com/spreadsheets/d/1pCqJg0VSzvihUOoxCOq3wt5JeGB4iApAyBBfc_BGv2A/edit#gid=1516519590).

I'm trying to make a USB Mass Storage Gadget like stated in [this guide](http://www.linux-usb.org/gadget/file_storage.html) using:
```
# modprobe g_mass_storage file=/root/data/backing_file
```
However it returns:
```
modprobe: FATAL: Module g_mass_storage not found in directory /lib/modules/4.4.190-1233-rockchip-ayufan-gd3f1be0ed310
```
Apparently the g_mass_storage module [is not compiled as part of default kernel configuration](https://linux-sunxi.org/USB_Gadget/Mass_storage).

So I wonder how you use USB OTG in your build? (I will push a guide if I can get it to work)

Thanks!

**Comment by ayufan** [comment]
I think it is, but it is no longer `g_mass_storage`, but rather: https://github.com/ayufan-rock64/linux-package/blob/master/root/usr/local/sbin/install_gadget#L33.

To use USB OTG, you can checkout those:

- https://github.com/ayufan-rock64/linux-package/blob/master/root-rock64/usr/local/sbin/rock64_enable_eth_gadget.sh
- https://github.com/ayufan-rock64/linux-package/blob/master/root/usr/local/sbin/install_gadget
- Theoretically, it should be enough to change rock64_enable_eth_gadget.sh accordingly
-

**Comment by motla** [comment]
@ayufan many thanks for your help!
You're using ConfigFs indeed.
After messing around for hours trying to understand why it didn't work, it was assigning OTG to the USB3.0 port instead of the dedicated USB2.0 OTG port of the Rock64... 😁 
We're almost there. Any idea how we can redirect the UDC to the USB2.0 OTG port ?
(I would like to use USB3.0 for an external drive)

**Comment by ayufan** [comment]
Hmm. Strange. It should work.

> We're almost there. Any idea how we can redirect the UDC to the USB2.0 OTG port ?

Can you check which DTS node is updated, maybe this is culprit?

**Comment by motla** [comment]
Sure, here are the details:
#### Shell script made from your example + [this doc](http://trac.gateworks.com/wiki/linux/OTG#ConfigFs) example
```bash
#!/bin/bash

set -xe

# load libcomposite module
modprobe libcomposite

# enable peripheral mode
enable_dtoverlay dwc3_peripheral usb@ff600000/dwc3@ff600000 okay 'dr_mode="peripheral"'

# reload dwc3
echo ff600000.dwc3 > /sys/bus/platform/drivers/dwc3/unbind
echo ff600000.dwc3 > /sys/bus/platform/drivers/dwc3/bind

# set drive to use with mass storage gadget
mkdir -p /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0
echo /dev/mmcblk1p6 > /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0/lun.0/file

# install and activate mass storage gadget
install_gadget NetworkHD ff600000.dwc3 mass_storage
```

#### USB DTS nodes listed at `/proc/device-tree`
```
usb3-phy@ff470000
usb@ff580000
usb@ff5c0000
usb@ff5d0000
usb@ff600000
```

#### Syslog
```
just after running the script:
Jun 02 20:45:04 rock64 kernel: xhci-hcd xhci-hcd.10.auto: remove, state 1
Jun 02 20:45:04 rock64 kernel: usb usb5: USB disconnect, device number 1
Jun 02 20:45:04 rock64 kernel: xhci-hcd xhci-hcd.10.auto: USB bus 5 deregistered
Jun 02 20:45:04 rock64 kernel: xhci-hcd xhci-hcd.10.auto: remove, state 1
Jun 02 20:45:04 rock64 kernel: usb usb4: USB disconnect, device number 1
Jun 02 20:45:04 rock64 kernel: xhci-hcd xhci-hcd.10.auto: USB bus 4 deregistered
Jun 02 20:45:04 rock64 kernel: phy phy-ff470000.usb3-phy.2: u3phy u2 power off
Jun 02 20:45:04 rock64 kernel: phy phy-ff470000.usb3-phy.3: u3phy u3 power off
Jun 02 20:45:04 rock64 kernel: phy phy-ff470000.usb3-phy.2: u3phy u2 power on
Jun 02 20:45:04 rock64 kernel: phy phy-ff470000.usb3-phy.3: u3phy u3 power on
Jun 02 20:45:04 rock64 kernel: Mass Storage Function, version: 2009/09/11
Jun 02 20:45:04 rock64 kernel: LUN: removable file: (no medium)

just after connecting USB3 to a host:
Jun 02 20:46:55 rock64 kernel: android_work: did not send uevent (0 0           (null))
Jun 02 20:46:55 rock64 kernel: android_work: sent uevent USB_STATE=CONNECTED
Jun 02 20:46:55 rock64 kernel: configfs-gadget gadget: super-speed config #1: c
Jun 02 20:46:55 rock64 kernel: android_work: sent uevent USB_STATE=CONFIGURED
```

Mass storage OTG works fine on USB3.

**Comment by gusarg81** [comment]
Hi,

Hey @ayufan: can you ever care to respond at least issues like #463 ?

Thanks.

**Comment by motla** [comment]
Ok I managed to get it work on port USB 2.0 OTG (it is device `usb@ff580000`, we can check that running `usb-devices`).
For USB 2.0 we have to use `dwc2` instead of `dwc3`.

Here is the script:
```bash
#!/bin/bash

set -xe

# enable peripheral mode
enable_dtoverlay dwc2_peripheral usb@ff580000 okay 'dr_mode="peripheral"'

# reload dwc2
echo ff580000.usb > /sys/bus/platform/drivers/dwc2/unbind
echo ff580000.usb > /sys/bus/platform/drivers/dwc2/bind

# set the drive to use with mass storage gadget
mkdir -p /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0
echo /dev/sda3 > /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0/lun.0/file

# install and activate mass storage gadget
install_gadget my_usb_drive_name ff580000.usb mass_storage
```

You need to change `/dev/sda3` to the disk partition you want to use as a mass storage.
It can be for example a partition of a USB drive that is plugged into the USB 3.0 port.

:warning: The USB host will not expect to see any changes in the mass storage other than the ones it makes.
> Extraneous changes are liable to corrupt the filesystem and may even crash the host. Only one system (normally, the USB host) may write to the backing storage, and if one system is writing that data, no other should be reading it. The only safe way to share the backing storage between the host and the gadget's operating system at the same time is to make it read-only on both sides. [linux-usb.org](http://www.linux-usb.org/gadget/file_storage.html)

As a result, while it's technically not impossible, it's hopeless to simultaneously mount/share the drive on a network, and use it via USB.

**Comment by motla** [comment]
(uninstall script:)

```bash
#!/bin/bash

set -x

# disable peripheral mode
disable_dtoverlay dwc2_peripheral

# reload dwc2
echo ff580000.usb > /sys/bus/platform/drivers/dwc2/unbind
echo ff580000.usb > /sys/bus/platform/drivers/dwc2/bind

# uninstall gadget
uninstall_gadgets
```
