### ISSUE TITLE
Rock64 minimal 64bit v0.9.14: apt update fails with Connection failed

### ISSUE THREAD

**Issue by Kosssma** [ayufan-rock64/linux-build#472]
Is http://deb.ayufan.eu/orgs/ayufan-rock64 online or still valid?
I get Connection failure during apt update

```
W: Failed to fetch http://deb.ayufan.eu/orgs/ayufan-rock64/releases/InRelease  Connection failed [IP: 2606:4700:3033::6815:575 80]
```

**Comment by ayufan** [comment]
Should be. But i might have broken something recently :)

**Comment by ayufan** [comment]
Appears to be working for me.

**Comment by ayufan** [comment]
OK. I fixed one thing (problem with outbound internet connection).

**Comment by Kosssma** [comment]
thanks it works now
