### ISSUE TITLE
build with DKMS/SPL?

### ISSUE THREAD

**Issue by digitalsanity** [ayufan-rock64/linux-build#48]
Could you build with DKMS/SPL enabled?  So we could enable e.g. ZFS via the zfs-dkms package in backports contrib?

**Comment by ayufan** [comment]
What needs to be enabled. AFAIK DKMS works at least for me

**Comment by digitalsanity** [comment]
Sorry -- you're correct, I think we're good here.  It looks like I am seeing an issue possibly related to CONFIG_USER_NS with SPL/ZFS that is causing trouble here.

error: incompatible types when assigning to type 'gid_t {aka unsigned int}' from type 'kgid_t {aka struct <anonymous>}'

error: incompatible types when assigning to type 'kgid_t {aka struct <anonymous>}' from type 'gid_t {aka unsigned int}'
   GROUP_AT(gi, i) = tmp_gid;

**Comment by digitalsanity** [comment]
FYI -- do not want to reopen this, but if anyone else is having issues with ZFS, you can follow/find a temporary fix here- https://github.com/zfsonlinux/spl/issues/653#issuecomment-333973785

**Comment by icicimov** [comment]
@digitalsanity  I left a comment in #653 too, spl-dkms and zfs-dkms fail to install for me too on rock64, both failing on `./configure` with:

```
checking kernel source version... 4.4.132-1075-rockchip-ayufan-ga83beded8524
checking kernel file name for module symbols... Module.symvers
checking whether modules can be built... no
configure: error: *** Unable to build an empty module.
```
As mentioned in that case too, when installed from packages all looks fine:
```
root@rock64:/tmp# dkms status
spl, 0.7.9: added
zfs, 0.7.9: added
```
and:
```
root@rock64:/tmp# dpkg -l | grep dkms        
ii  dkms                                                            2.3-2                                    all          Dynamic Kernel Module Support Framework
ii  spl-dkms                                                        0.7.9-3~bpo9+1                           all          Solaris Porting Layer kernel modules for Linux
ii  zfs-dkms                                                        0.7.9-3~bpo9+1                           all          OpenZFS filesystem kernel modules for Linux
```
however the modules can not be loaded since they are actually missing from `/lib/modules/4.4.132-1075-rockchip-ayufan-ga83beded8524/` directory. Any ideas?

**Comment by icicimov** [comment]
If this helps:
```
make: Entering directory '/usr/src/linux-headers-4.4.132-1075-rockchip-ayufan-ga83beded8524'
  CC [M]  /tmp/spl-0.7.9/build/conftest.o
gcc: error: unrecognized command line option '-mgeneral-regs-only'
gcc: error: unrecognized command line option '-mcmodel=large'
scripts/Makefile.build:283: recipe for target '/tmp/spl-0.7.9/build/conftest.o' failed
make[1]: *** [/tmp/spl-0.7.9/build/conftest.o] Error 1
Makefile:1471: recipe for target '_module_/tmp/spl-0.7.9/build' failed
make: *** [_module_/tmp/spl-0.7.9/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.4.132-1075-rockchip-ayufan-ga83beded8524'
```

**Comment by digitalsanity** [comment]
I think you are missing the standard build packages -- install those and
try again?

**Comment by icicimov** [comment]
Hi @digitalsanity I decided to give up on the ovm image and went with the bionic arm64 one. This time all worked fine:

```
root@rock64:~# date
Sun Aug  5 05:25:22 UTC 2018
root@rock64:~# dkms status
spl, 0.7.5, 4.4.132-1075-rockchip-ayufan-ga83beded8524, aarch64: installed
zfs, 0.7.5, 4.4.132-1075-rockchip-ayufan-ga83beded8524, aarch64: installed
root@rock64:~# uname -a
Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```
Additional to following you instructions I had to apply a patch as described in this thread https://github.com/armbian/build/issues/74 to make `make scripts` work.

**Comment by digitalsanity** [comment]
There is an issue with arch/arm/include not being packaged with linux header debs for arm64 kernels.  arch/arm64/include/asm/opcodes.h tries to include arch/arm/include/asm/opcodes.h, which doesn't exist (because it is an arm64 kernel afterall..)

See more:

https://github.com/ayufan-rock64/linux-build/issues/252#issuecomment-588348845
