### ISSUE TITLE
Chromium graphically slow, invisible in fullscreen

### ISSUE THREAD

**Issue by TheGuywithTheHat** [ayufan-rock64/linux-build#52]
I have a ROCK64 that I installed an Ubuntu MATE image on (specifically http://files.pine64.org/os/ROCK64/ubuntu/xenial-mate-rock64-0.5.10-118-arm64_sd2emmc.img.xz). The issue I'm having is with graphics stuff when running chromium. If I open up a new page, switch tabs, click on a link, etc, it takes about half a second for it to scan down the application, updating the lines of pixels seemingly one-by-one.

Fullscreen, though, is where things get really weird. If I start chromium in fullscreen (`--start-fullscreen` or `--kiosk`), the window doesn't render, and instead just displays the pixels that were on-screen before starting. I know it is successfully loading pages though, because if I click and drag, the translucent thing that visually represents what I'm dragging still shows up. (Like if you select this text and try to drag it, you can see the text you're dragging). However, the issue isn't with fullscreen, it's with _starting in_ fullscreen. If I open chromuim normally and then F11 into fullscreen, it works fine. If I start in fullscreen and then F11 out of fullscreen, the windows remains invisible. Complicating this even further, if I minimize an invisible window, unminimizing it makes it reappear normally.

I'm trying to get an [Electron](https://electron.atom.io/) application to start in kiosk mode, so for now a workaround could be starting windowed and then programmatically fullscreening on startup, but ideally I don't want to have to do that.

If it helps, here's the output of running chromium and electron (the output is the same regardless of starting in fullscreen or not).

```
$ chromium
[2850:2879:1012/180853.034888:ERROR:zygote_host_impl_linux.cc(277)] Failed to adjust OOM score of renderer with pid 3042: Permission denied
[2967:2967:1012/180853.381147:ERROR:gl_surface_egl.cc(232)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
[2967:2967:1012/180853.460263:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
[2967:2967:1012/180853.498235:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[2967:2967:1012/180853.586727:ERROR:gl_surface_egl.cc(232)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
[2850:2879:1012/180858.909581:ERROR:zygote_host_impl_linux.cc(277)] Failed to adjust OOM score of renderer with pid 3214: Permission denied
^C
$ ./node_modules/.bin/electron .
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: unable to load driver: rockchip_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: rockchip
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: unable to load driver: rockchip_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: rockchip
```

Any idea what might be going on, or do you think this is an issue on chromium's end?

**Comment by StuartIanNaylor** [comment]
If you do an apt-cache search for rockchip there is a libmali* driver for the rk3328.

Never managed to get it going just seems to crash x with a seg fault.

**Comment by xalius** [comment]
The latest pre-release images with new X configuration and LXDE should fix this.
