### ISSUE TITLE
Add drbd module to kernel build

### ISSUE THREAD

**Issue by ocastan** [ayufan-rock64/linux-build#54]
I want to use Rock64 OpenMediaVault as home NAS with HA. It looks like drbd is the easiest way to do so. Can you add it to the kernel build ?
Thanks in advance.

**Comment by ocastan** [comment]
One more remark: a similar request was made to armbian and accepted a few months ago.
[https://github.com/armbian/build/issues/639](https://github.com/armbian/build/issues/639)

**Comment by xalius** [comment]
The config options have been added, should be in the next release/pre-release.
