### ISSUE TITLE
Kernel error

### ISSUE THREAD

**Issue by Boia11** [ayufan-rock64/linux-build#55]
Hi, when I try to upload big file with Nextcloud (Apache+PHP5) the Rock64 crash with this error:
`
Message from syslogd@Rock64 at Nov  3 00:54:16 ...
 kernel:[ 1080.465944] Kernel panic - not syncing: hung_task: blocked tasks

Message from syslogd@Rock64 at Nov  3 00:54:16 ...
 kernel:[ 1080.939145] Kernel Offset: disabled

Message from syslogd@Rock64 at Nov  3 00:54:16 ...
 kernel:[ 1080.941632] Memory Limit: none
`

This is the complete SysLog of session from boot to crash: [https://pastebin.com/AfUvT4WB](https://pastebin.com/AfUvT4WB)
PHP is set to keep 16G of files with maximum_execution_time = 3600
What's the problem?

**Comment by Boia11** [comment]
Look here for try fix.....https://bugzilla.redhat.com/show_bug.cgi?id=717633 similar issue

**Comment by Boia11** [comment]
Yes...It's a bug with USB 3.0 (xhci-hcd) because I try to move HDD from USB 3.0 to USB 2.0 and work perfectly.
Fix it please

**Comment by xalius** [comment]
This should be fixed in recent kernels with increased coherent pool size.
