### ISSUE TITLE
Update new kernel

### ISSUE THREAD

**Issue by dalmatele** [ayufan-rock64/linux-build#57]
The mainline kernel from Linux rockchip is updated.
https://github.com/rockchip-linux/kernel/commit/c0aed970b71d8160ccc7fc2e4420c22a3cef4a6f
Please build new image with that.
They've fixed some problem with VPU encode/decode.
Thanks.

**Comment by xalius** [comment]
Ayufan rebases to upstream from time to time, so this should be merged.
