### ISSUE TITLE
usb3

### ISSUE THREAD

**Issue by shawnl** [ayufan-rock64/linux-build#61]
my SSD works when I plug it in to the usb2 ports, but not the usb3 ports. on the 4.13 kernel. usb3 works sometimes on the 4.4 kernel:
(4.4)
Dec 03 01:51:32 rock64 kernel: xhci-hcd xhci-hcd.8.auto: Cannot set link state.
Dec 03 01:51:32 rock64 kernel: usb usb5-port1: cannot disable (err = -32)
Dec 03 01:51:34 rock64 kernel: xhci-hcd xhci-hcd.8.auto: Cannot set link state.
Dec 03 01:51:34 rock64 kernel: usb usb5-port1: cannot disable (err = -32)

**Comment by itdaniher** [comment]
@shawnl I'm assuming you figured out usb3 on mainline? Is this working?

**Comment by shawnl** [comment]
My ssd was faulty.

**Comment by itdaniher** [comment]
cool, thanks!
