### ISSUE TITLE
kernel 4.4.93 build errors

### ISSUE THREAD

**Issue by jaccol** [ayufan-rock64/linux-build#65]
I tried building the latest kernel from https://github.com/ayufan-rock64/linux-kernel
(commit 2664498acfb495534ad51b8ea488ef276e35195 from December 4)

$ make rockchip_linux_defconfig
$ make Image 

ends in this error:

```
  CC      drivers/dma/pl330.o
drivers/dma/pl330.c: In function ‘_loop_cyclic’:
drivers/dma/pl330.c:1260:19: error: ‘struct dma_pl330_desc’ has no member named ‘num_periods’
  lcnt0 = pxs->desc->num_periods;
                   ^
drivers/dma/pl330.c:1302:11: error: ‘struct pl330_dmac’ has no member named ‘peripherals_req_type’
  if (pl330->peripherals_req_type == BURST) {
           ^
drivers/dma/pl330.c:1306:3: error: implicit declaration of function ‘BYTE_MOD_BURST_LEN’ [-Werror=implicit-function-declaration]
   c = BYTE_MOD_BURST_LEN(x->bytes, pxs->ccr);
   ^
cc1: some warnings being treated as errors
make[2]: *** [drivers/dma/pl330.o] Error 1
make[1]: *** [drivers/dma] Error 2
make: *** [drivers] Error 2
```

I build this on CentOS 7 on a rock64. 

version 4.4.77 (061663ba21ee96d4dd766389b208a67ee6dd37d6, October 30) builds and boots just fine. 

Jacco

PS. the linux-kernel repo has no option to report issues

**Comment by ayufan** [comment]
Thanks. I will check that. I'm in process of rebasing changes, and I saw
this error already.

**Comment by ayufan** [comment]
Actually, I pushed a fix for that just now ;)

**Comment by itdaniher** [comment]
Fought with this issue for awhile before giving up defeated.

**Comment by jaccol** [comment]
that was the quickest bugfix I've ever seen :)

It now builds. It'll take me a little more time to verify if it actually runs

**Comment by jaccol** [comment]
For me this does build, but it does not result in a bootable kernel. I don't have a serial output right now, so detailed debugging is difficult.

Has anybody made a working kernel for rock64 from this repo?

**Comment by itdaniher** [comment]
@jaccol I have not, but I've been trying...

**Comment by ayufan** [comment]
Fixed.
