### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by mbarela82** [ayufan-rock64/linux-build#68]
I installed the current mate build for rock64 and the screen resolution is set on 800 x 600 and there is no way to change it.

**Comment by Rar9** [comment]
I got the same problem with my Monitor.  Try a TV for the time being till they fix the EDID  detection.

I tried xrandx but without any luck.

**Comment by evilbunny2008** [comment]
I had the same problem with a monitor and fixed it by putting:

[code]drm_kms_helper.edid_firmware=edid/1920x1080.bin[/code]

in the /boot/efi/extlinux/extlinux.conf file, at the end of the append line, there are other modes supported such as 1600x1200.bin

https://wiki.archlinux.org/index.php/kernel_mode_setting#Forcing_modes_and_EDID

This is the only way I could get 0.6.x kernels to show on my monitor.

**Comment by xalius** [comment]
As evilbunny said, force EDID if the autodetection does not work for you.
