### ISSUE TITLE
OS does not start up even

### ISSUE THREAD

**Issue by takuhara** [ayufan-rock64/linux-build#69]
OS does not start up even

xenial-mate-rock64-0.5.10-118-arm64.img.xz

**Comment by texasbruce** [comment]
It does for me.

**Comment by takuhara** [comment]
I'm wrong.

OK
xenial-mate-rock64-0.5.15-136-arm64.img.xz
xenial-mate-rock64-0.5.10-118-arm64.img.xz

NG
xenial-mate-rock64-0.6.1-141-arm64.img.xz
xenial-mate-rock64-0.6.0-140-arm64.img.xz

**Comment by jaccol** [comment]
the prereleases 0.6.x also don't work for me

**Comment by ayufan** [comment]
This is expected. 0.6.x is not yet stable.
