### ISSUE TITLE
devfreq ff3000000.gpu couldn't update frequency transition information

### ISSUE THREAD

**Issue by mrfixit3000** [ayufan-rock64/linux-build#70]
Not getting display on most HDMI devices. On the one device I do have that it does work on, when using emulationstation, the output will jump back and forth between HDMI and DVI (in the same resolution) - and I see this error pop up sometimes, which I assume is related.
  devfreq ff3000000.gpu couldn't update frequency transition information

**Comment by not7cd** [comment]
Hey, @mrfixit3000. How this was fixed?

**Comment by Wufus** [comment]
The main rule of anyone seeking help - if you solved the problem yourself, take the solution with you to the grave
