### ISSUE TITLE
Upgraded from 0.6.1 to 0.6.5 doesn't finish booting anymore

### ISSUE THREAD

**Issue by xorinox** [ayufan-rock64/linux-build#73]
Hi, I used apt update/upgrade to update from 0.6.1 to 0.6.5 now the board doesn't finish booting anymore. I was already using an emmc 32GB card. I have attached a screenshot.

Errors reported are related to the emmc card:
- mmc0: tuning execution failed
- mmc0: error -5 whilst initializing mmc card

https://github.com/ayufan-rock64/linux-build/releases/tag/0.6.5

![20171222_124413](https://user-images.githubusercontent.com/5403531/34307618-f3c5af8c-e716-11e7-918e-74c822f35b55.jpg)

**Comment by denix0** [comment]
Me too!

**Comment by denix0** [comment]
Tried 0.6.3 - seems to have the same issue.

**Comment by lolyinseo** [comment]
The same problem

**Comment by denix0** [comment]
Hmm, had to downgrade all the way back to 0.5.15...

**Comment by xorinox** [comment]
Same here, now the board works again with the emmc. Unlikely this is related to a hardware issue.

**Comment by ayufan** [comment]
Fixed: https://github.com/ayufan-rock64/linux-kernel/commit/95368b4b832d932f75a1813a056805b84af9cff6
