### ISSUE TITLE
not able to install docker

### ISSUE THREAD

**Issue by xnathanh** [ayufan-rock64/linux-build#74]
system: rock64 4gb +64gb sd-card

i follow docker official install guide to install docker on 
1.jessie-minimal-rock64-0.6.5-152-arm64.img.xz
2.xenial-mate-rock64-0.6.5-152-arm64.img.xz
3.stretch-minimal-rock64-0.6.5-152-arm64.img.xz
all get same error: "Unable to locate package docker-ce"
```
root@rock64:~# uname -a
Linux rock64 4.4.77-rockchip-ayufan-104 #1 SMP Sun Sep 10 21:24:43 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
root@rock64:~# apt-get install docker-ce
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-ce
```

**Comment by ayufan** [comment]
Docker does not release officially packages for arm64. You can run it on
arm64, but you have to configure it manually. It is auto on armhf.

**Comment by xnathanh** [comment]
@ayufan here is the deb https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/

**Comment by xnathanh** [comment]
@ayufan 

new update:docker now working on xenial-mate-rock64-0.6.5-152-arm64.img.xz
here is way:

```
mkdir /home/rock64/download

wget https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/arm64/docker-ce_17.09.1~ce-0~ubuntu_arm64.deb

sudo dpkg -i docker-ce_17.09.1~ce-0~ubuntu_arm64.deb

```
