### ISSUE TITLE
kernel panics emmc rrdcached

### ISSUE THREAD

**Issue by dahubinno** [ayufan-rock64/linux-build#75]
Hi, I received a fresh Rock64 2 GB with the emmc from Pine64-shop.
I'm getting strange kernel panics when using the omv-0.5.15-sd-to-emmc-image.
Please see the attached outputs in dmesg.
[kernel panic2.pdf](https://github.com/ayufan-rock64/linux-build/files/1594462/kernel.panic2.pdf)
[stack trace.pdf](https://github.com/ayufan-rock64/linux-build/files/1594463/stack.trace.pdf)

After install, I didn't do much:
1. start omv, changed admin password, added new user, generated self-signed certificate according to the manual
2. switched language support to DE_UTF8 and timezone Europe/Berlin
3. apt-get update + apt-get upgrade

At first, I thought this would be a thermal or hardware issue, as it didn't occur regularly.
However, in the syslog messages, I saw that the rrdache-demon was writing tons of output messages to my syslog-file.
Having stopped the rrdcache-demon, the problems ceased to occur.

I wanted to share this - maybe this is already fixed in future releases.

Best regards
David

**Comment by xalius** [comment]
This is fixed in recent OMV pre-releases.
