### ISSUE TITLE
utf8 is not a recommended charset for FAT

### ISSUE THREAD

**Issue by dahubinno** [ayufan-rock64/linux-build#76]
Hi, I'm getting error messages having switched to utf8 charset.
The dirty flag is set which is quite annoying. 
I use the 0.5.15 omv-emmc image.

FAT-fs (mmcblk0p6): utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
[   10.721961] FAT-fs (mmcblk0p6): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.

According to my google searches, this may be fixed using the utf8 mount option. However, the fs cannot be found in fstab.

**Comment by evilbunny2008** [comment]
The fat partition wasn't unmounted properly, this is different to the utf-8 issue and you just need to run:

`fsck.vfat /dev/mmcblk1p6`
