### ISSUE TITLE
Same MAC-address

### ISSUE THREAD

**Issue by Xake** [ayufan-rock64/linux-build#80]
I have two rock64 booted from SPI, one based on 0.6.1 and one based on 0.6.10.
Both get the same MAC in uboot:
eth1addr=86:e0:c0:ea:fa:c9
ethaddr=86:e0:c0:ea:fa:a9

Is this a known issue?

**Comment by ayufan** [comment]
the same mac for both interfaces you say?

**Comment by ayufan** [comment]
or the same macs on both rocks?

**Comment by Xake** [comment]
Same on both rocks for both interfaces.

Den 5 jan. 2018 22:29 skrev "Kamil Trzciński" <notifications@github.com>:

**Comment by ayufan** [comment]
This is solved in 0.6.12.
