### ISSUE TITLE
e2label: Filesystem has unsupported read-only feature(s) while trying to open /dev/mmcblk1p7

### ISSUE THREAD

**Issue by Rar9** [ayufan-rock64/linux-build#81]
Dist-update from bionic-minimal-rock64-0.6.9-160-arm64.img.xz to 0.6.10  shows this error.

> Setting up linux-rock64-package (0.6.10) ...
> e2label: Filesystem has unsupported read-only feature(s) while trying to open /dev/mmcblk1p7
> Couldn't find valid filesystem superblock.
> dpkg: error processing package linux-rock64-package (--configure):
>  subprocess installed post-installation script returned error exit status 1
> dpkg: dependency problems prevent configuration of linux-rock64:
>  linux-rock64 depends on linux-rock64-package (= 0.6.10); however:
>   Package linux-rock64-package is not configured yet.
> 
> dpkg: error processing package linux-rock64 (--configure):
>  dependency problems - leaving unconfigured
> Processing triggers for flash-kernel (3.75ev3dev5) ...
> Using DTB: rk3328-rock64.dtb
> Installing /usr/lib/linux-image-4.4.103-rockchip-ayufan-162/rockchip/rk3328-rock64.dtb into /boot/dtbs/4.4.103-rockchip-ayufan-162/rk3328-rock64.dtb
> Taking backup of rk3328-rock64.dtb.
> Installing new rk3328-rock64.dtb.
> flash-kernel: installing version 4.4.103-rockchip-ayufan-162
> Taking backup of Image.
> Installing new Image.
> Taking backup of initrd.img.
> Installing new initrd.img.
> Taking backup of dtb.
> Installing new dtb.
> Errors were encountered while processing:
>  linux-rock64-package
>  linux-rock64
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ayufan** [comment]
It seems that we should get rid of this legacy stuff: https://github.com/ayufan-rock64/linux-build/blob/master/package/scripts/postinst.deb#L14

**Comment by ayufan** [comment]
Fixed by: https://github.com/ayufan-rock64/linux-build/commit/84fbe98cee43744fcd271fc2de772947152739d5
