### ISSUE TITLE
"Synchronous Abort" handler, esr 0x02000000

### ISSUE THREAD

**Issue by pgmy64** [ayufan-rock64/linux-build#85]
USB boot get into below error occasionally and require to reprogram the USB boot image in order to recover.  Not sure due to disk corruption or not.

DDR version 1.06 20170424
In
LPDDR3
786MHz
Bus Width=32 Col=11 Bank=8 Row=15/15 CS=2 Die Bus-Width=32 Size=4096MB
ddrconfig:7
OUT

U-Boot SPL 2017.09-g5a90a9a (Jan 12 2018 - 11:06:01)
setup_ddr_param  1
booted from SPI flash
Trying to boot from SPI
NOTICE:  BL31: v1.3(release):f947c7e
NOTICE:  BL31: Built : 11:06:00, Jan 12 2018
NOTICE:  BL31:Rockchip release version: v1.3

U-Boot 2017.09-g5a90a9a (Jan 12 2018 - 11:06:15 +0000), Build: jenkins-linux-build-rock-64-177
scanning bus 2 for devices... 2 USB Device(s) found
scanning bus 3 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found

Device 0: Vendor: SanDisk  Rev: 0405 Prod: SDSSDH2128G
            Type: Hard Disk
            Capacity: 122104.3 MB = 119.2 GB (250069680 x 512)
... is now current device
Scanning usb 0:6...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
reading /extlinux/extlinux.conf
259 bytes read in 21 ms (11.7 KiB/s)
1:      kernel-4.4
Retrieving file: /initrd.img
reading /initrd.img
3536837 bytes read in 178 ms (18.9 MiB/s)
Retrieving file: /Image
reading /Image
2359296 bytes read in 115 ms (19.6 MiB/s)
append: earlycon=uart8250,mmio32,0xff130000 rw root=LABEL=linux-root rootwait rootfstype=ext4 init=/sbin/init coherent_pool=1M ethaddr=66:52:90:cd:89:ae eth1addr=66:52:90:cd:89:ce serial=387ffff93aa4d8b
Retrieving file: /dtb
reading /dtb
44132 bytes read in 27 ms (1.6 MiB/s)
## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
   Loading Ramdisk to fcba1000, end fcf007c5 ... OK
   Loading Device Tree to 00000000fcb93000, end 00000000fcba0c63 ... OK

Starting kernel ...

"Synchronous Abort" handler, esr 0x02000000
ELR:     2fd0000
LR:      fef1735c
x0 : 00000000fcb93000 x1 : 0000000000000000
x2 : 0000000000000000 x3 : 0000000000000000
x4 : 0000000002080000 x5 : 0000000000000001
x6 : 0000000000000008 x7 : 0000000000000000
x8 : 00000000fef9da50 x9 : 0000000001008000
x10: 000000000a200023 x11: 0000000000000002
x12: 0000000000000002 x13: 00000000ffffffff
x14: 00000000fcf0265c x15: 00000000fef169b8
x16: 0000000000000003 x17: 00000000fcba0c64
x18: 00000000fcf0ce08 x19: 0000000000000400
x20: 00000000fefb33b8 x21: 0000000000000000
x22: 0000000000000003 x23: 00000000fcf02908
x24: 00000000fefa1650 x25: 00000000fef8fd90
x26: 00000000fef17300 x27: 0000000000000400
x28: 00000000fcf4e8a0 x29: 00000000fcf02740

Resetting CPU ...

DDR version 1.06 20170424
In
SRX

LPDDR3
786MHz
Bus Width=32 Col=11 Bank=8 Row=15/15 CS=2 Die Bus-Width=32 Size=4096MB
ddrconfig:7
OUT

**Comment by mweisbach** [comment]
Same issue on one of mine ROCK64 devices:

```
append: earlycon=uart8250,mmio32,0xff130000 rw root=LABEL=linux-root rootwait rootfstype=ext4 init=/sbin/init coherent_poo5
Retrieving file: /dtb
reading /dtb
44132 bytes read in 21 ms (2 MiB/s)
## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
   Loading Ramdisk to fcbaa000, end fcf012ba ... OK
   Loading Device Tree to 00000000fcb9c000, end 00000000fcba9c63 ... OK

Starting kernel ...

"Synchronous Abort" handler, esr 0x02000000
ELR:     2fd0000
LR:      fef1735c
x0 : 00000000fcb9c000 x1 : 0000000000000000
x2 : 0000000000000000 x3 : 0000000000000000
x4 : 0000000002080000 x5 : 0000000000000001
x6 : 0000000000000008 x7 : 0000000000000000
x8 : 00000000fef9d960 x9 : 0000000001008000
x10: 000000000a200023 x11: 0000000000000002
x12: 0000000000000002 x13: 00000000ffffffff
x14: 00000000fcf0267c x15: 00000000fef169b8
x16: 0000000000000003 x17: 00000000fcba9c64
x18: 00000000fcf0ce08 x19: 0000000000000400
x20: 00000000fefb3278 x21: 0000000000000000
x22: 0000000000000003 x23: 00000000fcf02928
x24: 00000000fefa1560 x25: 00000000fef8fcd8
x26: 00000000fef17300 x27: 0000000000000400
x28: 00000000fcf2bf20 x29: 00000000fcf02760

Resetting CPU ...
```

**Comment by mweisbach** [comment]
@pgmy64 can you point me to instructions how to "reprogram the USB boot image in order to recover"?

**Comment by pgmy64** [comment]
@mweisbach, i just reflash the USB drive with 'dd'

**Comment by xalius** [comment]
This is related to a bug in flash-kernel after kernel upgrades, fix is work in progress

**Comment by ayufan** [comment]
This is fixed.
