### ISSUE TITLE
Please add RTL8812AU driver to builds

### ISSUE THREAD

**Issue by evilbunny2008** [ayufan-rock64/linux-build#87]
The [802.11ac wifi dongle](https://www.pine64.org/?product=rock64-usb-3-0-dual-band-1200mbps-wifi-802-11abgnac-rtl8812au-adapter) sold in the pine64 store doesn't work out of the box with any image for the rock64, and most likely other boards too.

[Gnab has a fork](https://github.com/gnab/rtl8812au) of the drivers that build on the rock64, but needed a custom make file to make it build.
[rtl8812au.Makefile.txt](https://github.com/ayufan-rock64/linux-build/files/1633311/rtl8812au.Makefile.txt)

**Comment by evilbunny2008** [comment]
I just found a [xenial arm64 dkms package](https://launchpad.net/ubuntu/xenial/arm64/rtl8812au-dkms/4.3.8.12175.20140902+dfsg-0ubuntu2)

It doesn't work on debian stretch though, tries to compile for aarch64 instead of arm64

**Comment by evilbunny2008** [comment]
After a bit messing about I managed to get a working [deb dkms package](https://files.evilbunny.org/rtl8812au-dkms_4.2.2-1_all.deb) that builds on Debian stretch.

**Comment by evilbunny2008** [comment]
I found a more recent version ([v5.2.20](https://github.com/gordboy/rtl8812au)) of rlt8812au driver and built a [dkms deb](https://files.evilbunny.org/rtl8812au-dkms_5.2.20-1_all.deb) package of it.

**Comment by xalius** [comment]
The config options have been added, should be in the next release/pre-release.
