### ISSUE TITLE
booting from HDD/SSD doesn't resize on first boot

### ISSUE THREAD

**Issue by evilbunny2008** [ayufan-rock64/linux-build#90]
Change /usr/local/sbin/resize_rootfs.sh to this and it works.

[resize_rootfs.txt](https://github.com/ayufan-rock64/linux-build/files/1648170/resize_rootfs.txt)

**Comment by ayufan** [comment]
Hardcoding to `/dev/sda` might not be enough too.

Feel free to create a PR here.

**Comment by evilbunny2008** [comment]
What other devices would need to be expanded?

**Comment by ayufan** [comment]
Your HDD/SDD can have any name from `/dev/sd?` space, it depends on ordering of connected devices.

**Comment by evilbunny2008** [comment]
Are there any other devices that need addressing, other than mmcblk* and sd* ?

[resize_rootfs.txt](https://github.com/ayufan-rock64/linux-build/files/1648760/resize_rootfs.txt)
