### ISSUE TITLE
0.6.19 doesn't work with my monitor

### ISSUE THREAD

**Issue by evilbunny2008** [ayufan-rock64/linux-build#97]
My monitor is DVI based but worked with the addition of this edid line in the append section:

`drm_kms_helper.edid_firmware=edid/1920x1080.bin`

However this no longer works with 0.6.19, although serial console still works, I've no idea how to debug this any further.

Also the 0.6.x kernels doesn't drop to 800x600 if the edid is corrupt, where as the 0.5.x kernels did.

**Comment by evilbunny2008** [comment]
[https://github.com/ayufan-rock64/linux-build/files/1692674/uart.txt](https://github.com/ayufan-rock64/linux-build/files/1692674/uart.txt)

**Comment by ayufan** [comment]
This is fixed
